### PR TITLE
Hint for Newline added on quick edit

### LINKED ISSUE #16191: Cannot insert newline into textarea popup
### Describe the bug

This is a regression in phpmyadmin 5 (in phpmyadmin 4.9 is working fine).
If you are listing records from a table and you click on a field (to do a quick edit of field's value), you cannot insert a newline. As soon as you press enter, the field is saved. This is annoying, since you're forced to go into full edit, and then go back to list (and so on...), defeating the purpose of quick editing.

### To Reproduce

See above

### Expected behavior

A newline should be entered in textarea. Some kind of helper could be also acceptable, e.g. pressing alt+enter for newline (keeping simple enter to save)

### Screenshots

Not applicable

### Server configuration

- Operating system: Ubuntu 20.04
- Web server: php internal server
- Database version: mysql 8.0.20
- PHP version: 7.4.3
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Firefox 77.0.1
- Operating system: Ubuntu 20.04

### Additional context

None

### PR DESCRIPTION
**Pull request by olumide95**
### Description
Hint - Shift+Enter to goto a newline
Fixes: #16191

### CODE REVIEW

File: js/messages.php [hunk 1]
```diff
@@ -592,7 +592,10 @@ function () {
 $js_messages['strSubmit'] = __('Submit');
 
 /* For makegrid.js (column reordering, show/hide column, grid editing) */
-$js_messages['strCellEditHint'] = __('Press escape to cancel editing.');
+$js_messages['strCellEditHint'] = __(
+    'Press escape to cancel editing.'
+    . '<br />- Shift+Enter for newline'
+);
```
Comment (williamdes) [inline js/messages.php:598]:
```suggestion
$js_messages['strCellEditHint'] = __(
    'Press escape to cancel editing.'
    . '<br>- <kbd>shift</kbd>+<kbd>enter</kbd> for a newline'
);
```

**Review by williamdes — APPROVED** [review]
LGTM, I am waiting for another reviewer

**Review by MauricioFauth — APPROVED** [review]

**Comment by williamdes** [comment]
Thank you @olumide95 for your contribution !
Sorry for the merge delay, you work will be included in the 5.2 phpMyAdmin series.
