### PR TITLE
Fix #19570 - Check for HTTP_HOST and document the issue in FAQ

### LINKED ISSUE #19570: $_SERVER['HTTP_HOST'] doesn't exist when requesting via HTTP/3 on nginx
### Describe the bug

`$_SERVER['HTTP_HOST']` doesn't exist when requesting via HTTP/3 on nginx. Because of this there are 3 bugs that I've seen.

- when exporting settings, there's no hostname in filename - `phpMyAdmin-config-.json`
- the hostname is missing from title - `@HTTP_HOST@` is empty
- it breaks 2FA, instead of pma.example.com I get ` ` - empty string

### To Reproduce

1. Have nginx with HTTP/3 enabled.
2. See errors I described above.

### Expected behavior

A warning message should be added in the footer, if $_SERVER['HTTP_HOST'] doesn't exist. Something like this:

```
$_SERVER['HTTP_HOST'] is missing. This may cause phpMyAdmin to malfunction. If you are using nginx with HTTP/3 enabled, add fastcgi_param HTTP_HOST $host; to your nginx configuration.
```

### Screenshots

Image

### Server configuration

- Web server: nginx/1.27.3 with HTTP/3 enabled
- phpMyAdmin version: 5.2.3-dev, 6.0.0-dev

### Additional context

```
https://github.com/php/php-src/issues/13021
https://github.com/nginx-quic/nginx-quic/issues/3
https://trac.nginx.org/nginx/ticket/2281
https://github.com/nginx/nginx/issues/455
```

### PR DESCRIPTION
**Pull request by liviuconcioiu**
### Description

2FA can't be used on nginx with HTTP/3, since `$_SERVER['HTTP_HOST']` is missing.

**See the missing host in decoded QR:**

before

**After:**

after

If someone wants to make changes, please push your commit.

Fixes #19570

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

File: libraries/classes/Controllers/HomeController.php [hunk 1]
```diff
@@ -398,6 +399,21 @@ private function checkRequirements(): void
             ];
         }
 
+        /**
+        * Check for missing HTTP_HOST
+        * This commonly occurs with nginx >= 1.25.0 and HTTP/3 configurations
+        */
```
Comment (williamdes) [inline libraries/classes/Controllers/HomeController.php]:
```suggestion
         * Check for missing HTTP_HOST
         * This commonly occurs with nginx >= 1.25.0 and HTTP/3 configurations
         */
```

**Review by williamdes — APPROVED** [review]
Very cool !

**Review by williamdes — APPROVED** [review]

**Review by MauricioFauth — APPROVED** [review]
