### PR TITLE
fixed error in change button for column names with backslash

### LINKED ISSUE #15425: Backslash in column name resulting an error in editing
### Describe the bug

Backslash is allowed as column name, therefore it broke edit feature . (see screenshot)

### To Reproduce

I was accidentally put backslash when pressing enter, and had my column name with backslash

### Screenshots

1. Backslash Column Name
image

2. When using change button
image

### Server configuration

- Operating system: Windows 10
- Web server: Apache/2.4.39 (Win64) OpenSSL/1.1.1c PHP/7.2.20
- Database version: MariaDB 10.3.16
- PHP version: 7.2.20
- phpMyAdmin version: 4.9.0.1

### Client configuration

- Browser: Chrome Latest Version
- Operating system: WIndows 10

### Additional context

Well you can do sql query to change it, but you should be able to do this by pressing change button

### PR DESCRIPTION
**Pull request by rahgurung**
Signed-off-by: Rahul Gurung <gurungrahul2@gmail.com>

Closes #15425

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

File: libraries/classes/Controllers/Table/TableStructureController.php [hunk 1]
```diff
@@ -524,7 +524,7 @@ protected function displayHtmlForColumnChange($selected, $action)
         $fields_meta = array();
         for ($i = 0; $i < $selected_cnt; $i++) {
             $value = $this->dbi->getColumns(
-                $this->db, $this->table, $selected[$i], true
+                $this->db, $this->table, addslashes($selected[$i]), true
```
Comment (williamdes) [inline libraries/classes/Controllers/Table/TableStructureController.php]:
```suggestion
                $this->db, $this->table, $this->dbi->escapeString($selected[$i]), true
```

Maybe this would be better ?

**Review by williamdes — APPROVED** [review]

**Review by williamdes — APPROVED** [review]
Merged, thanks @gurrrung !
