### PR TITLE
Fixed Action Links UI

### LINKED ISSUE #15780: Unexpected UI of action links
### Describe the bug

Some action links are not clearly visible

### To Reproduce

1. Go to 'Settings -> Main Panel -> Browse Mode'
2. Change `How to display various action links` to Text
3. Go To any Table Structure
4. See error in Action Links

### Expected behavior

AFAIK Action Links should be visible in blue

### Screenshots
image

### PR DESCRIPTION
**Pull request by yashrajbothra**
### Description

1. Removed `ActionLinkMode` check because it already there in `getIcon()`;

Before:  image

After:  image

2. Added Space between links using `&emsp;` 

Before:  image

After: image

Fixes #15780

### CODE REVIEW

File: libraries/classes/Display/Results.php [hunk 1]
```diff
@@ -4920,8 +4920,8 @@ private function _getResultsOperations(
 
         // Displays "printable view" link if required
         if ($displayParts['pview_lnk'] == '1') {
-            $results_operations_html .= $this->_getPrintviewLinks();
-            $results_operations_html .= $this->_getCopytoclipboardLinks();
+            $results_operations_html .= $this->_getPrintviewLinks() . "&emsp;";
+            $results_operations_html .= $this->_getCopytoclipboardLinks() . "&emsp;";
```
Comment (yashrajbothra) [inline libraries/classes/Display/Results.php]: If this doesn't look good than i can also use some class to fix.

Comment (williamdes) [reply libraries/classes/Display/Results.php]: If you can find a fancy css solution that would be better ;)

File: libraries/classes/Display/Results.php [hunk 2]
```diff
@@ -4795,7 +4795,7 @@ private function _getLinkForCreateView(array $analyzed_sql_results, $url_query)
                         __('Create view'),
                         true
                     ),
-                    ['class' => 'create_view ajax']
+                    ['class' => 'create_view ajax' , 'class' => 'btn']
```
Comment (yashrajbothra) [inline libraries/classes/Display/Results.php]: @williamdes this looks okay?

Comment (williamdes) [reply libraries/classes/Display/Results.php]: The code looks good, can you post a screenshot?

Comment (yashrajbothra) [reply libraries/classes/Display/Results.php]: image

**Review by williamdes — APPROVED** [review]
:100:

**Comment by williamdes** [comment]
@sudo-bot deploy PR

@yashrajbothra I added you to the list of allowed deploys usernames

**Comment by williamdes** [comment]
Thank you for your contribution @yashrajbothra !
