### PR TITLE
Fixed the test cases

### LINKED ISSUE #18457: Test cases failing
### Describe the bug

Test cases are failing.

### To Reproduce

1. Go to root of the project.
2. Run `.vendor/bin/phpunit`

### Expected behavior

Tests should run successfully.

### Screenshots

image
image

### Server configuration

- Operating system: Ubuntu 20.04
- Web server: Apache 2
- Database version: MySQL 8.0
- PHP version: 8.1
- phpMyAdmin version:6.0.0-dev

### Additional context:

**Trace:**

```
There were 4 failures:

1) PhpMyAdmin\Tests\UtilTest::testLocalisedDate with data set #13
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'mer. 31 mars 2021 à 03:25'
+'Mar 31, 2021 at 03:25 AM'

/var/www/open-source/phpmyadmin/test/classes/UtilTest.php:972
/var/www/open-source/phpmyadmin/vendor/phpunit/phpunit/phpunit:99
/var/www/open-source/phpmyadmin/vendor/bin/phpunit:123

2) PhpMyAdmin\Tests\Config\ServerConfigChecksTest::testBlowfishWithValidSecret
Failed asserting that an array does not have the key 'error'.

/var/www/open-source/phpmyadmin/test/classes/Config/ServerConfigChecksTest.php:178
/var/www/open-source/phpmyadmin/vendor/phpunit/phpunit/phpunit:99
/var/www/open-source/phpmyadmin/vendor/bin/phpunit:123

3) PhpMyAdmin\Tests\Config\ServerConfigChecksTest::testBlowfishWithInvalidSecret
Failed asserting that an array does not have the key 'error'.

/var/www/open-source/phpmyadmin/test/classes/Config/ServerConfigChecksTest.php:154
/var/www/open-source/phpmyadmin/vendor/phpunit/phpunit/phpunit:99
/var/www/open-source/phpmyadmin/vendor/bin/phpunit:123

4) PhpMyAdmin\Tests\Controllers\Table\ImportControllerTest::testImportController
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
         <div class="card-header">File to import:</div>
         <div class="card-body">
                                 <p class="card-text">
-              File may be compressed (gzip, bzip2, zip) or uncompressed.<br>
+              File may be compressed (gzip, zip) or uncompressed.<br>
               A compressed file's name must end in <strong>.[format].[compression]</strong>. Example: <strong>.sql.zip</strong>            </p>
           
                       <div class="mb-3">

/var/www/open-source/phpmyadmin/test/classes/Controllers/Table/ImportControllerTest.php:82
/var/www/open-source/phpmyadmin/vendor/phpunit/phpunit/phpunit:99
/var/www/open-source/phpmyadmin/vendor/bin/phpunit:123

FAILURES!
Tests: 4321, Assertions: 16865, Failures: 4, Skipped: 41.
```

### PR DESCRIPTION
**Pull request by SachinBahukhandi**
### Description

Please describe your pull request.

Fixes #18457

### CODE REVIEW

**Review by faissaloux — CHANGES_REQUESTED** [review]

File: test/classes/Config/ServerConfigChecksTest.php [hunk 1]
```diff
@@ -128,6 +134,12 @@ public function testBlowfish(): void
         $this->assertArrayNotHasKey('error', $messages);
     }
 
+    /**
+     * Test for imports
```
[the remark this answers is not in the document]
Comment (SachinBahukhandi) [reply test/classes/Config/ServerConfigChecksTest.php:138]: I have fixed it. Thanks for pointing out!

File: test/classes/Config/ServerConfigChecksTest.php [hunk 2]
```diff
@@ -154,6 +166,12 @@ public function testBlowfishWithInvalidSecret(): void
...
```
[the remark this answers is not in the document]
Comment (SachinBahukhandi) [reply test/classes/Config/ServerConfigChecksTest.php]: I have fixed it. Thanks for pointing out!

File: test/classes/Config/ServerConfigChecksTest.php [hunk 3]
```diff
@@ -94,6 +94,12 @@ public function testManyErrors(): void
         );
     }
 
+    /**
+     * Test for imports
```
[the remark this answers is not in the document]
Comment (faissaloux) [reply test/classes/Config/ServerConfigChecksTest.php:98]: You didn't correct this, either correct the description or remove it since the function name doesn't need more explanation

File: test/classes/Config/ServerConfigChecksTest.php (hunk 1 above)
[the remark this answers is not in the document]
Comment (faissaloux) [reply test/classes/Config/ServerConfigChecksTest.php:138]: You didn't correct this, either correct the description or remove it since the function name doesn't need more explanation

File: test/classes/Config/ServerConfigChecksTest.php [hunk 4]
```diff
@@ -94,6 +94,12 @@ public function testManyErrors(): void
...
+     *
+     * @requires extension bz2
+     * @requires extension zip
```
Comment (faissaloux) [inline test/classes/Config/ServerConfigChecksTest.php:101]:
```suggestion
     * @requires extension sodium
```

**Review by faissaloux — CHANGES_REQUESTED** [review]

File: test/classes/Config/ServerConfigChecksTest.php (hunk 4 above)
Comment (SachinBahukhandi) [reply test/classes/Config/ServerConfigChecksTest.php:99]: > 

Done. Kindly verify.

File: test/classes/Config/ServerConfigChecksTest.php [hunk 5]
```diff
@@ -128,6 +131,10 @@ public function testBlowfish(): void
         $this->assertArrayNotHasKey('error', $messages);
     }
 
+    /**
+     * @requires extension bz2
+     * @requires extension zip
+     */
     public function testBlowfishWithInvalidSecret(): void
```
Comment (faissaloux) [inline test/classes/Config/ServerConfigChecksTest.php:138]:
```suggestion
    /**
     * @requires extension bz2
     * @requires extension zip
     * @requires extension sodium
     */
    public function testBlowfishWithInvalidSecret(): void
```

File: test/classes/Config/ServerConfigChecksTest.php [hunk 6]
```diff
@@ -154,6 +161,12 @@ public function testBlowfishWithInvalidSecret(): void
         $this->assertArrayNotHasKey('error', $messages);
     }
 
+    /**
+     * Test for blowfish_secret session
+     *
+     * @requires extension bz2
+     * @requires extension zip
+     */
     public function testBlowfishWithValidSecret(): void
```
Comment (faissaloux) [inline test/classes/Config/ServerConfigChecksTest.php:170]:
```suggestion
    /**
     * @requires extension bz2
     * @requires extension zip
     * @requires extension sodium
     */
    public function testBlowfishWithValidSecret(): void
```

**Review by faissaloux — CHANGES_REQUESTED** [review]
Last changes for me

File: test/classes/Config/ServerConfigChecksTest.php (hunk 6 above)
Comment (SachinBahukhandi) [reply test/classes/Config/ServerConfigChecksTest.php:171]: > 

Done. Please verify and mark as resolved, if it appears fine. Thanks!

File: test/classes/Config/ServerConfigChecksTest.php (hunk 5 above)
Comment (SachinBahukhandi) [reply test/classes/Config/ServerConfigChecksTest.php]: > /**
>      * @requires extension bz2
>      * @requires extension zip
>      * @requires extension sodium
>      */

Done. Please verify and mark as resolved, if it appears fine. Thanks!

**Review by faissaloux — APPROVED** [review]

File: test/classes/Config/ServerConfigChecksTest.php (hunk 6 above)
Comment (faissaloux) [reply test/classes/Config/ServerConfigChecksTest.php]: I don't have write access to resolve those conversations, @williamdes can do after his review.

Comment (SachinBahukhandi) [reply test/classes/Config/ServerConfigChecksTest.php]: Cool, no problem, I would do it.

File: test/classes/Config/ServerConfigChecksTest.php [hunk 7]
```diff
@@ -128,6 +131,11 @@ public function testBlowfish(): void
         $this->assertArrayNotHasKey('error', $messages);
     }
 
+    /**
+     * @requires extension bz2
+     * @requires extension zip
```
Comment (williamdes) [inline test/classes/Config/ServerConfigChecksTest.php:136]: is this true that this test requires the two extensions ?
what does it do on your end when you run the tests without the two lines ?

File: test/classes/Config/ServerConfigChecksTest.php [hunk 8]
```diff
@@ -94,6 +94,9 @@ public function testManyErrors(): void
         );
     }
 
+    /**
+     * @requires extension sodium
+     */
```
Comment (williamdes) [inline test/classes/Config/ServerConfigChecksTest.php:99]: I am not sure it makes sense to add this line because sodium is now bundled into PHP since 7.2.0

File: test/classes/Config/ServerConfigChecksTest.php (hunk 7 above)
Comment (faissaloux) [reply test/classes/Config/ServerConfigChecksTest.php:136]: Yes it does require both extensions `bz2` and `zip`

Here is the failing test
Screenshot 2023-06-12 232537

After checking the `error`
Screenshot 2023-06-12 232827

File: test/classes/Config/ServerConfigChecksTest.php (hunk 8 above)
Comment (faissaloux) [reply test/classes/Config/ServerConfigChecksTest.php:99]: But the tests fails when `sodium` is not enabled.

Comment (williamdes) [reply test/classes/Config/ServerConfigChecksTest.php:99]: Sodium can not be not enabled, how do you do that?

Comment (faissaloux) [reply test/classes/Config/ServerConfigChecksTest.php:99]: Yeah I can't on Linux but I can enable/disable it on Windows.

Comment (faissaloux) [reply test/classes/Config/ServerConfigChecksTest.php:99]: Yeah yeah you are right 😅 , `@requires extension sodium` should be removed

Comment (williamdes) [reply test/classes/Config/ServerConfigChecksTest.php:99]: That said we should add sodium to the checked extensions that phpmyadmin requires even if it's not possible to have it missing
since windows can
it would avoid some crashing while booting phpmyadmin on a weird php config
right @MauricioFauth?

Comment (MauricioFauth) [reply test/classes/Config/ServerConfigChecksTest.php:99]: I was going to say that it was already been checked, but it's not. We should definitely add that check.

Comment (Seb33300) [reply test/classes/Config/ServerConfigChecksTest.php:99]: Sodium is a requirement in the `composer.json:
https://github.com/phpmyadmin/phpmyadmin/blob/a79eff2a894e31734031dd8f8f5386accd4fcc61/composer.json#L57

Comment (faissaloux) [inline test/classes/Config/ServerConfigChecksTest.php:99]:
```suggestion

```

File: test/classes/Config/ServerConfigChecksTest.php [hunk 9]
```diff
@@ -128,6 +131,11 @@ public function testBlowfish(): void
         $this->assertArrayNotHasKey('error', $messages);
     }
 
+    /**
+     * @requires extension bz2
+     * @requires extension zip
+     * @requires extension sodium
+     */
```
Comment (faissaloux) [inline test/classes/Config/ServerConfigChecksTest.php:138]:
```suggestion
    /**
     * @requires extension bz2
     * @requires extension zip
     */
```

File: test/classes/Config/ServerConfigChecksTest.php [hunk 10]
```diff
@@ -154,6 +162,11 @@ public function testBlowfishWithInvalidSecret(): void
...
```
Comment (faissaloux) [inline test/classes/Config/ServerConfigChecksTest.php:169]:
```suggestion
    /**
     * @requires extension bz2
     * @requires extension zip
     */
```

**Review by faissaloux — CHANGES_REQUESTED** [review]

File: test/classes/Config/ServerConfigChecksTest.php (hunk 8 above)
Comment (SachinBahukhandi) [reply test/classes/Config/ServerConfigChecksTest.php:99]: Done

File: test/classes/Config/ServerConfigChecksTest.php (hunk 10 above)
Comment (SachinBahukhandi) [reply test/classes/Config/ServerConfigChecksTest.php]: Done

**Review by faissaloux — APPROVED** [review]

**Review by MauricioFauth — APPROVED** [review]
