### PR TITLE
Fix#14611 Enter Key submission JS error fixed

### LINKED ISSUE #14611: Index creation - Enter key form submission - Fatal JS Error
### Form submission with "Enter" key throws JavaScript error

While creating indexes for a column, after typing the index name and pressing Enter key instead of pressing the **Go** button to submit the form throws JavaScript fatal error. Observing this bug from previous versions as well.

### To Reproduce

1. Create a table under a database.
2. Enter a name for the table column and choose a suitable datatype.
3. Choose any type of index, say **Index** from Index column.
4. Type a name for the index and press the Enter key after typing the index name.

### Expected behavior
The form gets submitted and the modal gets close.

### Screenshots

image

### Server configuration

phpMyAdmin demo https://demo.phpmyadmin.net
- Web server: nginx/1.10.3
- Database version: 5.0.12-dev
- PHP version: 7.2.8
- phpMyAdmin version: 5.0.0

### PR DESCRIPTION
**Pull request by kartik1000**
### Description

On pressing the enter key as shortcut for dialog submission in index dialog box used to throw up fatal js error, this has been fixed in this pull request. The Enter key will now work as expected. 

Fixes #14611 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: js/indexes.js [hunk 1]
```diff
@@ -385,6 +386,13 @@ function PMA_showAddIndexDialog (source_array, array_index, target_columns, col_
                     width: 450,
                     minHeight: 250,
                     open: function () {
+                        $(this).keypress(function(e){
+                        if (e.which == 13 || e.keyCode == 13 || window.event.keyCode == 13) {
```
Comment (williamdes) [inline js/indexes.js]: can you indent this block ?

**Review by williamdes — APPROVED** [review]

File: js/indexes.js (hunk 1 above)
Comment (kartik1000) [reply js/indexes.js]: Yes, I will do it right away.

**Comment by williamdes** [comment]
image


@kartik1000 can you fix the bug ?

The index name is not updated using enter key

Please, hard reset your local branch onto 627fd9f546c18bb085745d8b8d558d2e777ac730

**Comment by kartik1000** [comment]
@williamdes, I think it is performing ok for me if this is what you mean. If you mean something else can you tell me how to replicate it? 
Jan-03-2020 13-39-24

**Comment by williamdes** [comment]
@kartik1000 I will have a look in depth because it seems not to work for me

**Comment by kartik1000** [comment]
ok @williamdes, let me know when you able to replicate it :)

**Review by williamdes — APPROVED** [review]

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
@kartik1000 I eddited your PR while checking it, can you please review and let me know if it looks good to you ?

https://github.com/phpmyadmin/phpmyadmin/issues/14611#issuecomment-590070755

**Comment by williamdes** [comment]
:ping_pong: @kartik1000

**Comment by kartik1000** [comment]
Sorry @williamdes. Missed the above comment. I will review and let you know for the same :)

**Comment by kartik1000** [comment]
@williamdes. It works absolutely fine now. There was some unusual behaviour which I had found earlier that use to happen only when enter was pressed for the first time. But even that is fixed now. This looks good to me👍

**Comment by williamdes** [comment]
Thank you @kartik1000 ! :rocket:

**Comment by kartik1000** [comment]
Thank you as well @williamdes for completing it so that it can be successfully merged :)

**Comment by williamdes** [comment]
If you can review all the pull-requests you have open so I can merge all of them too ;) ?

**Comment by kartik1000** [comment]
Yes. Surely lets finish them one by one.
