### PR TITLE
Fix notification links

### LINKED ISSUE #18241: Error SQL query: "Copy" doesn't copy
5.2.1 on Docker

This "Copy" link doesn't work in the popup. Instead, it just closes the popup:

sshot-2023-03-10-23-11-10-1

It does work in the banner that appears at the bottom of the page:

sshot-2023-03-10-23-11-45-1

image

To reproduce, try to Insert a new row on a table (using the "Insert" tab),
and put some invalid data.
Then press Go.

### PR DESCRIPTION
**Pull request by faissaloux**
Fixes #18241

### CODE REVIEW

File: libraries/classes/Controllers/JavaScriptMessagesController.php [hunk 1]
```diff
@@ -386,6 +386,7 @@ private function setMessages(): void
             'strHideQueryBox' => __('Hide query box'),
             'strShowQueryBox' => __('Show query box'),
             'strEdit' => __('Edit'),
+            'strEditQuery' => __('Edit query'),
```
Comment (williamdes) [inline libraries/classes/Controllers/JavaScriptMessagesController.php:389]:
```suggestion
            'strEditInlineQuery' => __('Inline edit query'),
```
Does it still make sense to use the already existing variant ? (to avoid translators work)

File: js/src/functions.js [hunk 2]
```diff
@@ -2092,6 +2093,34 @@ $(function () {
             $('#copyStatus').remove();
         }, 2000);
     });
+
+    $(document).on('mouseover', '.ajax_notification a', function (event) {
```
Comment (williamdes) [inline js/src/functions.js:2097]: Be aware that for each .on you need a .off in the registerTeardown 
Or the events will stay hooked when the context is destroyed

**Comment by faissaloux** [comment]
https://user-images.githubusercontent.com/60013703/224492538-cacf3a0a-8e2c-4107-916c-683c2c1d2f59.mp4

File: js/src/functions.js [hunk 3]
```diff
@@ -2092,6 +2093,34 @@ $(function () {
...
+        Functions.tooltip(
+            $(".ajax_notification"),
+            'span',
+            Messages.strEditQuery
+        );
+    });
+
+    $(document).on('mouseover', '.ajax_notification a.copyQueryBtn', function (event) {
```
Comment (williamdes) [inline js/src/functions.js:2105]:
```suggestion
    $(document).on('mouseover', '.ajax_notification a.copyQueryBtn', function () {
```
You can remove the parameter for all functions that do not use it

**Comment by williamdes** [comment]
This PR only seems to add lines, so is the current implementation incomplete or is this more a workaround than a bug fix ?

File: libraries/classes/Controllers/JavaScriptMessagesController.php (hunk 1 above)
Comment (faissaloux) [reply libraries/classes/Controllers/JavaScriptMessagesController.php]: Updated 👌🏻 

`strEdit` is used in designer history that's why I didn't remove it

File: js/src/functions.js (hunk 3 above)
Comment (faissaloux) [reply js/src/functions.js]: Done 👌🏻

File: libraries/classes/Controllers/JavaScriptMessagesController.php [hunk 4]
```diff
@@ -386,6 +386,7 @@ private function setMessages(): void
             'strHideQueryBox' => __('Hide query box'),
             'strShowQueryBox' => __('Show query box'),
             'strEdit' => __('Edit'),
+            'strEditInlineQuery' => __('Inline edit query'),
```
Comment (williamdes) [inline libraries/classes/Controllers/JavaScriptMessagesController.php:389]: I am sorry about that, but can you revert to your previous version ?
Now that you posted the video I understand it's for the tooltip

**Comment by faissaloux** [comment]
@williamdes The bug was fixed on the first two commits ( `mouseup` event ).

Then found out about the message `Click to dismiss this notification` appears on `Copy` and `Edit` links too which doesn't make sense, so I have fixed it using the tooltip messages that adds up much lines.

File: js/src/functions.js [hunk 5]
```diff
@@ -2092,6 +2093,28 @@ $(function () {
             $('#copyStatus').remove();
         }, 2000);
     });
+
+    $(document).on('mouseover', '.ajax_notification a', function (event) {
+        let message = $.inArray('copyQueryBtn', event.target.classList) != -1 ? Messages.strCopyToClipboard : Messages.strEditInlineQuery;
```
Comment (williamdes) [inline js/src/functions.js:2098]: jQuery has a `hasClass` method :)

File: js/src/functions.js (hunk 2 above)
Comment (faissaloux) [reply js/src/functions.js:2097]: Yeah I have tried to but it doesn't work as expected after dismissing the notification and show it again.

File: js/src/functions.js (hunk 5 above)
Comment (faissaloux) [reply js/src/functions.js]: Yeah 👍🏻 , done!

File: js/src/functions.js [hunk 6]
```diff
@@ -2092,6 +2093,26 @@ $(function () {
...
     });
+
+    $(document).on('mouseover mouseleave', '.ajax_notification a', function (event) {
+        let message = '';
+
+        if (event.type === 'mouseover') {
+            message = $(this).hasClass('copyQueryBtn') ? Messages.strCopyToClipboard : Messages.strEditQuery;
+        } else {
+            message = Messages.strDismiss
+        }
```
Comment (williamdes) [inline js/src/functions.js:2104]:
```suggestion
        let message = Messages.strDismiss;

        if (event.type === 'mouseover') {
            message = $(this).hasClass('copyQueryBtn') ? Messages.strCopyToClipboard : Messages.strEditQuery;
        }
```

**Review by williamdes — APPROVED** [review]
That's quite nice, let see what @MauricioFauth thinks

**Review by MauricioFauth — APPROVED** [review]
