### PR TITLE
Fix #16199 - Dragging of tables in designer

### LINKED ISSUE #16199: Dragging in Designer is inconsistent and frustrating
### Describe the bug

When using Designer, I drag the tables around. Sometimes, the table gets "stuck" at what seems like a boundary area; for instance in this screenshot, "rental" is as far up and to the right as I can easily make it go:

image

A symptom of the problem is that the item stays selected and drags around through the window even when my mouse button isn't clicked; so in this case I clicked and dragged on the "rental" window, it got "stuck" in the upper right, then I let go of the mouse, and it still drags around with my cursor movement. Once a window is "captured" in this way, rapid mouse movement usually leaves the window where it was and very slow movement drags the window along with the cursor.

Another symptom is that, when the dragging problem is occurring, the cursor movements select text (such as the tabs across the top, or the words in the pop out menu, or in extreme cases even the database names in the navigation pane). 

The problem is exacerbated by moving the mouse quickly while dragging, but isn't exclusively caused by that.

### To Reproduce

Go to Designer, try to drag a few windows around.

Move windows toward the upper third or right hand third of the available canvas.

Move windows rapidly.

### Server configuration

- Operating system: Debian
- Web server: Apache 
- Database version: MariaDB 10.3.22
- PHP version: 7.4.6
- phpMyAdmin version: QA_4_9, QA_5_0, master

### Client configuration

- Browser: Firefox 77, Chrome 83
- Operating system: MacOS

- Browser: Edge 44
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by kimdre**
### Description

Please describe your pull request.

Fixes the buggy dragging/movement of table boxes in the designer which causes them to get stuck or move weirdly.

Described in #16199

Fixes: #16199

I tested it with the latest version of the official docker image.

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
Thank you, following back the tracks it seems it was introduced by (myself ?!) for a bug fix: https://github.com/phpmyadmin/phpmyadmin/commit/75b185a701263e744256cf4a40e20ac8e4587a6c

**Review by williamdes — APPROVED** [review]
Awesome !!

File: js/src/designer/move.js [hunk 1]
```diff
@@ -1963,13 +1963,13 @@ DesignerMove.enablePageContentEvents = function () {
     $('#page_content').off('mousedown');
     $('#page_content').off('mouseup');
     $('#page_content').off('mousemove');
```
Comment (williamdes) [inline js/src/designer/move.js:1965]:
```suggestion
    $(document).off('mousedown');
    $(document).off('mouseup');
    $(document).off('mousemove');
```

**Comment by williamdes** [comment]
Also added b55c9515031ae995ea3098399ae62d454c233521
