### PR TITLE
Auto Save Query database and table independent (fix SQL query auto save)

### LINKED ISSUE #15997: Auto saved query no longer loading
### Describe the bug

The get auto-saved query button always shows the message

"No previously auto-saved query is available. Loading default query."

Rather than loading a previous query

### To Reproduce

1. Login to PMA
2. Go to the SQL tab for a particular table
3. Write and run an SQL statement
4. Return to the SQL tab and press "Get auto-saved query"
5. Message prompt "No previously auto-saved query is available. Loading default query."

### Expected behavior

On pressing Get auto-saved query it should load the previous query that was created and ran

### Screenshots

Initial Error
image

I can see the SQL being written into localStorage as I type
image
image

But on submitting a query I can see this value is removed in /js/vendor/sql.js
image

### Server configuration

- Operating system: Linux
- Web server: Apache/2.4.38 (Debian) 
- PHP version:  7.4.1 
- phpMyAdmin version:  5.0.1

### Client configuration

- Browser: Firefox 73.0.1 (64-bit)
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by shucon**
Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Please describe your pull request.

Fixes #15997

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by shucon** [comment]
Should we add a function where we remove the localStorage of queries if the table or database is removed?

File: js/src/functions.js [hunk 1]
```diff
@@ -1268,10 +1269,17 @@ Functions.insertQuery = function (queryType) {
...
     } else if (queryType === 'saved') {
-        if (isStorageSupported('localStorage') && typeof window.localStorage.autoSavedSql !== 'undefined') {
-            Functions.setQuery(window.localStorage.autoSavedSql);
-        } else if (Cookies.get('autoSavedSql')) {
-            Functions.setQuery(Cookies.get('autoSavedSql'));
+        var db = $('input[name="db"]').val();
+        table = $('input[name="table"]').val();
+        var key = 'autoSavedSql_' + db;
+        if (table != undefined) {
+            key += '.' + table;
```
Comment (williamdes) [inline js/src/functions.js:1276]: Please consider such code as bad, never try to make an identifier based on db.table

If it is the actual behavior you can keep it but it it bad in different ways, see my designer refactoring.

**Review by williamdes — APPROVED** [review]
