### PR TITLE
Fix #16130 - Local documentation links

### LINKED ISSUE #16130: Local documentation links have non escaped BB code shown to the user
### To Reproduce

1. Have mysqli extension missing
2. Have local documentation built (`cd doc && make html`)

### Expected behavior

Show a link to local documentation

### Screenshots

image

### Server configuration

- phpMyAdmin version: 5.x

### Additional context

See Core::sanitizeMessage to start the fix and apply the patch to have a test case

```diff
diff --git a/test/classes/MessageTest.php b/test/classes/MessageTest.php
index 1199f71574..ecd2db9066 100644
--- a/test/classes/MessageTest.php
+++ b/test/classes/MessageTest.php
@@ -428,6 +428,10 @@ class MessageTest extends PmaTestCase
                 . 'latest%2Fsetup.html%23foo" '
                 . 'target="documentation">link</a>',
             ],
+            [
+                '[a@doc/html/faq.html#faqmysql@documentation]link[/a]',
+                '<a href="doc/html/faq.html#faqmysql">link</a>',
+            ],
         ];
     }
```

Run: `./vendor/bin/phpunit --filter=testDecodeBB --no-coverage`

Use branch: QA_5_0 as a base branch to the fix and the PR

### PR DESCRIPTION
**Pull request by petrduda**
Signed-off-by: Petr Duda <petrduda@seznam.cz>

### Description

Corrected the bb code tags for local documentation (i.e. [doc]) in the mysqli missing extension warning; added the respective test cases.

Fixes #16130

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: libraries/classes/Sanitize.php [hunk 1]
```diff
@@ -141,9 +141,11 @@ public static function replaceBBLink(array $found)
     public static function replaceDocLink(array $found)
     {
         if (count($found) >= 4) {
+            /* doc@page@anchor pattern */
```
Comment (ibennetch) [inline libraries/classes/Sanitize.php:144]: Good use of documentation here.

File: test/classes/MessageTest.php [hunk 2]
```diff
@@ -428,6 +428,18 @@ public function decodeBBDataProvider()
                 . 'latest%2Fsetup.html%23foo" '
                 . 'target="documentation">link</a>',
             ],
+            [
```
Comment (ibennetch) [inline test/classes/MessageTest.php:431]: Thanks for writing a new test case!

**Review by williamdes — CHANGES_REQUESTED** [review]
:100: Very good work, I really appreciate each of your contributions !

~~One small issue is that it does not fix the case where the user has local documentation built (`cd doc && make html`)
image~~

**Review by williamdes — APPROVED** [review]
I was on the wrong branch :(
Everything is fine :)
