### PR TITLE
fix #18563 - can't access property toString, data[j][0] is null

### LINKED ISSUE #18563: can't access property "toString", data[j][0] is null
### Describe the bug

`can't access property "toString", data[j][0] is null`

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/&db=performance_schema&table=memory_summary_by_account_by_event_name
2. Click on `Display chart`
3. See error

### Expected behavior

No error should happen.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/c45ec96b-632a-40cd-888a-d7d633640691

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### PR DESCRIPTION
**Pull request by talktogauravsingh**
### Description

I fixed the issue of not being able to access the 'toString' property because 'data[j][0]' is null.

Fixes #18563

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: js/src/chart.js [hunk 1]
```diff
@@ -287,7 +287,7 @@ JQPlotLineChart.prototype.populateOptions = function (dataTable, options) {
     if (optional.axes.xaxis.ticks.length === 0) {
         var data = dataTable.getData();
         for (var j = 0; j < data.length; j++) {
-            optional.axes.xaxis.ticks.push(data[j][0].toString());
+            optional.axes.xaxis.ticks.push(data[j][0]?.toString());
```
Comment (MauricioFauth) [inline js/src/chart.js:290]: You can't use this syntax on `QA_5_2`. Only on `master`.

**Review by MauricioFauth — CHANGES_REQUESTED** [review]

File: js/src/chart.js (hunk 1 above)
Comment (MauricioFauth) [inline js/src/chart.js:290]:
```suggestion
            optional.axes.xaxis.ticks.push(data[j][0] !== null ? data[j][0].toString() : null);
```

**Review by MauricioFauth — APPROVED** [review]

**Comment by MauricioFauth** [comment]
Merged, thanks for your contribution!
