### PR TITLE
Fix #17703 - Multiple Datepicker issues resolved

### LINKED ISSUE #17703: Datepicker appear on all fields, not just date
### Describe the bug

Datepicker appears on all column types, not just date. Both 5.2 and master are affected.

### To Reproduce

1. Create a table with different column types and date.
2. Click on the date row.
3. Click on other column types.
4. See the datepicker appearing.

### Expected behavior

Datepicker should not appear for other column types.

### Screenshots

https://user-images.githubusercontent.com/25424343/187782936-8fe5c310-6e3f-45f9-a243-6a306cae47a8.mp4

### Server configuration

- Operating system: Linux
- Web server: nginx/1.14.2
- Database version: MySQL 8.0.18
- PHP version: 7.4.29
- phpMyAdmin version: 5.3.0-dev

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

Add any other context about the bug here.

### PR DESCRIPTION
**Pull request by vimalMK**
Signed-off-by: Vimal K <vimalinfo10@gmail.com>

### Description

1. Datepicker appears on all column types, not just date - Fixed
2. If you copy a row, on the bottom left appears the date picker - Fixed
3.  If the column type is only date, the date picker doesn't appear - Fixed
4. ~~Tooltip appearing in a wrong place - Fixed (Styling)~~ Reverted by @williamdes 

Fixes: #17703

### 1
[Datepicker appears on all column types, not just date.webm](https://user-images.githubusercontent.com/35750792/199934574-ecfe6138-04df-4996-9c47-ade82d2e50e1.webm)

### 2
[If you copy a row, on the bottom left appears the date picker.webm](https://user-images.githubusercontent.com/35750792/199934797-06dd0660-8db4-4490-8b50-2e79c6e0add5.webm)

### 3
[If the column type is only date, the date picker doesn't appear.webm](https://user-images.githubusercontent.com/35750792/199934821-a9b03905-5569-4efc-a85e-dfbb2716c5f5.webm)

### 4
[Tooltip appearing in a wrong place.webm](https://user-images.githubusercontent.com/35750792/199934861-4e096a39-fe2d-4a3a-b83a-75060a77e532.webm)

Fixes #17703 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by vimalMK** [comment]
@williamdes  worked from the QA_5_2 branch. 

About the actual issue where using a hard coded date format was a confusion. I worked around to avoid using the hard coded date format at all. So this PR will not have such change.
image

But it seems the date format for the date picker is hard coded any ways mentions below (or maybe am missing something to understand). Just letting you know for future reference. :)
https://github.com/phpmyadmin/phpmyadmin/blob/4f9999d706234356cd38dd14ade684817bdabed2/js/src/functions.js#L142

**Comment by williamdes** [comment]
> @williamdes worked from the QA_5_2 branch.
> 
> About the actual issue where using a hard coded date format was a confusion. I worked around to avoid using the hard coded date format at all. So this PR will not have such change. image
> 
> But it seems the date format for the date picker is hard coded any ways mentions below (or maybe am missing something to understand). Just letting you know for future reference. :)
> 
> https://github.com/phpmyadmin/phpmyadmin/blob/4f9999d706234356cd38dd14ade684817bdabed2/js/src/functions.js#L142

Do you have commits to push?
If it's hard coded then you can leave it as it is
I just realized it's maybe the MySQL format of dates so it can not be changed

**Comment by vimalMK** [comment]
> > @williamdes worked from the QA_5_2 branch.
> > About the actual issue where using a hard coded date format was a confusion. I worked around to avoid using the hard coded date format at all. So this PR will not have such change. image
> > But it seems the date format for the date picker is hard coded any ways mentions below (or maybe am missing something to understand). Just letting you know for future reference. :)
> > https://github.com/phpmyadmin/phpmyadmin/blob/4f9999d706234356cd38dd14ade684817bdabed2/js/src/functions.js#L142
> 
> Do you have commits to push? If it's hard coded then you can leave it as it is I just realized it's maybe the MySQL format of dates so it can not be changed

I do not any commits. All done!

File: js/src/functions.js [hunk 1]
```diff
@@ -164,8 +164,8 @@ Functions.addDatepicker = function ($thisElement, type, options) {
                 var tooltip = $thisElement.uiTooltip('instance');
                 if (typeof tooltip !== 'undefined') {
                     tooltip.disable();
-                    var $note = $('<p class="note"></div>');
-                    $note.text(tooltip.option('content'));
+                    var $note = $('<p class="note" style="font-size: 11px;"></div>');
+                    $note.text(Messages.strNote + ': ' + tooltip.option('content'));
```
Comment (williamdes) [inline js/src/functions.js:168]:
```suggestion
                    $note.text(Messages.strNote + tooltip.option('content'));
```
Note: `': '` should go to strNote because some languages space it differently.
I am copying this change into 5.3 because it's an enhancement and it requires a translation to be done

**Review by williamdes — APPROVED** [review]
Thank you for your contribution !
