### PR TITLE
Fixes #16892: current_timestamp() stringified on INSERT for date field

### LINKED ISSUE #16892: current_timestamp() stringified on INSERT
### Describe the bug

When using "Insert" page on a table, which has columns with default value of `current_timestamp()` this function is treated as a string value both in "Preview SQL" and when actually inserting rows.

### To Reproduce

1. Create a table with a date/datetime column with default value `current_timestamp()`
2. Try to insert a row into it using myAdmin'a special page
3. Check "Preview SQL" to see value of `'current_timestamp()'` instead of `current_timestamp()`
4. Try running it to get error, that data got truncated (and get 0 date).

### Expected behavior

Function is used as is, not as a string value

### Screenshots

N/A

### Server configuration

- Operating system: Windows 10
- Web server: Apache 2.4.46-win64-VS16
- Database version: mariaDB 10.5.9
- PHP version: 8.0.3
- phpMyAdmin version: 5.1

### Client configuration

- Browser: MS Edge
- Operating system: Windows 10

### Additional context

N/A

### PR DESCRIPTION
**Pull request by shucon**
Signed-off-by: Saksham Gupta <shucon01@gmail.com>

### Description

Please describe your pull request.

Fixes #16892 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
Could you add a PHPUnit test that covers this case?

File: libraries/classes/InsertEdit.php [hunk 1]
```diff
@@ -1725,9 +1725,14 @@ private function getValueColumnForOtherDatatypes(
                 $html_output .= '<input type="hidden" name="fields_type'
                     . $column_name_appendix . '" value="timestamp">';
             }
-            if (substr($column['pma_type'], 0, 8) === 'datetime') {
-                $html_output .= '<input type="hidden" name="fields_type'
-                    . $column_name_appendix . '" value="datetime">';
+            if (substr($column['pma_type'], 0, 4) === 'date') {
+                if (substr($column['pma_type'], 0, 8) === 'datetime') {
```
Comment (williamdes) [inline libraries/classes/InsertEdit.php:1729]: This if else is useless
You can use only one case and have a variable for the changing value

$type = condition ? date : datetime

**Review by williamdes — APPROVED** [review]

**Review by MauricioFauth — APPROVED** [review]
