### PR TITLE
Fix Row coloring issue@Indexes 

### LINKED ISSUE #13090: Row coloring issue @ Indexes
pma

### PR DESCRIPTION
**Pull request by shucon**
Signed-off-by: Saksham Gupta [shucon01@gmail.com](shucon01@gmail.com)
Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [ ] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any new functionality is covered by tests
Fixes: https://github.com/phpmyadmin/phpmyadmin/issues/13090
Accidentally deleted PR : https://github.com/phpmyadmin/phpmyadmin/pull/13871

### CODE REVIEW

File: libraries/classes/Index.php [hunk 1]
```diff
@@ -796,7 +798,12 @@ static public function getHtmlForIndexes($table, $schema, $print_mode = false)
 
             foreach ($index->getColumns() as $column) {
                 if ($column->getSeqInIndex() > 1) {
-                    $r .= '<tr class="noclick" >';
+                    if($iter%2 == 0){
+                        $r .= '<tr class="noclick" id="odd_row" >';
+                    }
+                    else{
+                        $r .= '<tr class="noclick" id="even_row" >';
```
Comment (mauriciofauth) [inline libraries/classes/Index.php]: I don't think this is the proper solution to this issue, as there is the CSS's [`:nth-child()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) pseudo-class that serves that purpose.
I think a more appropriate solution would be to wrap the entire row and apply the pseudo-class to the entire row instead of just applying to the `<tr>` tag.
Perhaps this happens with other tables that also make use of rowspan. It would be good to check this out.

**Review by MauricioFauth — CHANGES_REQUESTED** [review]

File: libraries/classes/Index.php (hunk 1 above)
Comment (shucon) [reply libraries/classes/Index.php]: @mauriciofauth the CSS's :nth-child() pseudo-class is creating the problems , that's why I created another class to override it . I'll see what else could be done.

**Comment by shucon** [comment]
@mauriciofauth please review the changes.

File: libraries/classes/Index.php [hunk 2]
```diff
@@ -796,7 +798,12 @@ static public function getHtmlForIndexes($table, $schema, $print_mode = false)
 
             foreach ($index->getColumns() as $column) {
                 if ($column->getSeqInIndex() > 1) {
-                    $r .= '<tr class="noclick" >';
+                    if($iter%2 == 0){
```
Comment (mauriciofauth) [inline libraries/classes/Index.php]: I think that adding an iterator isn't the best option, besides not solving the problem completely, since `:nth-child()` pseudo-class already does this function.

A possible solution to this problem would be to add a `div`, or another tag, that wraps each index row and apply the pseudo-class to that `div` instead of applying it to the `tr`.

**Review by MauricioFauth — CHANGES_REQUESTED** [review]

**Comment by shucon** [comment]
@mauriciofauth I've done the required changes.

File: themes/pmahomme/css/common.css.php [hunk 3]
```diff
@@ -554,13 +554,15 @@
...
+table tbody:first-of-type tr:nth-child(odd) th,
+#table_index tbody:nth-child(odd) tr {
     background: #fff;
 }
 
 /* even items 2,4,6,8,... */
 table tbody:first-of-type tr:nth-child(even),
-table tbody:first-of-type tr:nth-child(even) th {
+table tbody:first-of-type tr:nth-child(even) th,
+#table_index tbody:nth-child(even) tr {
```
Comment (mauriciofauth) [inline themes/pmahomme/css/common.css.php]: This solution is much closer to the expected result, but it still has some problems.
See:
screenshot from 2018-01-25 19-50-31

The first problem is that the Keyname column is not being colored. But this can be solved by adding the `th` selector to the rule set. For example:
```css
#table_index tbody:nth-child(even) tr,
#table_index tbody:nth-child(even) th
```

Another problem is that the colors of the rows are inverted, because the `:nth-child()` pseudo-class is counting the `<thead>` as the first element. This can be solved by replacing `:nth-child()` with the [`:nth-of-type()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-of-type) pseudo-class.

**Review by MauricioFauth — CHANGES_REQUESTED** [review]

**Review by MauricioFauth — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution and patience with my feedback!
