### PR TITLE
Fix #19254 - Trim spaces around index name

### LINKED ISSUE #19254: Cannot add index on a column name with a trailing space
### Describe the bug

Index cannot be added on a column that has a trailing space.

`Key column 'id ' doesn't exist in table`

The generated query is:
```SQL
ALTER TABLE `test` ADD `id` TINYINT UNSIGNED NOT NULL, ADD INDEX (`id `);
```

### To Reproduce

1. Create a column `id `, with index on it.
2. See error

### Expected behavior

Trailing space should be removed from index.

### Screenshots

https://github.com/user-attachments/assets/379c193b-d938-4a1f-8b99-5110d3e6219c

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### Additional context

Related to #18431

### PR DESCRIPTION
**Pull request by liviuconcioiu**
### Description

Trim spaces around index name.

Fixes #19254

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

File: js/src/indexes.js [hunk 1]
```diff
@@ -232,7 +232,7 @@ Indexes.addColumnToIndex = function (sourceArray, arrayIndex, indexChoice, colIn
         $.each(columns, function () {
             columnNames.push($('input[name="field_name[' +  this.col_index + ']"]').val());
         });
-        displayName = '[' + columnNames.join(', ') + ']';
+        displayName = '[' + columnNames.join(', ').trim() + ']';
```
Comment (MauricioFauth) [inline js/src/indexes.js:235]:
```suggestion
        displayName = '[' + columnNames.join(', ').trimRight() + ']';
```

`trimRight` instead of `trimEnd` as it's more compatible.
https://caniuse.com/mdn-javascript_builtins_string_trimend

File: libraries/classes/CreateAddField.php [hunk 2]
```diff
@@ -170,7 +170,7 @@ private function buildIndexStatement(
 
         $indexFields = [];
         foreach ($index['columns'] as $key => $column) {
-            $indexFields[$key] = Util::backquote($_POST['field_name'][$column['col_index']]);
+            $indexFields[$key] = Util::backquote(trim($_POST['field_name'][$column['col_index']]));
```
Comment (MauricioFauth) [inline libraries/classes/CreateAddField.php:173]:
```suggestion
            $indexFields[$key] = Util::backquote(rtrim($_POST['field_name'][$column['col_index']]));
```

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
Only the end of the name should be trimmed, as ` id` is a valid name.

**Review by MauricioFauth — APPROVED** [review]
