### PR TITLE
Replace slash with PHP constant

### LINKED ISSUE #16430: Windows error message uses trailing / instead of \
On Windows, I feel the warning/error message:

>The $cfg['TempDir'] (C:\inetpub\phpMyAdmin\tmp/) is not accessible

should use a backslash `\` instead of a frontslash `/`as the final character.

This is quite minor but looks wrong. It's possible there are other places in the code that act in a similar way.

### PR DESCRIPTION
**Pull request by LeeWeiZhang**
Signed-off-by: Lee Wei Zhang <leeweizhang24@gmail.com>

### Description

This Pr aim to fix issue:
https://github.com/phpmyadmin/phpmyadmin/issues/16430

Fixes #16430

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: libraries/vendor_config.php [hunk 1]
```diff
@@ -73,9 +73,9 @@
...
  * Path to files with compiled locales (*.mo)
  */
-define('LOCALE_PATH', ROOT_PATH . 'locale/');
+define('LOCALE_PATH', ROOT_PATH . 'locale' . DIRECTORY_SEPARATOR);
 
 /**
  * Define the cache directory for routing cache an other cache files
  */
-define('CACHE_DIR', ROOT_PATH . 'libraries/cache/');
+define('CACHE_DIR', ROOT_PATH . 'libraries/cache' . DIRECTORY_SEPARATOR);
```
Comment (mauriciofauth) [inline libraries/vendor_config.php:81]: There are two slashes in this line.

**Review by MauricioFauth — CHANGES_REQUESTED** [review]

**Review by williamdes — APPROVED** [review]
