### PR TITLE
Fix #17178 - adds the links from "Server variables and settings" to the url system

### LINKED ISSUE #17178: Links from Server variables and settings aren't added to URL system
### Describe the bug

Links from Server variables and settings aren't added to URL system.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/index.php?route=/server/variables](https://demo.phpmyadmin.net/master-config/index.php?route=/server/variables)
2. Hover over variable name to see the link or click on it

### Expected behavior

All external links should be added to the URL system.

### Screenshots

links

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser: Firefox
- Operating system: Windows

### PR DESCRIPTION
**Pull request by liviuconcioiu**
Signed-off-by: Liviu-Mihail Concioiu <liviu.concioiu@gmail.com>

### Description

This PR adds the links from "Server variables and settings" to the url system.

Fixes #17178

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: libraries/classes/Html/MySQLDocumentation.php [hunk 1]
```diff
@@ -42,7 +42,7 @@ public static function show(
             $url = Util::getMySQLDocuURL($link, $anchor);
         }
 
-        $openLink = '<a href="' . htmlspecialchars($url) . '" target="mysql_doc">';
+        $openLink = '<a href="index.php?route=/url&url=' . htmlspecialchars($url) . '" target="mysql_doc">';
```
Comment (MauricioFauth) [inline libraries/classes/Html/MySQLDocumentation.php:45]: This is not the proper fix. The `/url` route doesn't exist on `QA_5_2`.
I think it's better to fix this in `PhpMyAdmin\Html\Generator::linkToVarDocumentation` with something like:
```php
$link = $link !== null ? Core::linkURL($link) : $link;
```

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
Hi, @liviuconcioiu. Thanks for your contribution.

**Review by williamdes — APPROVED** [review]

**Review by MauricioFauth — APPROVED** [review]

**Comment by MauricioFauth** [comment]
Merged, thanks for your contribution!
