### PR TITLE
Fix #19367 - renaming timestamp column name

### LINKED ISSUE #19367: Renaming a timestamp(6) column doesn't work: it quotes the value
### Describe the bug

Renaming a `timestamp(6)` column with `DEFAULT current_timestamp(6)` doesn't work, because it adds single quotes around `current_timestamp(6)`.

### To Reproduce

1. Create table:

```SQL
CREATE TABLE `test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `created_at` timestamp(6) NOT NULL DEFAULT current_timestamp(6),
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;
```
2. Rename `created_at`
3. See error

### Expected behavior

Renaming should work.

### Screenshots

https://github.com/user-attachments/assets/10093d81-d29e-47f6-9fb4-1158e449cde6

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### PR DESCRIPTION
**Pull request by yashpunwani**
This PR will fix the bug that is raising a query error when we try to update the name of a timestamp column. This is because it was adding quotes to the `current_timestamp` sql function which was getting added while generating alter sql query.

For more refer this issue: [#19367](https://github.com/phpmyadmin/phpmyadmin/issues/19367)

Fixes #19367

### CODE REVIEW

File: src/Table/Table.php [hunk 1]
```diff
@@ -1776,4 +1781,18 @@ public function getColumnsWithIndex(int $types): array
...
+     *
+     * @param string $query SQL query to check
+     *
+     * @return bool true if query has DEFAULT CURRENT_TIMESTAMP function
+     */
+    private static function hasCurrentTimestampFunction(string $query): bool
+    {
+        preg_match("/current_timestamp\((\d+)\)/i", $query, $matches);
+
+        return !empty($matches[0]);
```
Comment (kamil-tekiela) [inline src/Table/Table.php]: We don't use empty() in this codebase anymore. Plus, all of it seems unnecessary. Could you not simply use str_contains?

File: src/Table/Table.php [hunk 2]
```diff
@@ -1776,4 +1781,18 @@ public function getColumnsWithIndex(int $types): array
 
         return $columnsWithIndex;
     }
+
+    /**
```
Comment (kamil-tekiela) [inline src/Table/Table.php]: The whole docbloc is redundant and can be removed

File: src/Table/Table.php (hunk 1 above)
Comment (yashpunwani) [reply src/Table/Table.php]: Yes, you are right. I was using logic from previous code.

**Comment by yashpunwani** [comment]
Hey @kamil-tekiela can you please approve the workflow?

**Comment by kamil-tekiela** [comment]
No, sorry. I don't have the permissions in this repo.

File: src/Table/Table.php [hunk 3]
```diff
@@ -518,7 +518,12 @@ public static function generateFieldSpec(
                         } elseif ($type === 'BINARY' || $type === 'VARBINARY') {
                             $query .= ' DEFAULT 0x' . $defaultValue;
                         } else {
-                            $query .= ' DEFAULT ' . $dbi->quoteString($defaultValue);
+                            // if default value is a current timestamp sql function then it does not needs to be quoted
+                            if(str_contains($defaultValue, 'current_timestamp') || str_contains($defaultValue, 'CURRENT_TIMESTAMP')) {
```
Comment (williamdes) [inline src/Table/Table.php]: What about the string litteral "the CURRENT_TIMESTAMP" as a default value of the column?

Would it break using this new code?

Comment (kamil-tekiela) [reply src/Table/Table.php]: See https://github.com/phpmyadmin/phpmyadmin/issues/19623#issuecomment-2724922090

Comment (yashpunwani) [reply src/Table/Table.php]: @williamdes It is working with the literal "CURRENT_TIMESTAMP"

**Comment by yashpunwani** [comment]
@williamdes can you please approve the workflow?

**Comment by yashpunwani** [comment]
Hi @williamdes , I have made the changes that were raising linting errors, can you please approve the workflows ?

**Comment by yashpunwani** [comment]
@williamdes can you please reapprove workflows, i have fixed the lint errors

**Comment by yashpunwani** [comment]
Sorry for the force push, i was failing DCO checks. Hope it would not raise any problems. @williamdes please reapprove the workflows. Sorry for disturbing you again.

**Comment by williamdes** [comment]
> Sorry for the force push, i was failing DCO checks. Hope it would not raise any problems. @williamdes please reapprove the workflows. Sorry for disturbing you again.

Can you go to https://github.com/yashpunwani/phpmyadmin/tree/master and click "sync fork"
Then you can fetch and git rebase
or whatever is best but please squash your commits

File: src/Table/Table.php [hunk 4]
```diff
@@ -518,7 +518,14 @@ public static function generateFieldSpec(
                         } elseif ($type === 'BINARY' || $type === 'VARBINARY') {
                             $query .= ' DEFAULT 0x' . $defaultValue;
                         } else {
-                            $query .= ' DEFAULT ' . $dbi->quoteString($defaultValue);
+                            if (
```
Comment (kamil-tekiela) [inline src/Table/Table.php]: Please reduce the nesting level. This `if` is still part of the outer `if`. Combine `else` and `if` into `elseif`.

**Review by kamil-tekiela — APPROVED** [review]

**Comment by liviuconcioiu** [comment]
I think it should target `QA_5_2` branch, since the bug is also present there.

**Comment by yashpunwani** [comment]
> I think it should target `QA_5_2` branch, since the bug is also present there.

@liviuconcioiu I have made a separate branch to fix this issue for `QA_5_2`, named [fix/qa-5-2-renaming-timestamp-col](https://github.com/yashpunwani/phpmyadmin/tree/fix/qa-5-2-renaming-timestamp-col) in my forked repo. Please take a look, it can be directly merged to the `QA_5_2`

**Comment by williamdes** [comment]
> > I think it should target `QA_5_2` branch, since the bug is also present there.
> 
> @liviuconcioiu I have made a separate branch to fix this issue for `QA_5_2`, named [fix/qa-5-2-renaming-timestamp-col](https://github.com/yashpunwani/phpmyadmin/tree/fix/qa-5-2-renaming-timestamp-col) in my forked repo. Please take a look, it can be directly merged to the `QA_5_2`

I can do the magic at merge time, transforming this PR into the one needed for 5.2

**Comment by williamdes** [comment]
@yashpunwani can you tick the box on the pull request to allow maintainers to make changes to it please ?
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by yashpunwani** [comment]
@williamdes done

**Review by williamdes — APPROVED** [review]
The diff looks okay, let's see what the tests think about it

File: libraries/classes/Utils/HttpRequest.php [hunk 5]
```diff
@@ -14,6 +14,7 @@
 use function file_get_contents;
 use function function_exists;
 use function getenv;
+use function http_get_last_response_headers;
```
Comment (williamdes) [inline libraries/classes/Utils/HttpRequest.php:17]:
```suggestion
```

**Comment by williamdes** [comment]
I merged this as 631cac096ff774933670946499bdb6757016f1d2 with some changes and improvements
