### PR TITLE
#15127 - fixed the white square in floating menubar

### LINKED ISSUE #15127: [UI] Horrible white square
### Describe the bug

image

This occurs for some reason a some time but is very annoying ...
Use designer and navigate between pages

### PR DESCRIPTION
**Pull request by rahgurung**
Signed-off-by: Rahul Gurung <gurungrahul2@gmail.com>

Closes #15127 

This PR removes the unwanted margin-left from the floating menubar which was creating a white square.

### CODE REVIEW

File: js/navigation.js [hunk 1]
```diff
@@ -1128,7 +1128,7 @@ var ResizeHandler = function () {
         var windowWidth = $(window).width();
         $('#pma_navigation').width(pos);
         $('body').css('margin-' + this.left, pos + 'px');
-        $('#floating_menubar, #pma_console')
```
Comment (gurrrung) [inline js/navigation.js]: @williamdes The reason I removed the margin-left is that I don't find any reason to have it in the code, I even tried resizing the sliders so that things not break, everything worked fine.

Comment (williamdes) [reply js/navigation.js]: Thanks @gurrrung!

**Review by williamdes — APPROVED** [review]
Thanks @gurrrung for the contribution, merged !

**Comment by williamdes** [comment]
Screenshot_20190821_084457_com android chrome
