### PR TITLE
Fix #16585 - BLOB JPG preview thumbnail

### LINKED ISSUE #16585: BLOB to JPG transformation broken
Configuring a BLOB column to have browser transformation set to Inline JPG and clicking on the (also broken) thumbnail will result in the following warning:

```
Fatal error: Uncaught TypeError: Argument 1 passed to PhpMyAdmin\Core::downloadHeader() must be of the type string, null given, called in /var/www/html/transformation_wrapper.php on line 131 and defined in /var/www/html/libraries/classes/Core.php:631 Stack trace:
#0 /var/www/html/transformation_wrapper.php(131): PhpMyAdmin\Core::downloadHeader(NULL, 'Image/JPEG')
#1 {main} thrown in /var/www/html/libraries/classes/Core.php on line 631
```
Open new phpMyAdmin window
```
Notice in ./transformation_wrapper.php#131
 Undefined variable: cn
```

transformation_wrapper.php is expecting "cn" to be passed on the query string, which is not the case at the moment. Manually appending &cn= fixes the issue.

### PR DESCRIPTION
**Pull request by joltcoke**
Thumbnails are broken because imagecreatetruecolor() is expecting int but the params are either strings (from query string) or float. This PR fixes both issues.

Addresses the broken thumbnail mentioned in #16585 

Fixes: #16585

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @joltcoke 
Could you rebase onto QA_5_1 ?
And change the PR target using the edit button ?

**Comment by joltcoke** [comment]
Hi @williamdes 

i've rebased to QA_5_1 and converted the casts into intval() conversions to be consistent with the other code in the same file. This also fixed the linting issues.

**Comment by williamdes** [comment]
I tested your fix and it works great !
But I added one more commit because the `cn` parameter seems not to be sent and it did throw and error.

File: libraries/classes/Controllers/TransformationWrapperController.php [hunk 1]
```diff
@@ -194,11 +195,11 @@ public function index(): void
             $ratioHeight = $srcHeight / $_REQUEST['newHeight'];
 
             if ($ratioWidth < $ratioHeight) {
-                $destWidth = $srcWidth / $ratioHeight;
-                $destHeight = $_REQUEST['newHeight'];
+                $destWidth = intval(round($srcWidth / $ratioHeight));
```
Comment (williamdes) [inline libraries/classes/Controllers/TransformationWrapperController.php:198]: Let me know if https://stackoverflow.com/a/58712745/5155484 could be an issue here also

**Review by MauricioFauth — APPROVED** [review]
