### PR TITLE
Fix #16146 - sorting changes number_of_rows

### LINKED ISSUE #16146: When browsing, changing the sort order loses the number of rows setting
When browsing, changing the sort order looses the number of rows setting 
### To Reproduce
select a list of records
change the number of rows to say 500
change the sort order of the list

### Expected behavior
Don't  change the number of rows setting when the sort order is changed

image

- Browser: Chrome
- Operating system: W10 64

### PR DESCRIPTION
**Pull request by rajat315315**
### Description

Please describe your pull request.
This pull request fixes the bug that causes number of rows to change when we change the sorting order while viewing a table.

Fixes #16146 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @rajat315315 
Thank you for your contribution, I would like that you create a variable like `$sessionMaxRows = $_GET['session_max_rows'] ?? $_POST['session_max_rows'];`
Could you do this change ?

**Comment by rajat315315** [comment]
Done!!

File: libraries/classes/Display/Results.php [hunk 1]
```diff
@@ -3966,14 +3966,15 @@ public function setConfigParamsForDisplayTable()
...
+        $sessionMaxRows = $_GET['session_max_rows'] ?? $_POST['session_max_rows'];
         // as this is a form value, the type is always string so we cannot
         // use Core::isValid($_POST['session_max_rows'], 'integer')
-        if (Core::isValid($_POST['session_max_rows'], 'numeric')) {
-            $query['max_rows'] = (int) $_POST['session_max_rows'];
-            unset($_POST['session_max_rows']);
-        } elseif ($_POST['session_max_rows'] == self::ALL_ROWS) {
+        if (Core::isValid($sessionMaxRows, 'numeric')) {
+            $query['max_rows'] = (int) $sessionMaxRows;
+            unset($_REQUEST['session_max_rows']);
```
Comment (williamdes) [inline libraries/classes/Display/Results.php:3974]: Could you unset get and post?
```suggestion
            unset($_GET['session_max_rows'], $_POST['... );
```

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
Thank you @rajat315315 !
Merged, the fix works fine :)
