### PR TITLE
Don't guess system schema collation

### LINKED ISSUE #18950: Twig\Error\RuntimeError: Key "description" does not exist as the array is empty.
### Describe the bug

```
Internal error in .\resources\templates\server\databases\index.twig#187
Twig\Error\RuntimeError: Key "description" does not exist as the array is empty.
```

It happens because of `$cfg['Servers'][$i]['DisableIS'] = true;`

### To Reproduce

1. Set `$cfg['environment'] = 'development';`
2. Set `$cfg['Servers'][$i]['DisableIS'] = true;`
3. Go to `Databases` page

### Expected behavior

No error should be given and databases should be visible.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/a98d0884-09fe-4d83-9479-1523dc027aab

### Server configuration

- Database version: MariaDB/11.2.2
- PHP version: 8.3.2
- phpMyAdmin version: 6.0.0-dev

### PR DESCRIPTION
**Pull request by kamil-tekiela**
Fixes #18950

### CODE REVIEW

File: test/classes/DatabaseInterfaceTest.php [hunk 1]
```diff
@@ -277,10 +277,15 @@ public function testPostConnectShouldSetVersion(
...
+        $GLOBALS['cfg']['Server']['DisableIS'] = true;
         $GLOBALS['server'] = 1;
+
+        $this->dummyDbi->addSelectDb('information_schema');
+        $GLOBALS['db'] = 'information_schema';
+
         // test case for system schema
         $this->assertEquals(
-            'utf8_general_ci',
+            'bar',
```
Comment (MauricioFauth) [inline test/classes/DatabaseInterfaceTest.php:288]: You can add a result for this test, so you can control the value.
Example:

```php
$this->dummyDbi->removeDefaultResults();
$this->dummyDbi->addResult('SELECT @@collation_database', [['utf8mb4_general_ci']], ['@@collation_database']);

$this->assertEquals('utf8mb4_general_ci', $this->dbi->getDbCollation('information_schema'));
```

**Review by MauricioFauth — CHANGES_REQUESTED** [review]

**Review by MauricioFauth — APPROVED** [review]
