### PR TITLE
#13912 and #15123 - check phpMyAdmin tables are accessible

### LINKED ISSUE #13912: SELECT MAX(version) - pma tracking - PMA does not detect that table is not accessible
### Steps to reproduce
1. add aws db config code
2. restart xampp

### Expected behaviour
Remote db should be open on selecting it and i should be able to view a table

### Actual behaviour
showing SQL query error

phpmyadmin

### Server configuration
**Operating system**: Amazon AWS Linux

**Web server:** 

**Database:**

**PHP version:** 7.1.11

**phpMyAdmin version:** 4.7.7

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10

### LINKED ISSUE #15123: phpMyAdmin unusable with user having WITH GRANT OPTION privileges and an existing Configuration Storage database
### Describe the bug

All attempts to access tables, databases, anything is blocked.

### To Reproduce

- Create a user, GRANT him `GRANT` and select the option to create a database and give all privileges to the user.
- Login to the user, try to browse his database

NOTE: the user can see other databases witch is for me quite strange.

### Screenshots

User

### Server configuration

- phpMyAdmin version: 4.8.6, 5.0.0-dev

### PR DESCRIPTION
**Pull request by williamdes**
### Description

The tables can be listed but not accessible.
Corrupt data (#13912) or permission issue (#15123)
Fixes #13912 and fixes #15123

### CODE REVIEW

File: libraries/classes/Relation.php [hunk 1]
```diff
@@ -574,74 +574,112 @@ public function checkRelationsParam()
...
         if (isset($cfgRelation['relation'])) {
-            $cfgRelation['relwork']     = true;
+            if ($this->canAccessStorageTable($cfgRelation['relation'])) {
+                $cfgRelation['relwork']     = true;
+            }
         }
 
         if (isset($cfgRelation['relation']) && isset($cfgRelation['table_info'])) {
-            $cfgRelation['displaywork'] = true;
+            if ($this->canAccessStorageTable($cfgRelation['table_info'])) {
```
Comment (williamdes) [inline libraries/classes/Relation.php]: maybe missing an if `$cfgRelation['relwork']`

**Comment by williamdes** [comment]
This PR makes phpMyAdmin usable for browsing data in totally broken servers

Can you please have a look @mauriciofauth and @ibennetch ?

**Review by MauricioFauth — APPROVED** [review]
