### PR TITLE
globalised DEFAULT_GENERATED matching

### LINKED ISSUE #16076: Cannot edit or export TIMESTAMP column with default CURRENT_TIMESTAMP in MySQL >= 8.0.13
@williamdes Can we reopen this? The problem still exists for me on two different servers.
Direct dump with `mysqldump` works as expected, just dumping over phpmyadmin does not work

### Server 1 configuration
Operating system: Ubuntu
Web server: Nginx/1.17.9
Database version: MySQL 8.0.19
PHP version: 7.4.3
phpMyAdmin version: 5.0.2

### Server 2 configuration
Operating system: Debian
Web server: Apache/2.4.38
Database version: MySQL 8.0.19
PHP version: 7.3.14
phpMyAdmin version: 4.9.4

### Table Definition
| # | Name      | Type        | Collation       | Attribute                   | Null | Default           | Extra                                         |
|---|-----------|-------------|-----------------|-----------------------------|------|-------------------|-----------------------------------------------|
| 1 | ID        | int         |                 | UNSIGNED                    | NO   |                   | AUTO_INCREMEMT                                |
| 2 | xyv       | int         |                 | UNSIGNED                    | NO   |                   |                                               |
| 3 | xyz       | varchar(50) | utf8_general_ci |                             | NO   |                   |                                               |
| 4 | timestamp | timestamp   |                 | on update CURRENT_TIMESTAMP | NO   | CURRENT_TIMESTAMP | DEFAULT_GENERATED ON UPDATE CURRENT_TIMESTAMP |

_Originally posted by @toitzi in https://github.com/phpmyadmin/phpmyadmin/issues/15315#issuecomment-613264821_

Ref: #15315

### PR DESCRIPTION
**Pull request by ankush-0x90**
Signed-off-by: Ankush Patil <aspraz2658@gmail.com>

### Description
We were checking for only DEFAULT_GENERATED as extra value
Failing on DEFAULT_GENERATED ON UPDATE CURRENT_TIMESTAMP

Fixes #16076 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: libraries/classes/InsertEdit.php [hunk 1]
```diff
@@ -1625,7 +1625,7 @@ private function getValueColumnForOtherDatatypes(
                 $readOnly
             );
 
-            if (preg_match('/(VIRTUAL|PERSISTENT|GENERATED)/', $column['Extra']) && $column['Extra'] !== 'DEFAULT_GENERATED') {
+            if ( preg_match('/(VIRTUAL|PERSISTENT|GENERATED)/', $column['Extra']) && !preg_match('/(DEFAULT_GENERATED)/', $column['Extra']) ) {
```
Comment (williamdes) [inline libraries/classes/InsertEdit.php:1628]: Could you explain the change and maybe use strpos here?

**Review by williamdes — APPROVED** [review]
The code looks good

File: libraries/classes/InsertEdit.php (hunk 1 above)
Comment (asprazz) [reply libraries/classes/InsertEdit.php:1628]: We could also use strpos their just ..like insertEdit.php

It's making sure that no DEFAULT_GENERATED should be their in extra .. using regex

Is strpos better way of handling not operations?

Comment (williamdes) [reply libraries/classes/InsertEdit.php:1628]: Okay, I was asking myself : does the extra contain something else, if yes, what?

I would prefer a strpos because this is no very much a regex but a text search, always use the lightest solution :)

Could you rebase on QA_5_0?

Comment (asprazz) [reply libraries/classes/InsertEdit.php:1628]: Yes I can rebase it on QA_5_0 should i change to strpos

Comment (williamdes) [reply libraries/classes/InsertEdit.php:1628]: Yes, please :)

**Comment by asprazz** [comment]
Hi @williamdes, may be I am little late. But done using strpos and rebasing on QA_5_0. :)

File: libraries/classes/InsertEdit.php [hunk 2]
```diff
@@ -1670,7 +1670,7 @@ private function getValueColumnForOtherDatatypes(
                 $readOnly
             );
 
-            if (preg_match('/(VIRTUAL|PERSISTENT|GENERATED)/', $column['Extra']) && $column['Extra'] !== 'DEFAULT_GENERATED') {
```
Comment (williamdes) [inline libraries/classes/InsertEdit.php:1673]: before: can match generated types and is not default generated
after: can match generated types and does not contain default generated

File: libraries/classes/Table.php [hunk 3]
```diff
@@ -1810,7 +1810,7 @@ public function getNonGeneratedColumns($backquoted = true)
                 if ((
                     strpos($column['Extra'], 'GENERATED') === false
                     && strpos($column['Extra'], 'VIRTUAL') === false
-                    ) || $column['Extra'] === 'DEFAULT_GENERATED') {
+                    ) || strpos($column['Extra'], 'DEFAULT_GENERATED') !== false) {
```
Comment (williamdes) [inline libraries/classes/Table.php:1813]: before: (does not contain GENERATED and does not contain VIRTUAL) or is default generated
after: (does not contain GENERATED and does not contain VIRTUAL) or does not contain default generated

**Review by williamdes — APPROVED** [review]
The code looks good after analysis, I will test it.
Congratulations for your GPG signature, it looks nice!

**Comment by williamdes** [comment]
Thank you !
This is a good and working fix :muscle:
