### PR TITLE
Fix #19242 - Removing the popup with auto-saved query message

### LINKED ISSUE #19242: Cannot disable "Auto saved query" which is popping everytime
### Describe the bug

PhpMyAdmin (last version) keeps saying "You have a previously saved query. Click Get auto-saved query to load the query.".

Also, when using PhpMyAdmin in multiple tabs, making a query in one of them resets all the other tabs queries...

### To Reproduce

Nothing particular, it just keeps saying this message.

### Expected behavior

Please, just make an option to disable this pain. The feature is interesting but it is clearly buggy.

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: Debian
- Web server: Nginx
- Database version: Any
- PHP version: Any
- phpMyAdmin version: Last

### Client configuration

- Browser: Any
- Operating system: Any

### PR DESCRIPTION
**Pull request by jpoliveira08**
### Description

This pull request aims to remove the pop-up displaying the message 'You have a previously saved query. Click Get auto-saved query to load the query.' This pop-up is shown multiple times and, as reported in some issues, negatively impacts the user experience.

The code was based on pull request #16456, where it was mentioned that this change is acceptable but may hide the feature from the user. Therefore, this implementation keeps the 'Get auto-saved query' button, but it is only enabled if there is a query available to be retrieved. Otherwise, the button is displayed but remains disabled.

If this change is still not acceptable, we could add a tooltip to the button, explaining that it is enabled only when there are saved queries, or we could consider other solutions.

Fixes #19242

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

File: resources/js/src/sql.ts [hunk 1]
```diff
@@ -799,6 +797,7 @@ AJAX.registerOnload('sql.js', function () {
 
         // remove any div containing a previous error message
         $('.alert-danger').remove();
+        checkSavedQuery();
```
Comment (williamdes) [inline resources/js/src/sql.ts:800]: Hi @jpoliveira08 
Sorry for the review delay
Do you know why this line had to be added ?
It does not seem clear to me

Except that, everything is okay

Comment (jpoliveira08) [reply resources/js/src/sql.ts]: Hi @williamdes 

Yes, I checked and noticed it was in the wrong place. I added it to ensure the button is enabled as soon as the user types something in the query. Previously, the button to recover the query could be clicked as long as there was at least one character typed.

Comment (williamdes) [reply resources/js/src/sql.ts]: Thank you !

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
Thank you for your contribution !
