### PR TITLE
Fixed empty text not appearing after deleting all Routines

### LINKED ISSUE #16498: Inconsistent empty list behaviour after dropping multiple routines/events/triggers
### Describe the bug

When dropping all remaining routines/events/triggers, the resulting empty list is not replaced accordingly.

### To Reproduce

1. Select a database, create a few stored procedures (or events, or triggers, respectively), e.g.:
```sql
CREATE FUNCTION `test1`() RETURNS INT(1) NOT DETERMINISTIC NO SQL SQL SECURITY DEFINER RETURN 1; 
CREATE FUNCTION `test2`() RETURNS INT(1) NOT DETERMINISTIC NO SQL SQL SECURITY DEFINER RETURN 1; 
CREATE FUNCTION `test3`() RETURNS INT(1) NOT DETERMINISTIC NO SQL SQL SECURITY DEFINER RETURN 1; 
```
2. Go to the Routines page.
3. Select all the displayed routines, click "With selected: Drop", click "OK" in the pop-up confirm "Do you really want to delete the selected items?".
4. The procedures are dropped and their rows are removed from the list correctly, but the list header/footer remains displayed.
5. On the other hand, when deleting a single remaining procedure, the empty list is correctly replaced with a text "There are no routines to display."

### Expected behavior

After dropping all routines, the empty list is consistently replaced with the "There are no routines to display." text.

### Screenshots

After deleting multiple routines:
after-deleting-multiple

After deleting single remaining routine:
after-deleting-single

### Server configuration

- Operating system, Web server, Database version, PHP version: https://demo.phpmyadmin.net/
- phpMyAdmin version: 4.9.7, 5.0.4, 5.1.0

### Client configuration

- Browser: Firefox 83.0
- Operating system: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by rajat315315**
Signed-off-by: Rajat Jain <rajatjain.ix@gmail.com>

### Description

Fixed the missing message that has to appear after deleting multiple Routines.

Fixes #16498 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: js/src/rte.js [hunk 1]
```diff
@@ -504,9 +504,7 @@ RTE.COMMON = {
                             });
                         } else {
                             $currRow.hide('fast', function () {
-                                $(this).remove();
-                                // Now we have removed the row from the list, but maybe
-                                // some row classes are wrong now. So we will itirate
+                                //we will itirate
```
Comment (williamdes) [inline js/src/rte.js:507]:
```suggestion
                                //we will iterate 
```

**Comment by williamdes** [comment]
Thank you for the fix @rajat315315 !

**Comment by rajat315315** [comment]
Welcome.
Can somebody please nominate me, if I have done some meaningful contribution at the community?
[](https://stars.github.com/nominate/)
