### PR TITLE
Fix #17285 - Add DELIMITER $$ when exporting triggers

### LINKED ISSUE #17285: Exported Triggers not usable for import again
### Describe the bug

When I try to export all my triggers for any database schema, no delimiter is added to the output. Because of this it's impossible to import those triggers again.

Why do I need this? Because I needed to change the creator (user) of that triggers. The initial one was removed and no updates have been possible on that database.

### To Reproduce

1. Go to a database with many triggers
2. Click on menu item 'Trigger'
3. Select all trigger on very end of the page
4. Klick export on the very end of page

### Expected behavior

A sql file is downloaded OR the modal which opens has delimiters in generated sql code.

### Screenshots

none.

### Server configuration

phpMyAdmin: Versionsinformationen: 5.1.1
Operating system: Linux Ubuntu
Server: Localhost via UNIX socket
Server-Typ: MariaDB
Server-Verbindung: SSL wird nicht verwendet Dokumentation
Server-Version: 10.2.39-MariaDB-1:10.2.39+maria~bionic-log - mariadb.org binary distribution
Protokoll-Version: 10
Benutzer: admin@localhost
Server-Zeichensatz: UTF-8 Unicode (utf8mb4)
nginx/1.20.1
Datenbank-Client Version: libmysql - mysqlnd 7.4.26
PHP-Erweiterung: mysqli Dokumentation curl Dokumentation mbstring Dokumentation
PHP-Version: 7.4.26

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

### Additional context

none.

### PR DESCRIPTION
**Pull request by M393**
Fixes #17285
image

and fixes a bug where the `Loading...` was not visible during export because it was immediately dismissed.

### CODE REVIEW

**Comment by M393** [comment]
Do you know where triggers are exported as html? When going to (Database or Table) -> Triggers export is done with AJAX.
I don't think this change causes a problem, but can't say for sure.
https://github.com/phpmyadmin/phpmyadmin/blob/47599015fd9ee3afd35ef8fdb3d1ccb52e38fd89/libraries/classes/Database/Triggers.php#L504-L516

File: js/src/database/triggers.js [hunk 1]
```diff
@@ -98,7 +98,6 @@ const DatabaseTriggers = {
         } else {
             $.get($this.attr('href'), { 'ajax_request': true }, showExport);
         }
-        Functions.ajaxRemoveMessage($msg);
```
Comment (williamdes) [inline js/src/database/triggers.js:101]: Why this change?

**Comment by williamdes** [comment]
Maybe special schema https://github.com/phpmyadmin/phpmyadmin/blob/d21d00cd0a1f32628914612bcf5eb56e7d7e0630/tests/unit/Display/ResultsTest.php#L203

**Comment by M393** [comment]
@williamdes Where do I find this in phpMyAdmin UI?

**Comment by williamdes** [comment]
> @williamdes Where do I find this in phpMyAdmin UI?

In the `information_schema` database, in the triggers tables :)
`?route=/sql&db=information_schema&table=TRIGGERS&pos=0`

**Comment by williamdes** [comment]
Also fixes https://github.com/phpmyadmin/phpmyadmin/issues/19578 ?

**Comment by M393** [comment]
> Maybe special schema
> 
> https://github.com/phpmyadmin/phpmyadmin/blob/d21d00cd0a1f32628914612bcf5eb56e7d7e0630/tests/unit/Display/ResultsTest.php#L203

The ACTION_COLUMN is transmitted to the browser as plain text and formatted with js, doesn't go through that function.

Triggers::export() is private and only called from Triggers::main(). The only two controllers who call Triggers::main() are Database/TriggersController and Table/TriggersController, so possibly unused code.

Anyways, this is what the html looks like when you force ajax to off:
image
It's a heading and textarea with the trigger sql inside - now with DELIMITER. 👍

**Comment by M393** [comment]
> Also fixes #19578 ?

No, it doesn't.
