### PR TITLE
Fix #19744 - Check if curl is enabled

### LINKED ISSUE #19744: [Bug]: "Error" on any attempt to export a table
### Describe the bug

Environment: Firefox (latest), and Edge (latest), both running on Windows 11 (latest) ASUS Vivobook laptop.

Bug: when I highlight a database table and click on Export, the screen goes entirely blank except for the one word "Error" that now appears in the top left corner. The Firefox tab label now reads "Internal error: Error". That's it. All other operations of phpMyAdmin appear to work.

This bug may be related to my efforts to rid my system of OneDrive. However, there should surely be more from phpMyAdmin to guide me towards remedies. I am not having difficulties with other applications (Word, Excel etc)

### How to Reproduce

_No response_

### Expected behavior

_No response_

### Screenshots

_No response_

### Operating System

Windows

### Web Server

Apache 2.4.62

### Database Server

MySQL

### Database version

8.0.42

### PHP version

8.3.12

### phpMyAdmin version

5.2.2

### browser

Firefox 140.0 (aarch64)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liviuconcioiu**
### Description

Fixes #19744, #19661

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

File: libraries/classes/Plugins/Export/ExportPdf.php [hunk 1]
```diff
@@ -332,6 +333,6 @@ private function setPdf($pdf): void
 
     public static function isAvailable(): bool
     {
-        return class_exists(TCPDF::class);
+        return class_exists(TCPDF::class) && function_exists('curl');
     }
```
Comment (kamil-tekiela) [inline libraries/classes/Plugins/Export/ExportPdf.php:337]: function_exists or extension?

Comment (liviuconcioiu) [reply libraries/classes/Plugins/Export/ExportPdf.php:337]: Still not sure if this is the right way to do it. Apparently the bug started to happen when `use TCPDF;` was added in https://github.com/phpmyadmin/phpmyadmin/commit/92dc790d786cd8942e383b71637217ed6c2cef62.

tcpdf requires curl https://github.com/tecnickcom/TCPDF/blob/ca5b6de294512145db96bcbc94e61696599c391d/composer.json#L26

Comment (MauricioFauth) [reply libraries/classes/Plugins/Export/ExportPdf.php:337]: Okay, so TCPDF started requiring curl in version 6.8.0.

**Review by MauricioFauth — APPROVED** [review]
