### PR TITLE
Fix #13864 - Prevent resetting of enum fields when adding new rows to current insertion batch

### LINKED ISSUE #13864: ENUM's radiobuttons reset on "Continue insertion with" changes
### Steps to reproduce
1. Having table with ENUM datatype column, having 2 option
2. Going to table Insert section
3. Choose a value for the enum
4. Change the value of "Continue insertion with" to any other value

### Expected behaviour
ENUM datatype column setting in all added (selected) items must remain as selected on "Continue insertion with" change

### Actual behaviour
ENUM datatype column setting in all added (selected) items resets and loses the previously selected value

### Server configuration
phpMyAdmin version: 4.7.4, 4.8.3, 5.0.0-dev

### PR DESCRIPTION
**Pull request by victorphoenix3**
fixes #13864

Signed-off-by: Jayati Shrivastava <gaurijove@gmail.com>

### Description
Earlier, upon clicking on "continue insertion with" all the previously set enum fields would also get reset to default.
bug

### Fixes 
Now, the previously set enum fields retain their value as expected and only the newly added enum fields are set to default value upon clicking "continue insertion with".
fix

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Comment by victorphoenix3** [comment]
@williamdes @mauriciofauth The PR is ready for review.

File: js/table/change.js [hunk 1]
```diff
@@ -619,6 +620,30 @@ function addNewContinueInsertionFiels (event) {
                 .find('.foreign_values_anchor')
                 .each(tempReplaceAnchor);
 
+            var $oldRow = $lastRow.find('.textfield');
+            $oldRow.each(function () {
+                if ($(this).closest('tr').find('span.column_type').html() === 'enum') {
+                    if ($(this).val() === $checkedValue) {
```
Comment (mauriciofauth) [inline js/table/change.js]: ESLint found 1 error:
https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/625894283#L404
```
Function declared in a loop contains unsafe references to variable(s) '$checkedValue'  no-loop-func
```
You can run ESLint yourself with the command:
```
yarn run js-lint
```

**Review by MauricioFauth — CHANGES_REQUESTED** [review]

File: js/table/change.js (hunk 1 above)
Comment (victorphoenix3) [reply js/table/change.js]: How do i sidestep this? I had to declare a new variable to $checkedValue to store the value of the enum field of the last row since it is lost during cloning.

Comment (victorphoenix3) [reply js/table/change.js]: @mauriciofauth

**Comment by victorphoenix3** [comment]
@williamdes  @mauriciofauth that js-lint error got fixed by defining the function outside the loop. Its ready for review.

**Review by williamdes — APPROVED** [review]
LGTM

I loved the GIFs that you made to show the change :100:

**Comment by victorphoenix3** [comment]
@williamdes  is this ready for merge?

**Comment by williamdes** [comment]
Thank you @victorphoenix3 for your patience and contribution !
Works fine now :tada:
