### PR TITLE
Button on Export Page to show SQL Query

### LINKED ISSUE #14340: How come no way to get back from table Export?
This has been driving me crazy for many versions. In the early days you used to be able to go back to your query from the Export page. But now, once you hit "Export", you're dead in the water. If you hit it by accident, or you do your export and realize you got wrong results or want to change something in the export or even if you just want to keep working on that query to export something else, there is no way to get back. Hopefully your query is saved in the Console history, but that's spotty at best and you have to open a new window to get the history to update. And I know the query is there on the page, in a hidden field, somewhere. When I'm desperate, I go into developer mode on my browser and search for the query so I can capture it and paste in a new window.  But how hard would it be to have a "Back to query" button? Or even just a "show your query" button and box where you could copy it out like I do from developer? I can't believe this doesn't bother others as much as it does me.

### PR DESCRIPTION
**Pull request by kartik1000**
Signed-off-by: Kartik Kathuria <kathuriakartik0@gmail.com>

### Description
Please describe your pull request.
The following PR adds Show SQL Query button on Export page, to show the SQL Query used for exporting. In case, one does not go to the export page after executing some SQL Query the button is not shown. 
Fixes #14340 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by kartik1000** [comment]
@williamdes please review :)

**Comment by williamdes** [comment]
@sudo-bot /deploy

File: js/export.js [hunk 1]
```diff
@@ -233,6 +233,39 @@ AJAX.registerTeardown('export.js', function () {
 });
 
 AJAX.registerOnload('export.js', function () {
+    // Fetch SQL Query used for exporting rows
+    var sqlquery = sessionStorage.getItem("sqlquery");
```
Comment (williamdes) [inline js/export.js]: You should use `if (isStorageSupported('sessionStorage')) {`

File: js/export.js [hunk 2]
```diff
@@ -233,6 +233,39 @@ AJAX.registerTeardown('export.js', function () {
...
+        var closing_options = {};
+        closing_options[PMA_messages.strClose] = function () {
+        $(this).dialog('close');
+        };
+        var $response_dialog = $sql_content.dialog({
+        minWidth: 550,
+        maxHeight: 400,
+        modal: true,
+        buttons: closing_options,
+        title: 'Sql query',
```
Comment (williamdes) [inline js/export.js]: Could you make this translatable ?

File: templates/display/export/template_loading.twig [hunk 3]
```diff
@@ -1,6 +1,16 @@
 <div class="exportoptions" id="export_templates">
     <h3>{% trans 'Export templates:' %}</h3>
 
+     <div class="floatleft">
+        <form method="post" action="tbl_export.php" class="ajax">
+            <div id = "sqlqueryform">
+            <h4>Show Sql Query:</h4>
```
Comment (williamdes) [inline templates/display/export/template_loading.twig]:
```suggestion
            <h4>{% trans 'Show Sql Query:' %}</h4>
```

File: templates/display/export/template_loading.twig [hunk 4]
```diff
@@ -1,6 +1,16 @@
...
+            <input type="submit" name="createTemplate" id="showsqlquery"
+                value="Show the SQL Query">
```
Comment (williamdes) [inline templates/display/export/template_loading.twig]:
```suggestion
                value="{% trans 'Show the SQL Query' %}">
```

File: js/export.js [hunk 5]
```diff
@@ -233,6 +233,40 @@ AJAX.registerTeardown('export.js', function () {
...
+            var closingoptions = {};
+            closingoptions[PMA_messages.strClose] = function () {
+                $(this).dialog('close');
+            };
+            var $response_dialog = $sqlcontent.dialog({
+            minWidth: 550,
+            maxHeight: 400,
+            modal: true,
+            buttons: closingoptions,
+            title: 'Sql query',
```
Comment (williamdes) [inline js/export.js]: Please make the string translatable like `PMA_messages.strClose`

`PMA_messages` to `Messages` was renamed by @mauriciofauth (ea2d5a0d87a706814df929e9c5cedee5f84e9fcc)

**Review by williamdes — CHANGES_REQUESTED** [review]

**Comment by kartik1000** [comment]
@williamdes  I made the change. Please review :)

File: js/export.js [hunk 6]
```diff
@@ -233,6 +233,40 @@ AJAX.registerTeardown('export.js', function () {
...
+        } else {
+            $('#sqlqueryform').show();
+        }
+        // must delete session storage variable everytime, to avoid any problem when users arrives at the export again
+        delete sessionStorage.sqlquery;
+        $('#showsqlquery').click(function(){
+            // Creating a dialog box similar to preview sql container to show sql query
+            var $sqlcontent = $('<div/>').append(sqlquery);
+            var closingoptions = {};
+            closingoptions[PMA_messages.strClose] = function () {
```
Comment (williamdes) [inline js/export.js]: `PMA_messages` was renamed to `Messages`

File: js/export.js [hunk 7]
```diff
@@ -233,6 +233,40 @@ AJAX.registerTeardown('export.js', function () {
...
+            minWidth: 550,
+            maxHeight: 400,
+            modal: true,
+            buttons: closingoptions,
+            title: PMA_messages.strQuery,
+            close: function () {
+            $(this).remove();
+            }, open: function () {
+                // Pretty SQL printing.
+                PMA_highlightSQL($(this));
```
Comment (williamdes) [inline js/export.js]: the function was renamed

**Comment by kartik1000** [comment]
@williamdes, renamed the functions.  Please review :)

**Review by williamdes — APPROVED** [review]

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
@sudo-bot Deploy PR

**Comment by williamdes** [comment]
I changed the ui part of your contribution
image
But I am still not sure about the placement of this button and you are not creating a workaround for #14340 

Maybe fixing the return button is a better idea :thinking: ?

**Comment by kartik1000** [comment]
@williamdes, I felt that the export page was designed such that it cannot return to the query page and that was not a bug. 
The ui is good and and a new heading was required :)
I feel that we can use maybe both. It can probably be used as shortcut rather than returning back and if not, and if this is no urgent then I can look for fix to return button and keep this PR open as well and change suggested change in the issue description 😄

**Comment by williamdes** [comment]
> I can look for fix to return button

That would be a great idea, seems like users are mad about that stupid return issue

**Comment by williamdes** [comment]
@kartik1000 Would it be possible to rebase onto latest master version and do not rely on local storage ?

**Comment by williamdes** [comment]
image

**Comment by williamdes** [comment]
@kartik1000 I worked on your code and simplified it, would you agree to review it ?

**Comment by kartik1000** [comment]
@williamdes, Yes sure! I will do it by tomorrow👍. On first look it looks good to me :)

**Comment by williamdes** [comment]
Merged !
Thank you !
