### PR TITLE
Fix create index form accepting too many columns

### LINKED ISSUE #16769: Fatal error when creating an index
### Describe the bug

A fatal error is given when a index on 9223372036854775808 columns is created.

### To Reproduce

1. Go to any table structure
2. Create an index on 9223372036854775808 columns
3. See error

### Expected behavior

The 9223372036854775808 number should be replaced with a smaller number.

### Screenshots

error

### Server configuration

- Operating system: Windows
- Web server: nginx/1.19.8
- Database version: 5.7.32
- PHP version: 8.0.3
- phpMyAdmin version: 5.2.0-dev+20210326.fe41637a0d

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

```
Fatal error:  Uncaught ValueError: The supplied range exceeds the maximum array size: start=1 end=9223372036854775807 in Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\tmp\twig\cb\cbec66d4ec6642f8f36b48da8a324e1c1e37d9c0b396c35c715ff67cf5ae8005.php:350
Stack trace:
#0 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\tmp\twig\cb\cbec66d4ec6642f8f36b48da8a324e1c1e37d9c0b396c35c715ff67cf5ae8005.php(350): range(1, '922337203685477...')
#1 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\vendor\twig\twig\src\Template.php(394): __TwigTemplate_f3eb8b8cbf64c06cee7628be9cba6069094f2b1c47e46d1040b40edeba9e9598->doDisplay(Array, Array)
#2 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\vendor\twig\twig\src\Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#3 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\vendor\twig\twig\src\Template.php(379): Twig\Template->display(Array)
#4 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\vendor\twig\twig\src\TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#5 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\libraries\classes\Template.php(156): Twig\TemplateWrapper->render(Array)
#6 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\libraries\classes\Controllers\AbstractController.php(37): PhpMyAdmin\Template->render('table/index_for...', Array)
#7 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\libraries\classes\Controllers\Table\IndexesController.php(197): PhpMyAdmin\Controllers\AbstractController->render('table/index_for...', Array)
#8 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\libraries\classes\Controllers\Table\IndexesController.php(74): PhpMyAdmin\Controllers\Table\IndexesController->displayForm(Object(PhpMyAdmin\Index))
#9 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\libraries\classes\Routing.php(189): PhpMyAdmin\Controllers\Table\IndexesController->index(Array)
#10 Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\index.php(18): PhpMyAdmin\Routing::callControllerForRoute('/table/indexes', Object(FastRoute\Dispatcher\GroupCountBased), Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#11 {main}
  thrown in Z:\nginx-1.19.8\html\phpMyAdmin-5.2.0-dev\tmp\twig\cb\cbec66d4ec6642f8f36b48da8a324e1c1e37d9c0b396c35c715ff67cf5ae8005.php on line 350
```

### PR DESCRIPTION
**Pull request by MauricioFauth**
From [Multiple-Column Indexes (MySQL 5.6 Reference Manual)](https://dev.mysql.com/doc/refman/5.6/en/multiple-column-indexes.html):
> An index may consist of up to 16 columns.

- Fixes #16769

### CODE REVIEW

File: libraries/classes/Controllers/Table/IndexesController.php [hunk 1]
```diff
@@ -184,6 +185,13 @@ public function displayForm(Index $index): void
 
         $this->addScriptFiles(['indexes.js']);
 
+        /**
+         * An index may consist of up to 16 columns.
+         *
+         * @link https://dev.mysql.com/doc/refman/5.6/en/multiple-column-indexes.html
```
Comment (williamdes) [inline libraries/classes/Controllers/Table/IndexesController.php:191]:
```suggestion
         * @link https://dev.mysql.com/doc/refman/5.6/en/multiple-column-indexes.html
         * @link https://mariadb.com/kb/en/innodb-limitations/#limitations-on-schema
```

File: libraries/classes/Controllers/Table/IndexesController.php [hunk 2]
```diff
@@ -184,6 +185,13 @@ public function displayForm(Index $index): void
 
         $this->addScriptFiles(['indexes.js']);
 
+        /**
+         * An index may consist of up to 16 columns.
```
Comment (williamdes) [inline libraries/classes/Controllers/Table/IndexesController.php:189]: MariaDB says "A multicolumn index on InnoDB can use a maximum of 16 columns. If you attempt to create a multicolumn index that uses more than 16 columns, MariaDB returns an Error 1070." on https://mariadb.com/kb/en/innodb-limitations/#limitations-on-schema

Maybe we should check if this is InnoDB

Comment (mauriciofauth) [reply libraries/classes/Controllers/Table/IndexesController.php:189]: - https://mariadb.com/kb/en/myisam-overview/:
  > Maximum of 32 columns per index.

Comment (mauriciofauth) [reply libraries/classes/Controllers/Table/IndexesController.php:189]: What about counting how many columns that table has and using that as a max value?

Comment (williamdes) [reply libraries/classes/Controllers/Table/IndexesController.php:189]: Sound a bit bad, not sure we should do that

Comment (mauriciofauth) [reply libraries/classes/Controllers/Table/IndexesController.php:189]: What I thought was using the number of columns if it was the less than 16 or 32 or whatever. Since it is on the table structure page, we already have amount of columns.

But I'm tending to keep 16 as the max for QA branches, even for MyISAM tables, because it's possible to add more columns in the modal if necessary. This will fix the reported error. 

Since it is a jQuery UI modal, it is difficult to use if too much columns are added. So we should replace it with the Bootstrap's modal. But this is only possible in master.

Comment (williamdes) [reply libraries/classes/Controllers/Table/IndexesController.php:189]: > What I thought was using the number of columns if it was the less than 16 or 32 or whatever. Since it is on the table structure page, we already have amount of columns.

I agree, just wondering if this is a good multi page workflow restriction of if in this case it will change nothing

**Comment by mauriciofauth** [comment]
The limit is only applied to the create index form now.

**Review by williamdes — APPROVED** [review]
