### PR TITLE
Fix truncate operation for views

### LINKED ISSUE #18762: Unable to truncate all tables when a VIEW is included.
### Describe the bug

When using the "Check all" method in phpMyAdmin, options can be selected that will result into an error. For example, when selecting all tables, views will be included/selected as well. When choosing the option to empty/truncate them, an error appears.

### To Reproduce

1. Go to phpMyAdmin, create a new table, for example, something like this:

```CREATE TABLE `test` (
  `id` INT NOT NULL AUTO_INCREMENT , PRIMARY KEY (`id`)
  `firstname` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastname` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;```

2. Also, create a VIEW, doesn't matter what, just create some, for example:

```CREATE VIEW `test2` AS SELECT * FROM `test`;```

3. Navigate to the database, choose "Check all" als select the option "Empty" in dropdown "With selected":

image

4. Click [ Yes ] to confirm the action:

image

5. See error

image

### Expected behavior

A view can't be truncated, so the statement ```TRUNCATE `test2`;``` can't be executed. However, I'm able to select it. I thins views shouldn't be included in the "Check all" option OR when views are checked, the option "Empty" should be disabled OR when views are included in the list with tables to empty/truncate, just skip them to prevent errors.

### PR DESCRIPTION
**Pull request by u7723606**
### Description

This pull request was for the issue #18762 
Currently, attempting to truncate a view results in an error because views cannot be truncated. I think it would be better to just skip over the views when they are included in the list of tables to truncate to prevent errors.

- Fixes #18762 

I added a check to truncate function so that if the target is a view, the TRUNCATE operation is not executed.

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: src/Partitioning/Maintenance.php [hunk 1]
```diff
@@ -134,17 +134,34 @@ public function repair(DatabaseName $db, TableName $table, string $partition): a
...
+            $this->dbi->$table->getName()
         );
 
-        $this->dbi->selectDb($db);
-        $result = $this->dbi->tryQuery($query);
-
-        return [(bool) $result, $query];
+        $result = $this->dbi->fetchResult($query);
+        return !empty($result);
+    }
```
Comment (williamdes) [inline src/Partitioning/Maintenance.php:147]: You do not need this function, the Table class has isView()

File: src/Partitioning/Maintenance.php [hunk 2]
```diff
@@ -134,17 +134,34 @@ public function repair(DatabaseName $db, TableName $table, string $partition): a
...
+    
+    public function truncate(DatabaseName $db, TableName $table, string $partition): array
+    {
+        if ($this->isView($db, $table)) {
```
Comment (williamdes) [inline src/Partitioning/Maintenance.php:151]: @MauricioFauth what is the best way to build a Table object from a TableName ?

Comment (MauricioFauth) [reply src/Partitioning/Maintenance.php:151]:
```suggestion
        if (\PhpMyAdmin\Table::get($table->getName(), $db->getName(), $this->dbi)->isView()) {
```

Comment (u7723606) [reply src/Partitioning/Maintenance.php:151]: Thanks! I gonna try this function and improve the truncate()

File: src/Partitioning/Maintenance.php [hunk 3]
```diff
@@ -136,6 +136,10 @@ public function repair(DatabaseName $db, TableName $table, string $partition): a
      */
     public function truncate(DatabaseName $db, TableName $table, string $partition): array
     {
+        if (\PhpMyAdmin\Table::get($table->getName(), $db->getName(), $this->dbi)->isView()) {
+            return [false, 'Table is a view, cannot truncate.'];
```
Comment (williamdes) [inline src/Partitioning/Maintenance.php:140]:
```suggestion
            return [false, _('This table is a view, it can not be truncated.')];
```
Adds translation

**Review by MauricioFauth — APPROVED** [review]

**Comment by MauricioFauth** [comment]
Merged, thanks for your contribution!
