### PR TITLE
Fix #17599 - Fix passwordForm is null

### LINKED ISSUE #17599: Uncaught TypeError: can't access property "generated_pw", passwordForm is null
### Describe the bug

Uncaught TypeError: can't access property "generated_pw", passwordForm is null

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/QA_5_2/index.php?route=/&db=INFORMATION_SCHEMA&table=PROCESSLIST](https://demo.phpmyadmin.net/QA_5_2/index.php?route=/&db=INFORMATION_SCHEMA&table=PROCESSLIST)
2. Click on any user
3. Click on `Generate`

### Expected behavior

A password should be generated and no error should be given.

### Screenshots

https://user-images.githubusercontent.com/25424343/173453655-eda2eb98-861b-4ebc-9c38-e674a9cb841f.mp4

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version: QA_5_2

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

```JSON
{
    "pma_version": "5.2.1-dev",
    "browser_name": "FIREFOX",
    "browser_version": "102.0",
    "user_os": "Win",
    "server_software": "nginx/1.14.2",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.4.29",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "can't access property \"generated_pw\", passwordForm is null",
        "stack": [
            {
                "func": "Functions.suggestPassword",
                "line": "598",
                "column": "16",
                "context": [
                    "  // \"editors and viewers regard the password as multiple words and",
                    "  // things like double click no longer work\"",
                    "  var pwchars = 'abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUV//...",
                    "  var passwordlength = 16; // do we want that to be dynamic?  no, keep it s//...",
                    "",
                    "  var passwd = passwordForm.generated_pw; // eslint-disable-next-line compa//...",
                    "",
                    "  var randomWords = new Int32Array(passwordlength);",
                    "  passwd.value = '';",
                    "  var i; // First we're going to try to use a built-in CSPRNG",
                    "  // eslint-disable-next-line compat/compat"
                ],
                "uri": "js/dist/functions.js?v=5.2.1-dev",
                "scriptname": "js/dist/functions.js"
            },
            {
                "func": "Functions.displayPasswordGenerateButton/pwdButton<",
                "line": "644",
                "column": "15",
                "context": [
                    "  var pwdButton = $('<input>').attr({",
                    "    type: 'button',",
                    "    id: 'button_generate_password',",
                    "    value: Messages.strGenerate",
                    "  }).addClass('btn btn-secondary button').on('click', function () {",
                    "    Functions.suggestPassword(this.form);",
                    "  });",
                    "  var pwdTextbox = $('<input>').attr({",
                    "    type: 'text',",
                    "    name: 'generated_pw',",
                    "    id: 'generated_pw'"
                ],
                "uri": "js/dist/functions.js?v=5.2.1-dev",
                "scriptname": "js/dist/functions.js"
            },
            {
                "func": "dispatch",
                "line": "2",
                "column": "43064",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.1-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "add/v.handle",
                "line": "2",
                "column": "41048",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.1-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "uri": "index.php?route=%2Fserver%2Fprivileges&username=pma&hostname=192.168.30.20%3A57532"
    }
}
```

### PR DESCRIPTION
**Pull request by liviuconcioiu**
Signed-off-by: Liviu-Mihail Concioiu <liviu.concioiu@gmail.com>

### Description

This PR fixes passwordForm is null error. The password won't be generated if the username isn't in the privilege table.

Fixes #17599

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: js/src/functions.js [hunk 1]
```diff
@@ -551,6 +551,11 @@ Functions.suggestPassword = function (passwordForm) {
     // things like double click no longer work"
     var pwchars = 'abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWYXZ@!_.*/()[]-';
     var passwordlength = 16;    // do we want that to be dynamic?  no, keep it simple :)
+
+    if (typeof passwordForm === 'undefined' || passwordForm === null) {
```
Comment (williamdes) [inline js/src/functions.js:555]: This patch works but when the password is typed does it make the strength progress?

Comment (liviuconcioiu) [reply js/src/functions.js:555]: No, but even if you try to add a user and type a password, the strength progress doesn't show. Only if Generate is clicked.

https://user-images.githubusercontent.com/25424343/215141832-fc734281-a2fe-42fb-8af1-f3568d67c630.mp4

Comment (liviuconcioiu) [reply js/src/functions.js:555]: https://user-images.githubusercontent.com/25424343/215142592-b100f1cf-a876-41eb-bce1-05a3b9adbdf0.mp4

Comment (williamdes) [reply js/src/functions.js:555]: In fact I am asking this because I tried to fix this and there is something wrong with the input ids or something like that that makes this undefined issue
But it's one level above that it should be fixed, what do you think?

Comment (liviuconcioiu) [reply js/src/functions.js:555]: > But it's one level above that it should be fixed, what do you think?

I'll take another look.

Comment (liviuconcioiu) [reply js/src/functions.js]: @williamdes `Login Information` was on each tab (it shouldn't) and also was out of `Change login information / Copy user account` section, if you look at the video.

Wrong placement: https://demo.phpmyadmin.net/QA_5_2/index.php?route=/server/privileges&username=pma&hostname=192.168.30.20%3A56974&dbname=&tablename=&routinename=

Good placement: https://demo.phpmyadmin.net/QA_5_2/index.php?route=/server/privileges&username=kevinmoreno&hostname=localhost&dbname=&tablename=&routinename=

**Review by MauricioFauth — APPROVED** [review]

File: js/src/functions.js (hunk 1 above)
Comment (williamdes) [reply js/src/functions.js]: Thank you for the research and fix :)
