### PR TITLE
Clear config storage params from session after failed access

### LINKED ISSUE #17368: Could not save configuration #1049 - Unknown database 'phpmyadmin'
### Describe the bug

Could not save configuration `#1049 - Unknown database 'phpmyadmin'` error is given when refreshing home page. ~~This is only shown on Firefox. Possibly related to https://github.com/phpmyadmin/phpmyadmin/commit/1faab7119d3eb9ffed32632042f5fbafe69c582e~~

Also, I've noticed that phpmyadmin can be created, it will appear in databases, but there is no way to remove it.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/](https://demo.phpmyadmin.net/master-config/)
2. See error

### Expected behavior

The error should not show.

### Screenshots

https://user-images.githubusercontent.com/25424343/153518010-eafbc53a-2d9c-4453-9f6a-bff965433ac8.mp4

https://user-images.githubusercontent.com/25424343/153519275-e5cccdd3-1b93-42f6-be13-ceda47edd560.mp4

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version: 5.1.3

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

Edit: Affects phpMyAdmin 5.1 and all browsers.

### PR DESCRIPTION
**Pull request by MauricioFauth**
The issue happens when the config storage is deleted after a session is started. The error message will still appears, but only a single time, because the the config storage will be cleared from session, forcing phpMyAdmin to check it again.

- Fixes #17368

### CODE REVIEW

File: libraries/classes/UserPreferences.php [hunk 1]
```diff
@@ -166,12 +168,19 @@ public function save(array $config_array)
...
-                ),
-                '<br><br>'
+            $message->addMessage(Message::error($dbi->getError(DatabaseInterface::CONNECT_CONTROL)), '<br><br>');
+            $hasConfigDatabase = $dbi->fetchSingleRow(
+                'SHOW DATABASES LIKE \'' . $dbi->escapeString($cfgRelation['db']) . '\';',
+                'ASSOC',
+                DatabaseInterface::CONNECT_CONTROL
             );
+            if (! $hasConfigDatabase) {
+                $_SESSION['relation'][$GLOBALS['server']] = [];
```
Comment (williamdes) [inline libraries/classes/UserPreferences.php:178]: Could you add a comment about why this is here ?

File: libraries/classes/UserPreferences.php [hunk 2]
```diff
@@ -166,12 +168,19 @@ public function save(array $config_array)
...
         if (! $dbi->tryQuery($query, DatabaseInterface::CONNECT_CONTROL)) {
             $message = Message::error(__('Could not save configuration'));
-            $message->addMessage(
-                Message::rawError(
-                    $dbi->getError(DatabaseInterface::CONNECT_CONTROL)
-                ),
-                '<br><br>'
+            $message->addMessage(Message::error($dbi->getError(DatabaseInterface::CONNECT_CONTROL)), '<br><br>');
+            $hasConfigDatabase = $dbi->fetchSingleRow(
+                'SHOW DATABASES LIKE \'' . $dbi->escapeString($cfgRelation['db']) . '\';',
```
Comment (williamdes) [inline libraries/classes/UserPreferences.php:173]: Not sure if some access control could make this a false positive ?

File: libraries/classes/UserPreferences.php (hunk 1 above)
Comment (mauriciofauth) [reply libraries/classes/UserPreferences.php:178]: Sure!

**Review by williamdes — APPROVED** [review]

File: libraries/classes/UserPreferences.php (hunk 2 above)
Comment (kamil-tekiela) [reply libraries/classes/UserPreferences.php:172]: The value of `$cfgRelation['db']` should be escaped against `_%\` probably.

Comment (mauriciofauth) [reply libraries/classes/UserPreferences.php]: You're both right. Thanks @williamdes and @kamil-tekiela.

**Review by williamdes — APPROVED** [review]
💯

**Review by williamdes — APPROVED** [review]
