### PR TITLE
Fix #20007 - Update create-release.sh with file to be excluded

### LINKED ISSUE #20007: [6.0]: Files to be excluded
### Describe the bug

```
Searching for files
Found unexpected file: vendor/spomky-labs/cbor-php/RELEASES.md with extension md
Found unexpected file: vendor/symfony/dependency-injection/Loader/schema/services.schema.json with extension json
Some new files to be excluded were found.
Please update create-release.sh
```

### How to Reproduce

https://github.com/phpmyadmin/phpmyadmin/actions/runs/20629566664/job/59245380976#step:12:21

### phpMyAdmin version

6.0.0-dev

### PR DESCRIPTION
**Pull request by liviuconcioiu**
### Description

Fixes #20007

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Comment by liviuconcioiu** [comment]
Is there something wrong with the PR? I don't see them being removed:

https://github.com/phpmyadmin/phpmyadmin/actions/runs/23380153474/job/68018242644#step:12:77

**Comment by MauricioFauth** [comment]
> Is there something wrong with the PR? I don't see them being removed:

I think this script uses the `master` branch instead of the PR code. 

@williamdes Do you think there's a easy way to run `create-release.sh` with the PR code when the file is modified? Otherwise I don't it's worth running it in pull requests.

**Review by MauricioFauth — APPROVED** [review]

File: bin/internal/create-release.sh [hunk 1]
```diff
@@ -185,21 +187,32 @@ cleanup_composer_vendors() {
...
 
     rm \
         vendor/phpmyadmin/motranslator/CODE_OF_CONDUCT.md \
         vendor/phpmyadmin/motranslator/CONTRIBUTING.md \
         vendor/phpmyadmin/motranslator/PERFORMANCE.md \
         vendor/phpmyadmin/shapefile/CONTRIBUTING.md \
-        vendor/spomky-labs/cbor-php/CODE_OF_CONDUCT.md
+        vendor/spomky-labs/cbor-php/CODE_OF_CONDUCT.md \
+        vendor/spomky-labs/cbor-php/RELEASES.md \
+        vendor/spomky-labs/cbor-php/SECURITY.md \
```
Comment (MauricioFauth) [inline bin/internal/create-release.sh:213]:
```suggestion
        vendor/spomky-labs/cbor-php/SECURITY.md \
        vendor/spomky-labs/pki-framework/SECURITY.md \
```

**Comment by williamdes** [comment]
> @williamdes Do you think there's a easy way to run create-release.sh with the PR code when the file is modified? Otherwise I don't it's worth running it in pull requests.

yes it is already done, I am pretty sure

File: bin/internal/create-release.sh [hunk 2]
```diff
@@ -160,14 +160,16 @@ cleanup_composer_vendors() {
...
+        vendor/phpmyadmin/motranslator/psalm.xml \
         vendor/phpmyadmin/motranslator/tests/ \
         vendor/phpmyadmin/shapefile/phpunit.xml.dist \
         vendor/phpmyadmin/shapefile/tests/ \
         vendor/phpmyadmin/shapefile/examples/ \
         vendor/phpmyadmin/shapefile/data/ \
         vendor/symfony/service-contracts/Test/ \
         vendor/symfony/expression-language/Resources/ \
-        vendor/symfony/dependency-injection/Loader/schema/dic/services/services-1.0.xsd \
+        vendor/symfony/dependency-injection/Loader/schema/ \
```
Comment (williamdes) [inline bin/internal/create-release.sh]: I am not sure it is safe to blindly delete all the folder

File: bin/internal/create-release.sh [hunk 3]
```diff
@@ -185,21 +187,32 @@ cleanup_composer_vendors() {
...
+        vendor/spomky-labs/cbor-php/CODE_OF_CONDUCT.md \
+        vendor/spomky-labs/cbor-php/RELEASES.md \
+        vendor/spomky-labs/cbor-php/SECURITY.md \
+        vendor/web-auth/cose-lib/CODE_OF_CONDUCT.md \
+        vendor/web-auth/cose-lib/RELEASES.md \
+        vendor/web-auth/cose-lib/SECURITY.md \
+        vendor/slim/psr7/phpunit.xml.dist \
+        vendor/laminas/laminas-httphandlerrunner/.laminas-ci.json \
+        vendor/psr/event-dispatcher/.editorconfig \
+        vendor/google/recaptcha/app.yaml
```
Comment (williamdes) [inline bin/internal/create-release.sh]: non markdown files should move above

**Comment by liviuconcioiu** [comment]
I applied the changes, but the files aren't removed:

https://github.com/phpmyadmin/phpmyadmin/actions/runs/24047165958/job/70133342203#step:12:75

**Review by MauricioFauth — APPROVED** [review]

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
> I applied the changes, but the files aren't removed:
> 
> https://github.com/phpmyadmin/phpmyadmin/actions/runs/24047165958/job/70133342203#step:12:75

Indeed, this is weird. Maybe it does not use the right branch

**Comment by williamdes** [comment]
Yes that is it, the branch is hard coded. It should not run for PRs I guess
