### PR TITLE
show error message on export page when database is empty

### LINKED ISSUE #13572: Nothing on Export page when database is empty
### Steps to reproduce
1. Create a new database
2. Open export page
3. Nothing on page

### Expected behaviour
Should show some message like "No tables in the database"

### Actual behaviour
Nothing on page.
screenshot from 2017-08-06 17-59-41

### PR DESCRIPTION
**Pull request by manishbisht**
Fixes: #13572

Signed-off-by: Manish Bisht <manish.bisht490@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

screenshot from 2017-08-14 06-57-35

### CODE REVIEW

File: db_export.php [hunk 1]
```diff
@@ -48,7 +48,8 @@
 
 // exit if no tables in db found
 if ($num_tables < 1) {
-    PhpMyAdmin\Message::error(__('No tables found in database.'))->display();
+    $message = PhpMyAdmin\Message::error(__('No tables found in database.'));
+    $message->getDisplay();
```
Comment (nijel) [inline db_export.php]: The getDisplay method just returns the message to display, so this can not work. What was wrong on the previous code?

Comment (manishbisht) [inline db_export.php]: Earlier the error was not displaying on the page.

Comment (nijel) [inline db_export.php]: You're right. It seems that Reponse class is showing global $message if set, so that's why your change works, the getDisplay method is not really doing anything useful here.

**Comment by nijel** [comment]
I've merged your changes, but in the end I've rewritten the code again in ec9fe20e48882e76197804e96ac6ae543665397e
