### PR TITLE
Fix #16935 Remove hardcoded row length

### LINKED ISSUE #16935: The char/varchar textarea minimum height is incorrectly fixed to 7 rows
### Describe the bug

The char/varchar textarea minimum height is incorrectly fixed to 7 rows

### To Reproduce

1. Configure a small value for  `$cfg['CharTextareaRows']`, like for instance 2 (which is supposed to be the default, according to the documentation)
2. Open the form to edit or insert a record
3. Observe that he textarea is 7 rows tall

### Expected behavior

The textarea height is supposed to respect the `$cfg['CharTextareaRows']` config option.

### Additional context

The issue is located at https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/InsertEdit.php#L584 and has been introduced by PR #14379.
Here we can see `$textAreaRows = max($GLOBALS['cfg']['CharTextareaRows'], 7);`, which actually sets the lower boundary of CharTextareaRows to 7.

### PR DESCRIPTION
**Pull request by shucontech**
Signed-off-by: Saksham Gupta <shucontech@gmail.com>

### Description

Please describe your pull request.

Fixes #16935 

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

File: libraries/classes/InsertEdit.php [hunk 1]
```diff
@@ -1030,7 +1030,7 @@ private function getTextarea(
              *       why character columns have the "char" class instead
              */
             $the_class = 'char charField';
-            $textAreaRows = max($GLOBALS['cfg']['CharTextareaRows'], 7);
+            $textAreaRows = $GLOBALS['cfg']['CharTextareaRows'];
```
Comment (williamdes) [inline libraries/classes/InsertEdit.php:1033]: You need to edit the config.default file to keep the actual behavior
And also edit the docs to make this change clear

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
I added 0c904d6990336a704a2bab97a3d5ea18f20a2264 onto it
