### PR TITLE
Fix #17451 - fetchValue call with connection parameter

### LINKED ISSUE #17451: Rows count for table_uiprefs
### Describe the bug

A regular user cannot read the table "table_uiprefs", so table rows cannot be counted to check if they exceed MaxTableUiprefs. Rows count must be fetched as controluser, not as logged in user.

### To Reproduce

1. Enable the SQL errors log in MariaDB ("sql_error_log_filename" variable)
2. Login as user with limited privileges (not root)
3. Browse any table
4. See error in log file: "'SELECT' command denied to user: ... SELECT COUNT(*) FROM `phpmyadmin`.`pma__table_uiprefs`"

### Expected behavior

No error.

### Server configuration

- Operating system: Linux
- Web server: Apache
- Database version: MariaDB 10.6.7
- PHP version: 8.1.2
- phpMyAdmin version:  5.3.0-dev+20220208.47252f9cf8

### Client configuration

- Browser:  any
- Operating system:  any

### Additional context

Bug can be fixed by modifying line 1806 in file libraries/classes/Table.php:

from:
        $rowsCount = (int) $this->dbi->fetchValue($sqlQuery);

to:
        $rowsCount = (int) $this->dbi->fetchValue($sqlQuery, 0, DatabaseInterface::CONNECT_CONTROL);

### PR DESCRIPTION
**Pull request by gs71**
### Description

A regular user cannot read the table "table_uiprefs", so table rows cannot be counted to check if they exceed MaxTableUiprefs. Rows count must be fetched as controluser, not as logged in user.

Fixes #17451

Before submitting pull request, please review the following checklist:

- [X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [X] Every commit has a descriptive commit message.
- [X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

Signed-off-by: Guido Selva <guido.selva@gmail.com>

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Thank you for your contribution !
And taking the time to make pull-requests to fix some issues

File: libraries/classes/Table.php [hunk 1]
```diff
@@ -1824,7 +1824,7 @@ protected function saveUiPrefsToDb(UiPreferencesFeature $uiPreferencesFeature)
         // Remove some old rows in table_uiprefs if it exceeds the configured
         // maximum rows
         $sqlQuery = 'SELECT COUNT(*) FROM ' . $table;
-        $rowsCount = (int) $this->dbi->fetchValue($sqlQuery);
+        $rowsCount = (int) $this->dbi->fetchValue($sqlQuery, 0, DatabaseInterface::CONNECT_CONTROL)
```
Comment (williamdes) [inline libraries/classes/Table.php:1827]:
```suggestion
        $rowsCount = (int) $this->dbi->fetchValue($sqlQuery, 0, DatabaseInterface::CONNECT_CONTROL);
```

**Comment by williamdes** [comment]
Merged as 3d0e40a9fb1fe14795b7499cc870c9e9da021780 with a fix for the missing `;`
