### PR TITLE
Fix #19987 - Reopening a function removes charset

### LINKED ISSUE #19987: [Bug]: Reopening a function removes charset
### Describe the bug

Opening an existing FUNCTION with a different charset than default this is ignored. Saving and closing removes the charset.

### How to Reproduce

1. open an existing FUNCTION with a specified result charset (observe under return options the charset being ignored)
2. make and undo a small change
3. save the function

### Expected behavior

Nothing changes, the return charset remains.

### Screenshots

Image

### Operating System

_No response_

### Web Server

_No response_

### Database Server

_No response_

### Database version

_No response_

### PHP version

8.3.17

### phpMyAdmin version

Version information: 5.2.2, latest stable version: 5.2.3

### browser

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by decob**
### Description
Opening and updating an existing function that has a different return CHARSET than the default CHARSET for the table or database. On saving, the CHARSET for the function changes to the DB default. Note: this online happens when the function created also uses COLLATE.

Please describe your pull request.
Took a bit of time to diagnose and replicate  but ultimately was only happening when a function was created that had both a CHARSET and COLLATE sets.

So starting off, created 2 functions that had a different return CHARSET than the database default. (so DB was ASCII., Functions Latin1)

```sql
  DROP FUNCTION IF EXISTS test_charset_latin1_collate;
  CREATE FUNCTION test_charset_latin1_collate()
  RETURNS VARCHAR(100) CHARACTER SET LATIN1 COLLATE latin1_general_ci
  DETERMINISTIC
  RETURN 'test';

  DROP FUNCTION IF EXISTS test_charset_latin1_no_collate;
  CREATE FUNCTION test_charset_latin1_no_collate()
  RETURNS VARCHAR(100) CHARACTER SET latin1
  DETERMINISTIC
  RETURN 'test';
```

On viewing the 2 functions in the UI, the function with no COLLATE was correctly showing the return CHARSET
Screenshot 2026-01-11 at 13 44 55

where as the function with a COLLATE set was not, and the 'charset'  from the dropdown as no option was selected..
Screenshot 2026-01-11 at 13 44 50

So in this instance when you saved, it set the CHARSET of the function to the database default.

This was happening due to the $options value used here
```
            $retval['item_returnopts_num'] = implode(' ', $options);
            $retval['item_returnopts_text'] = implode(' ', $options);
```
returning an array of 2 items - the CHARSET and COLLATE, so the string for item_returnopts_text used in the twig template was in my example was "latin1 latin1_general_ci", and in turned used to compare with charset.getName

`{{ routine.item_returnopts_text == charset.getName() ? ' selected' }}
`

So my fix separately works out the charset text and numeric values. I did contemplate doing a hackier fix in the twig template  but better to return the actual CHARSET to the view 

Fixes #19987 Reopening a function removes charset

Before submitting pull request, please review the following checklist:

- [ X] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ X] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ X] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ X] Every commit has a descriptive commit message.
- [ X] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

File: libraries/classes/Database/Routines.php [hunk 1]
```diff
@@ -624,18 +624,33 @@ public function getDataFromName($name, $type, $all = true): ?array
         $retval['item_returnopts_text'] = '';
 
         if (! empty($routine['DTD_IDENTIFIER'])) {
-            $options = [];
+            $retval['item_returntype'] = $stmt->return->name;
+            $retval['item_returnlength'] = implode(',', $stmt->return->parameters);
+
+            // Extract charset (CHARSET or CHARACTER SET) separately from numeric options
+            /** @var string|false $charset */
+            $charset = $stmt->return->options->has('CHARSET');
```
Comment (williamdes) [inline libraries/classes/Database/Routines.php:632]: You should probably fix the PHPStan errors because it is never wrong on what can happen in your code

**Comment by williamdes** [comment]
This looks nice, I will test it

**Comment by decob** [comment]
@williamdes I've addressed that PHPStan issue - was just unused ignore in the baseline that needed removing since my fix addressed them. I take it that selenium failure is just a flakey test

**Review by williamdes — APPROVED** [review]
Thank you !
