### PR TITLE
Fix table creation

### LINKED ISSUE #17544: Create table on Designer gives a 400 error
### Describe the bug

When creating a table from Designer, it gives a 400 error. This only affects 5.3.0-dev.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/index.php?route=/database/designer&db=sakila](https://demo.phpmyadmin.net/master/index.php?route=/database/designer&db=sakila)
2. Click on 'Create table'
3. See error

### Expected behavior

User should be allowed to create a new table.

### Screenshots

https://user-images.githubusercontent.com/25424343/169703337-5b115644-2e06-467d-95fe-bbae864a3655.mp4

### Server configuration

- Operating system: Linux
- Web server: nginx/1.14.2
- Database version: 8.0.18 - MySQL Community Server - GPL
- PHP version: 7.4.29
- phpMyAdmin version: 5.3.0-dev

### Client configuration

- Browser: Chrome/101.0.4951.67
- Operating system: Windows 10

### Additional context

Add any other context about the bug here.

### PR DESCRIPTION
**Pull request by kamil-tekiela**
Fixes #17544 

@MauricioFauth Could you please take a look? I removed 2 globabls which IMHO shouldn't be global and excluded check for table, because that is an optional argument. The page can be opened without providing the table name.

### CODE REVIEW

File: libraries/classes/Controllers/Table/CreateController.php [hunk 1]
```diff
@@ -98,7 +96,7 @@ public function __invoke(ServerRequest $request): void
 
         $createAddField = new CreateAddField($this->dbi);
 
-        $GLOBALS['num_fields'] = $createAddField->getNumberOfFieldsFromRequest();
+        $num_fields = $createAddField->getNumberOfFieldsFromRequest();
```
Comment (williamdes) [inline libraries/classes/Controllers/Table/CreateController.php:99]:
```suggestion
        $numFields = $createAddField->getNumberOfFieldsFromRequest();
```

**Review by williamdes — APPROVED** [review]
Looks okay

**Review by MauricioFauth — APPROVED** [review]

**Comment by MauricioFauth** [comment]
> I removed 2 globabls which IMHO shouldn't be global

@kamil-tekiela  When we converted the entry points from files to routes, we explicit mark as global most of the implicit global variables to avoid issues. This is why there are some unnecessary global vars.
