### PR TITLE
Fix #17329 - catch the bigSQL error.

### LINKED ISSUE #17329: Uncaught DOMException: The quota has been exceeded.
### Describe the bug

Uncaught DOMException: The quota has been exceeded. when pasting a few large queries inside SQL box. All versions have this problem.

### To Reproduce

1. Go to 'SQL' tab.
2. Paste a few large texts, 15-20 Mb.
3. See error

### Expected behavior

The exception should be caught somehow or a message should be given.

### Server configuration

- Operating system: Windows 10
- Web server: nginx/1.21.6
- Database version: MySQL 5.7.37
- PHP version: 8.1.2
- phpMyAdmin version: 5.3.0-dev

### Client configuration

- Browser: Firefox 97
- Operating system: Windows 10

### Additional context

```JSON
{
    "pma_version": "5.3.0-dev",
    "browser_name": "FIREFOX",
    "browser_version": "97.0",
    "user_os": "Win",
    "server_software": "nginx/1.21.6",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0",
    "locale": "en",
    "configuration_storage": "enabled",
    "php_version": "8.1.2",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "QuotaExceededError",
        "message": "The quota has been exceeded.",
        "stack": [
            {
                "func": "Sql.autoSave",
                "line": "64",
                "column": "27",
                "context": [
                    "Sql.autoSave = function (query) {",
                    "  if (query) {",
                    "    var key = Sql.getAutoSavedKey();",
                    "",
                    "    if (isStorageSupported('localStorage')) {",
                    "      window.localStorage.setItem(key, query);",
                    "    } else {",
                    "      Cookies.set(key, query);",
                    "    }",
                    "  }",
                    "};"
                ],
                "uri": "js/dist/sql.js?v=5.3.0-dev",
                "scriptname": "js/dist/sql.js"
            },
            {
                "func": "?",
                "line": "262",
                "column": "13",
                "context": [
                    "  }",
                    "",
                    "  $(function () {",
                    "    if (codeMirrorEditor) {",
                    "      codeMirrorEditor.on('change', function () {",
                    "        Sql.autoSave(codeMirrorEditor.getValue());",
                    "      });",
                    "    } else {",
                    "      $('#sqlquery').on('input propertychange', function () {",
                    "        Sql.autoSave($('#sqlquery').val());",
                    "      });"
                ],
                "uri": "js/dist/sql.js?v=5.3.0-dev",
                "scriptname": "js/dist/sql.js"
            },
            {
                "func": "signalLater/loop/<",
                "line": "2084",
                "column": "45",
                "context": [
                    "    } else {\r",
                    "      list = orphanDelayedCallbacks = [];\r",
                    "      setTimeout(fireOrphanDelayed, 0);\r",
                    "    }\r",
                    "    var loop = function ( i ) {\r",
                    "      list.push(function () { return arr[i].apply(null, args); });\r",
                    "    };\r",
                    "\r",
                    "    for (var i = 0; i < arr.length; ++i)\r",
                    "      loop( i );\r",
                    "  }\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "fireCallbacksForOps",
                "line": "2041",
                "column": "24",
                "context": [
                    "    // Calls delayed callbacks and cursorActivity handlers until no\r",
                    "    // new ones appear\r",
                    "    var callbacks = group.delayedCallbacks, i = 0;\r",
                    "    do {\r",
                    "      for (; i < callbacks.length; i++)\r",
                    "        { callbacks[i].call(null); }\r",
                    "      for (var j = 0; j < group.ops.length; j++) {\r",
                    "        var op = group.ops[j];\r",
                    "        if (op.cursorActivityHandlers)\r",
                    "          { while (op.cursorActivityCalled < op.cursorActivityHandlers.length)\r",
                    "            { op.cursorActivityHandlers[op.cursorActivityCalled++].call(nul//..."
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "finishOperation",
                "line": "2055",
                "column": "30",
                "context": [
                    "\r",
                    "  function finishOperation(op, endCb) {\r",
                    "    var group = op.ownsGroup;\r",
                    "    if (!group) { return }\r",
                    "\r",
                    "    try { fireCallbacksForOps(group); }\r",
                    "    finally {\r",
                    "      operationGroup = null;\r",
                    "      endCb(group);\r",
                    "    }\r",
                    "  }\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "endOperation",
                "line": "3816",
                "column": "30",
                "context": [
                    "  }\r",
                    "\r",
                    "  // Finish an operation, updating the display and signalling delayed events\r",
                    "  function endOperation(cm) {\r",
                    "    var op = cm.curOp;\r",
                    "    if (op) { finishOperation(op, function (group) {\r",
                    "      for (var i = 0; i < group.ops.length; i++)\r",
                    "        { group.ops[i].cm.curOp = null; }\r",
                    "      endOperations(group);\r",
                    "    }); }\r",
                    "  }\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "runInOp",
                "line": "3945",
                "column": "27",
                "context": [
                    "  // Run the given function in an operation\r",
                    "  function runInOp(cm, f) {\r",
                    "    if (cm.curOp) { return f() }\r",
                    "    startOperation(cm);\r",
                    "    try { return f() }\r",
                    "    finally { endOperation(cm); }\r",
                    "  }\r",
                    "  // Wraps a function in an operation. Returns the wrapped function.\r",
                    "  function operation(cm, f) {\r",
                    "    return function() {\r",
                    "      if (cm.curOp) { return f.apply(cm, arguments) }\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "handlePaste",
                "line": "8191",
                "column": "18",
                "context": [
                    "  function handlePaste(e, cm) {\r",
                    "    var pasted = e.clipboardData && e.clipboardData.getData(\"Text\");\r",
                    "    if (pasted) {\r",
                    "      e.preventDefault();\r",
                    "      if (!cm.isReadOnly() && !cm.options.disableInput)\r",
                    "        { runInOp(cm, function () { return applyTextInput(cm, pasted, 0, nu//...",
                    "      return true\r",
                    "    }\r",
                    "  }\r",
                    "\r",
                    "  function triggerElectric(cm, inserted) {\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "TextareaInput.prototype.init/<",
                "line": "9363",
                "column": "36",
                "context": [
                    "      if (ie && ie_version >= 9 && this$1.hasSelection) { this$1.hasSelecti//...",
                    "      input.poll();\r",
                    "    });\r",
                    "\r",
                    "    on(te, \"paste\", function (e) {\r",
                    "      if (signalDOMEvent(cm, e) || handlePaste(e, cm)) { return }\r",
                    "\r",
                    "      cm.state.pasteIncoming = +new Date;\r",
                    "      input.fastPoll();\r",
                    "    });\r",
                    "\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "EventListener.handleEvent*on",
                "line": "536",
                "column": "15",
                "context": [
                    "\r",
                    "  var noHandlers = [];\r",
                    "\r",
                    "  var on = function(emitter, type, f) {\r",
                    "    if (emitter.addEventListener) {\r",
                    "      emitter.addEventListener(type, f, false);\r",
                    "    } else if (emitter.attachEvent) {\r",
                    "      emitter.attachEvent(\"on\" + type, f);\r",
                    "    } else {\r",
                    "      var map = emitter._handlers || (emitter._handlers = {});\r",
                    "      map[type] = (map[type] || noHandlers).concat(f);\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "TextareaInput.prototype.init",
                "line": "9362",
                "column": "7",
                "context": [
                    "    on(te, \"input\", function () {\r",
                    "      if (ie && ie_version >= 9 && this$1.hasSelection) { this$1.hasSelecti//...",
                    "      input.poll();\r",
                    "    });\r",
                    "\r",
                    "    on(te, \"paste\", function (e) {\r",
                    "      if (signalDOMEvent(cm, e) || handlePaste(e, cm)) { return }\r",
                    "\r",
                    "      cm.state.pasteIncoming = +new Date;\r",
                    "      input.fastPoll();\r",
                    "    });\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "Display",
                "line": "4463",
                "column": "11",
                "context": [
                    "    d.activeTouch = null;\r",
                    "\r",
                    "    d.gutterSpecs = getGutters(options.gutters, options.lineNumbers);\r",
                    "    renderGutters(d);\r",
                    "\r",
                    "    input.init(d);\r",
                    "  }\r",
                    "\r",
                    "  // Since the delta values reported on mouse wheel events are\r",
                    "  // unstandardized between browsers and even browser versions, and\r",
                    "  // generally horribly unpredictable, this code starts by measuring\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "CodeMirror",
                "line": "7890",
                "column": "34",
                "context": [
                    "    if (typeof doc == \"string\") { doc = new Doc(doc, options.mode, null, op//...",
                    "    else if (options.mode) { doc.modeOption = options.mode; }\r",
                    "    this.doc = doc;\r",
                    "\r",
                    "    var input = new CodeMirror.inputStyles[options.inputStyle](this);\r",
                    "    var display = this.display = new Display(place, doc, input, options);\r",
                    "    display.wrapper.CodeMirror = this;\r",
                    "    themeChanged(this);\r",
                    "    if (options.lineWrapping)\r",
                    "      { this.display.wrapper.className += \" CodeMirror-wrap\"; }\r",
                    "    initScrollbars(this);\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "CodeMirror",
                "line": "7878",
                "column": "49",
                "context": [
                    "  // that user code is usually dealing with.\r",
                    "\r",
                    "  function CodeMirror(place, options) {\r",
                    "    var this$1 = this;\r",
                    "\r",
                    "    if (!(this instanceof CodeMirror)) { return new CodeMirror(place, optio//...",
                    "\r",
                    "    this.options = options = options ? copyObj(options) : {};\r",
                    "    // Determine effective options based on given values and defaults.\r",
                    "    copyObj(defaults, options, false);\r",
                    "\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "fromTextArea",
                "line": "9743",
                "column": "24",
                "context": [
                    "        }\r",
                    "      };\r",
                    "    };\r",
                    "\r",
                    "    textarea.style.display = \"none\";\r",
                    "    var cm = CodeMirror(function (node) { return textarea.parentNode.insert//...",
                    "      options);\r",
                    "    return cm\r",
                    "  }\r",
                    "\r",
                    "  function addLegacyProps(CodeMirror) {\r"
                ],
                "uri": "js/vendor/codemirror/lib/codemirror.js?v=5.3.0-dev",
                "scriptname": "js/vendor/codemirror/lib/codemirror.js"
            },
            {
                "func": "Functions.getSqlEditor",
                "line": "338",
                "column": "39",
                "context": [
                    "      });",
                    "    }",
                    "",
                    "    $.extend(true, defaults, options); // create CodeMirror editor",
                    "",
                    "    var codemirrorEditor = CodeMirror.fromTextArea($textarea[0], defaults);//...",
                    "",
                    "    if (!resizeType) {",
                    "      resizeType = 'vertical';",
                    "    }",
                    ""
                ],
                "uri": "js/dist/functions.js?v=5.3.0-dev",
                "scriptname": "js/dist/functions.js"
            },
            {
                "func": "?",
                "line": "3929",
                "column": "36",
                "context": [
                    "    return;",
                    "  }",
                    "",
                    "  if ($elm.length > 0) {",
                    "    if (typeof CodeMirror !== 'undefined') {",
                    "      codeMirrorEditor = Functions.getSqlEditor($elm);",
                    "      codeMirrorEditor.focus();",
                    "      codeMirrorEditor.on('blur', Functions.updateQueryParameters);",
                    "    } else {",
                    "      // without codemirror",
                    "      $elm.trigger('focus').on('blur', Functions.updateQueryParameters);"
                ],
                "uri": "js/dist/functions.js?v=5.3.0-dev",
                "scriptname": "js/dist/functions.js"
            },
            {
                "func": "dispatch",
                "line": "2",
                "column": "43064",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "add/v.handle",
                "line": "2",
                "column": "41048",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "trigger",
                "line": "2",
                "column": "71515",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "trigger/<",
                "line": "2",
                "column": "72110",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "3003",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1481",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "trigger",
                "line": "2",
                "column": "72086",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fireOnload",
                "line": "131",
                "column": "17",
                "context": [
                    "   *",
                    "   * @return {void}",
                    "   */",
                    "  fireOnload: function (file) {",
                    "    var eventName = 'onload_' + AJAX.hash(file);",
                    "    $(document).trigger(eventName);",
                    "",
                    "    if (this.debug) {",
                    "      // eslint-disable-next-line no-console",
                    "      console.log( // no need to translate",
                    "      'Fired event ' + eventName + ' for file ' + file);"
                ],
                "uri": "js/dist/ajax.js?v=5.3.0-dev",
                "scriptname": "js/dist/ajax.js"
            },
            {
                "func": "?",
                "line": "218",
                "column": "12",
                "context": [
                    "              AJAX.fireOnload('menu_resizer.js');",
                    "        AJAX.fireOnload('vendor/tracekit.js');",
                    "      AJAX.fireOnload('error_report.js');",
                    "        AJAX.fireOnload('config.js');",
                    "      AJAX.fireOnload('doclinks.js');",
                    "      AJAX.fireOnload('functions.js');",
                    "      AJAX.fireOnload('navigation.js');",
                    "      AJAX.fireOnload('indexes.js');",
                    "      AJAX.fireOnload('common.js');",
                    "      AJAX.fireOnload('page_settings.js');",
                    "      AJAX.fireOnload('drag_drop_import.js');"
                ],
                "uri": "index.php?route=%2Ftable%2Fsql",
                "scriptname": "index.php"
            },
            {
                "func": "e",
                "line": "2",
                "column": "30038",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "Deferred/then/l/</t<",
                "line": "2",
                "column": "30340",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "setTimeout handler*Deferred/then/l/<",
                "line": "2",
                "column": "30549",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "c",
                "line": "2",
                "column": "28327",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fireWith",
                "line": "2",
                "column": "29072",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fire",
                "line": "2",
                "column": "29108",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "c",
                "line": "2",
                "column": "28327",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fireWith",
                "line": "2",
                "column": "29072",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "ready",
                "line": "2",
                "column": "32045",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "B",
                "line": "2",
                "column": "31824",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "EventListener.handleEvent*",
                "line": "2",
                "column": "32193",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "?",
                "line": "2",
                "column": "220",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "?",
                "line": "2",
                "column": "225",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "uri": "index.php?route=%2Ftable%2Fsql"
    }
}
```

### PR DESCRIPTION
**Pull request by ping-yee**
### Description

Please describe your pull request.

Fixes #17329 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: js/src/sql.js [hunk 1]
```diff
@@ -47,10 +47,20 @@ Sql.urlEncode = function (str) {
...
+                Cookies.set(key, query);
+            }
+        } catch (e) {
+            console.error(e);
+            Functions.ajaxShowMessage(
+                '<div class="alert alert-danger" role="alert">' +
+                e +
+                '</div>',
+                false
+            );
```
Comment (MauricioFauth) [inline js/src/sql.js:63]: I'm not sure if showing the error is needed is this case. Not like this, at least.

Comment (ping-yee) [reply js/src/sql.js:63]: @MauricioFauth Thanks for the review.

I made the change based on the issue’s expected output, or do you think try-catch is enough?

Comment (ping-yee) [reply js/src/sql.js]: @MauricioFauth I have changed the error handling, review please.

**Review by MauricioFauth — APPROVED** [review]
