### PR TITLE
Fix #19627 - Reset UNSIGNED attribute when changing to non-numeric co…

### LINKED ISSUE #19627: Unsigned varchar Error
### Describe the bug

Changing an unsigned integer attribute to varchar produces bad SQL "Change attribute attribute varchar(32) unsinged NULL DEFAULT NULL"

### To Reproduce

CREATE TABLE mytable(
myattribute integer unsigned NULL DEFAULT NULL
)

Goto Structure
Klick Change myattribute

make the integer into a varchar (32)

klick save

"Change attribute attribute varchar(32) unsinged NULL DEFAULT NULL"

SQL ERROR

### Expected behavior

Good SQL

"Change attribute attribute varchar(32)  NULL DEFAULT NULL"

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: Ubuntu 2204
- Web server: Apache
- Database version: Aurora 8
- PHP version: 8.1
Version information: 5.1.4deb2~bpo11+1

### Client configuration

- Browser:
- Operating system:

### Additional context

Add any other context about the bug here.

### PR DESCRIPTION
**Pull request by predictor2718**
## Summary                                                                                                          
  - When changing a column from INT UNSIGNED to VARCHAR, the UNSIGNED attribute stayed selected, producing invalid SQL
  - Added two fixes:                                                                                                  
    1. Automatically reset the attribute dropdown when the type changes to a non-numeric type                         
    2. Validate on submit that UNSIGNED/ZEROFILL is not used with non-numeric types, showing an error message         
                                                                                                                      
  ## How to verify                                                                                                    
  1. Create table with `INTEGER UNSIGNED` column                                                                      
  2. Change → switch type to VARCHAR(32) → attribute dropdown resets automatically                                    
  3. Manually re-select UNSIGNED → click Save → validation error appears                                              
                                                                                                                      
  Fixes #19627

### CODE REVIEW

File: resources/js/modules/functions.ts [hunk 1]
```diff
@@ -731,6 +731,32 @@ export function checkTableEditForm (theForm, fieldsCnt) {
             }
         }
 
+        // Check for UNSIGNED/ZEROFILL on non-numeric types
+        var $typeField = $('#field_' + i + '_2');
+        var $attrField = $typeField.closest('tr').find('select[name^="field_attribute"]');
+        var typeVal = String($typeField.val() || '').toUpperCase();
+        var attrVal = String($attrField.val() || '').toUpperCase();
```
Comment (MauricioFauth) [inline resources/js/modules/functions.ts]:
```suggestion
        const $typeField = $('#field_' + i + '_2');
        const $attrField = $typeField.closest('tr').find('select[name^="field_attribute"]');
        const typeVal = String($typeField.val() || '').toUpperCase();
        const attrVal = String($attrField.val() || '').toUpperCase();
```

File: resources/js/modules/functions.ts [hunk 2]
```diff
@@ -731,6 +731,32 @@ export function checkTableEditForm (theForm, fieldsCnt) {
...
+        if (attrVal === 'UNSIGNED' || attrVal === 'UNSIGNED ZEROFILL' || attrVal === 'ZEROFILL') {
+            var numTypes = [
```
Comment (MauricioFauth) [inline resources/js/modules/functions.ts]:
```suggestion
            const numTypes = [
```

File: resources/js/modules/functions.ts [hunk 3]
```diff
@@ -1570,6 +1596,37 @@ function showNoticeForEnum (selectElement) {
...
  * Hides/shows a warning message when LENGTH is used with inappropriate integer type
  */
+/**
+ * Reset the attribute dropdown when the column type is changed
+ * to a non-numeric type. Attributes like UNSIGNED and ZEROFILL
+ * are only valid for numeric types.
+ */
+function resetAttributeForNonNumericType ($typeSelector) {
+    var type = String($typeSelector.val() || '').toUpperCase();
+    var numericTypes = [
```
Comment (MauricioFauth) [inline resources/js/modules/functions.ts]:
```suggestion
    const type = String($typeSelector.val() || '').toUpperCase();
    const numericTypes = [
```

File: resources/js/modules/functions.ts [hunk 4]
```diff
@@ -1570,6 +1596,37 @@ function showNoticeForEnum (selectElement) {
...
+        'FLOAT',
+        'DOUBLE',
+        'DECIMAL',
+    ];
+
+    if (numericTypes.indexOf(type) === -1) {
+        // Find the attribute select in the same row
+        var $row = $typeSelector.closest('tr');
+        var $attrSelect = $row.find('select[name^="field_attribute"]');
+        var currentAttr = String($attrSelect.val() || '').toUpperCase();
```
Comment (MauricioFauth) [inline resources/js/modules/functions.ts]:
```suggestion
        const $row = $typeSelector.closest('tr');
        const $attrSelect = $row.find('select[name^="field_attribute"]');
        const currentAttr = String($attrSelect.val() || '').toUpperCase();
```

File: resources/js/modules/functions.ts [hunk 5]
```diff
@@ -731,6 +731,32 @@ export function checkTableEditForm (theForm, fieldsCnt) {
...
+                'BIGINT',
+                'FLOAT',
+                'DOUBLE',
+                'DECIMAL',
+            ];
+            elm3 = $('#field_' + i + '_1');
+            if (numTypes.indexOf(typeVal) === -1 && elm3.val() !== '') {
+                $attrField.select();
+                alert(typeVal + ' ' + window.Messages.strInvalidAttribute);
+                $attrField.focus();
```
Comment (MauricioFauth) [inline resources/js/modules/functions.ts]:
```suggestion
                $attrField.trigger('select');
                ajaxShowMessage(typeVal + ' ' + window.Messages.strInvalidAttribute, null, 'error');
                $attrField.trigger('focus');
```

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
Thank you!

**Review by MauricioFauth — APPROVED** [review]
Thank you!
