### PR TITLE
Fixes Import Fail

### LINKED ISSUE #14072: Import fails with error code 200
I'm using git master and trying to import a file (sql and csv files). After I press "Go", I get a red popup on the page:

```
Error in processing request
Error code: 200
Error text: OK (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.
```

This is in my Apache error log:
```
[Fri Mar 02 06:53:22.702997 2018] [:error] [pid 13114] [client 192.168.56.1:53209] PHP Fatal error:  Call to undefined function PhpMyAdmin\\Plugins\\Import\\Upload\\uploadprogress_get_info() in /var/www/pma-dev/fork/libraries/classes/Plugins/Import/Upload/UploadProgress.php on line 63
[Fri Mar 02 06:53:22.758920 2018] [:error] [pid 13114] [client 192.168.56.1:53209] PHP Stack trace:
[Fri Mar 02 06:53:22.844225 2018] [:error] [pid 13114] [client 192.168.56.1:53209] PHP   1. {main}() /var/www/pma-dev/fork/import_status.php:0
[Fri Mar 02 06:53:22.844275 2018] [:error] [pid 13114] [client 192.168.56.1:53209] PHP   2. PhpMyAdmin\\Display\\ImportAjax::status() /var/www/pma-dev/fork/import_status.php:120
[Fri Mar 02 06:53:22.844303 2018] [:error] [pid 13114] [client 192.168.56.1:53209] PHP   3. PhpMyAdmin\\Plugins\\Import\\Upload\\UploadProgress::getUploadStatus() /var/www/pma-dev/fork/libraries/classes/Display/ImportAjax.php:131
```

### PR DESCRIPTION
**Pull request by shucon**
Fixes: https://github.com/phpmyadmin/phpmyadmin/issues/14072

Signed-off-by: Saksham Gupta <shucon01@gmail.com>

Before submitting pull request, please check that every commit:

- [x] Has proper Signed-Off-By
- [x] Has commit message which describes it
- [x] Is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any new functionality is covered by tests

### CODE REVIEW

**Comment by shucon** [comment]
Travis CI build failed and seems to be somewhat related, any ideas?

File: libraries/classes/Plugins/Import/Upload/UploadProgress.php [hunk 1]
```diff
@@ -60,7 +60,11 @@ public static function getUploadStatus($id)
             return $ret;
         }
 
-        $status = uploadprogress_get_info($id);
+        if (function_exists("uploadprogress_get_info")) {
+            $status = uploadprogress_get_info($id);
+        } else {
+            $status = getallheaders();
```
Comment (mauriciofauth) [inline libraries/classes/Plugins/Import/Upload/UploadProgress.php]: Hi @shucon. Why did you choose getallheaders?

Comment (shucon) [reply libraries/classes/Plugins/Import/Upload/UploadProgress.php]: Line 59 used ImportAjax::progressCheck() , which checked whether getallheaders or uploadprogress_get_info function exists. So getallheaders was important as it was getting checked.

Comment (mauriciofauth) [reply libraries/classes/Plugins/Import/Upload/UploadProgress.php]: But the return of `getallheaders()` does not make much sense to the code just below it.

Maybe the problem is in `ImportAjax::progressCheck()`.
https://github.com/phpmyadmin/phpmyadmin/blob/b8e7e9fa3bd3707ffdb09f1bcfdc37cccf00c4fa/libraries/classes/Display/ImportAjax.php#L91-L95

I think it should be an `&&` instead of an `||`. What do you think?

**Comment by shucon** [comment]
I read a bit about getallheaders before using it here and I was convinced that both functions are similar and upload_progress_get_info is not used anymore.

**Comment by shucon** [comment]
Also changing or to and would render progress bar useless for most of the cases.

**Comment by shucon** [comment]
Okay, I think you are right , I'll check it once when I get time.

File: libraries/classes/Plugins/Import/Upload/UploadProgress.php (hunk 1 above)
Comment (shucon) [reply libraries/classes/Plugins/Import/Upload/UploadProgress.php]: Yes, you were correct. Sorry for the confusion.

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!
