### PR TITLE
Fix linter for sql query box with multiple statements

### LINKED ISSUE #18389: Analyzed statement's error not shown immediately
### Describe the bug

Analyzed statement's error is not shown immediately. It only shows up when there is an error two consecutive times.

### To Reproduce

1. Go to  SQL
2. Type single letter or paste an invalid statement
3. Observe no error being shown
4. Type one more letter
5. Now an error is displayed

### Expected behavior

It should display error as soon as the statement is not valid

### Screenshots

image
image

### Server configuration

- phpMyAdmin version: 6  514d536 

### Client configuration

- Browser: Firefox 112.0.2
- Operating system: Linux

### LINKED ISSUE #18487: Unexpected token. (near ;)
### Describe the bug

Something has changed in the past weeks that is causing a `Unexpected token. (near ;)` error on phpMyAdmin 5.2.2-dev and 6.0.0-dev for every query that is edited and has `;` at the end, no matter what you type.

Strange, it doesn't happen on the demo server.

### To Reproduce

1. Go to https://www.phpmyadmin.net/downloads/
2. Download phpMyAdmin 5.2+snapshot
3. Edit a query with `;` at the end

### Expected behavior

No `Unexpected token. (near ;)` error should be given.

### Screenshots

https://github.com/phpmyadmin/sql-parser/assets/25424343/bcd882ba-226b-44b3-ab5e-fbf855bef697

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### LINKED ISSUE #18511: Parser error shown with multiple statements in query box
### Describe the bug

An error is shown when multiple SQL statements are entered in the query box.

### To Reproduce

1. Go to the query box 
2. Input 
```sql
SELECT 1; SELECT 1; 
```
3. See error

### Expected behavior

No error shown.

### Screenshots
image

### Server configuration

- phpMyAdmin version: 5.2 and 6.0

### PR DESCRIPTION
**Pull request by MoonE**
### Description

Only change the delimiter for routine/event/trigger editor. The query editor should use the default delimiter.

Fixes #18389, fixes  #18487, fixes #18511,

### CODE REVIEW

File: libraries/classes/Controllers/LintController.php [hunk 1]
```diff
@@ -48,14 +48,14 @@ public function __invoke(): void
...
 
             if (! empty($options['routineEditor'])) {
-                $sqlQuery = 'CREATE PROCEDURE `a`() ' . $sqlQuery;
+                $sqlQuery = "DELIMITER $$\nCREATE PROCEDURE `a`() " . $sqlQuery . '$$';
             } elseif (! empty($options['triggerEditor'])) {
-                $sqlQuery = 'CREATE TRIGGER `a` AFTER INSERT ON `b` FOR EACH ROW ' . $sqlQuery;
+                $sqlQuery = "DELIMITER $$\nCREATE TRIGGER `a` AFTER INSERT ON `b` FOR EACH ROW " . $sqlQuery . '$$';
             } elseif (! empty($options['eventEditor'])) {
-                $sqlQuery = 'CREATE EVENT `a` ON SCHEDULE EVERY MINUTE DO ' . $sqlQuery;
+                $sqlQuery = "DELIMITER $$\nCREATE EVENT `a` ON SCHEDULE EVERY MINUTE DO " . $sqlQuery . '$$';
```
Comment (kamil-tekiela) [inline libraries/classes/Controllers/LintController.php:55]: Do we need the `$$` at the end?

Comment (williamdes) [reply libraries/classes/Controllers/LintController.php:55]: Yes, multi line content would break otherwise

**Review by williamdes — APPROVED** [review]
Awesome, thank you

File: libraries/classes/Controllers/LintController.php (hunk 1 above)
Comment (MoonE) [reply libraries/classes/Controllers/LintController.php:55]: I don't think it is necessary, In these cases only one statement will be in the editor and a delimiter at the very end is not required.

Comment (kamil-tekiela) [reply libraries/classes/Controllers/LintController.php:55]: I'm not sure how multiline content would break. I am testing it right now. A delimiter is supposed to delimit two queries apart. If there is no other query appended to it then the delimiter should is redundant.

Comment (kamil-tekiela) [reply libraries/classes/Controllers/LintController.php:55]: I can't get it to break and it seems to work fine without it. The reported issue is also gone. I think we should merge it without the delimiter at the end. It was needed before because the delimiter was reset back to `;` but this is also unnecessary.

**Comment by MoonE** [comment]
The second commit fixes #18389, the problem was that the annotations were generated for non-existing lines as the linted sql was not the same as the sql in the editor.

With this fixed, linting routines/events/triggers **never** (except when the sql length exceeds 10000 characters) produces lint results as the body of these statements is not analyzed. It is simply skipped:

Routine: https://github.com/phpmyadmin/sql-parser/blob/011fa18a4e55591fac6545a821921dd1d61c6984/src/Statements/CreateStatement.php#L719-L726
Trigger: https://github.com/phpmyadmin/sql-parser/blob/011fa18a4e55591fac6545a821921dd1d61c6984/src/Statements/CreateStatement.php#L786-L793
Event: https://github.com/phpmyadmin/sql-parser/blob/011fa18a4e55591fac6545a821921dd1d61c6984/src/Statements/CreateStatement.php#L795-L802

So I'm not sure what the reason was for adding the sql prefix in the first place. Wouldn't it work better without it? Parsing the body of these statements as normal sql.

File: libraries/classes/Controllers/LintController.php [hunk 2]
```diff
@@ -10,52 +10,59 @@
...
+        $prefix = is_string($editorType) ? self::EDITOR_SQL_PREFIX[$editorType] ?? '' : '';
 
-        // Disabling standard response.
-        $this->response->disable();
-
-        Core::headerJSON();
+        $lints = Linter::lint($prefix . $sqlQuery);
+        if ($prefix !== '') {
+            // Adjust positions to account for prefix
+            foreach ($lints as &$lint) {
```
Comment (kamil-tekiela) [inline libraries/classes/Controllers/LintController.php:50]: Stylistic nit, but I would prefer `foreach ($lints as $key => $lint) {` and then `$lints[$key] = `

**Comment by kamil-tekiela** [comment]
> So I'm not sure what the reason was for adding the sql prefix in the first place. Wouldn't it work better without it? Parsing the body of these statements as normal sql.

I have asked myself this question this morning too. I suppose there was a scenario which made this fix necessary. It seems to be related to this fix https://github.com/phpmyadmin/sql-parser/pull/438

File: libraries/classes/Controllers/LintController.php (hunk 1 above)
Comment (williamdes) [reply libraries/classes/Controllers/LintController.php]: Can you state versions for the record? "needed before"

**Comment by williamdes** [comment]
> > So I'm not sure what the reason was for adding the sql prefix in the first place. Wouldn't it work better without it? Parsing the body of these statements as normal sql.
> 
> I have asked myself this question this morning too. I suppose there was a scenario which made this fix necessary. It seems to be related to this fix [phpmyadmin/sql-parser#438](https://github.com/phpmyadmin/sql-parser/pull/438)

That's correct
The parser made changes required in this repo

**Comment by williamdes** [comment]
> So I'm not sure what the reason was for adding the sql prefix in the first place. Wouldn't it work better without it? Parsing the body of these statements as normal sql.

@Tithugues

**Review by williamdes — APPROVED** [review]
This looks good

**Review by kamil-tekiela — APPROVED** [review]

**Review by williamdes — APPROVED** [review]
