### PR TITLE
Fix #18543 - Unsupported operand types: string - float

### LINKED ISSUE #18543: TypeError: Unsupported operand types: string - float
### Describe the bug

TypeError: Unsupported operand types: string - float. On 6.0.0-dev can't be reproduced, because all values are converted to float.

### To Reproduce

1. https://demo.phpmyadmin.net/QA_5_2/index.php?route=/sql&db=opengis&table=world_borders&server=1
2. Click on `Edit`
3. Click on `Edit/Insert`
4. Enter a letter instead of a float value
5. See error

### Expected behavior

No error should be given.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/15176f03-a932-490f-9892-927b8190e3ba

### Server configuration

- phpMyAdmin version: 5.2.2-dev

### Additional context

https://github.com/phpmyadmin/phpmyadmin/blob/4574eb71d462c4331e3e5438213eec7a8e2365ac/libraries/classes/Gis/GisGeometry.php#L245-L247

### PR DESCRIPTION
**Pull request by liviuconcioiu**
### Description

Fixes #18543

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

File: libraries/classes/Gis/GisGeometry.php [hunk 1]
```diff
@@ -242,9 +242,9 @@ protected function extractPoints($point_set, $scale_data, $linear = false): arra
 
             if (isset($coordinates[0], $coordinates[1]) && trim($coordinates[0]) != '' && trim($coordinates[1]) != '') {
                 if ($scale_data != null) {
-                    $x = ($coordinates[0] - $scale_data['x']) * $scale_data['scale'];
-                    $y = $scale_data['height']
-                        - ($coordinates[1] - $scale_data['y']) * $scale_data['scale'];
+                    $x = floatval((floatval(trim($coordinates[0])) - $scale_data['x']) * $scale_data['scale']);
```
Comment (williamdes) [inline libraries/classes/Gis/GisGeometry.php:245]: could this be extracted to variables?
it's a bit messy

**Review by MauricioFauth — APPROVED** [review]

File: libraries/classes/Gis/GisGeometry.php [hunk 2]
```diff
@@ -241,13 +241,12 @@ protected function extractPoints($point_set, $scale_data, $linear = false): arra
...
+
                 if ($scale_data != null) {
-                    $x = ($coordinates[0] - $scale_data['x']) * $scale_data['scale'];
-                    $y = $scale_data['height']
-                        - ($coordinates[1] - $scale_data['y']) * $scale_data['scale'];
-                } else {
-                    $x = floatval(trim($coordinates[0]));
-                    $y = floatval(trim($coordinates[1]));
+                    $x = floatval(($x - $scale_data['x']) * $scale_data['scale']);
+                    $y = floatval($scale_data['height'] - ($y - $scale_data['y']) * $scale_data['scale']);
```
Comment (williamdes) [inline libraries/classes/Gis/GisGeometry.php:249]: the floatval should be around the scale data and not the entire operation
I am not sure but I'd say the entire operation is always a float if one of operands is a float

Comment (liviuconcioiu) [reply libraries/classes/Gis/GisGeometry.php:249]: > the floatval should be around the scale data and not the entire operation I am not sure but I'd say the entire operation is always a float if one of operands is a float

On 6.0.0-dev is on the entire operation.

https://github.com/phpmyadmin/phpmyadmin/blob/c3c729da0b7da5e09bb4fbc33f21d6d5a1305b48/libraries/classes/Gis/GisGeometry.php#L216-L223
