### PR TITLE
Fix #14412 - AuthenticationSignon.php's showFailure function does not consider SignonCookieParams

### LINKED ISSUE #14412: AuthenticationSignon.php's showFailure function does not consider SignonCookieParams
### Steps to reproduce
1. Use "signon" mode in a way that an error occurs on phpMyAdmin side (ex: set incorrect mysql server name) so `showFailure()` is called (In `libraries/classes/Plugins/Auth/AuthenticationSignon.php`)

### Expected behaviour
`showFailure` sets a session parameter called "`PMA_single_signon_error_message`" so the external login script can have access to the error message in case some error happens on phpMyAdmin side.

### Actual behaviour
`showFailure` forgets to consider `SignonCookieParams` and call `session_set_cookie_params` before calling `session_start`. In corner cases, this creates a new session and cookie, so the external script will not have access to the error message.

### PR DESCRIPTION
**Pull request by williamdes**
Fixes: #14412
Call `session_set_cookie_params` to set the cookie params

### CODE REVIEW

**Comment by williamdes** [comment]
Hi @nhatier can you please review this PR ?

**Comment by williamdes** [comment]
@mauriciofauth @ibennetch can you please review this PR ?

File: libraries/classes/Plugins/Auth/AuthenticationSignon.php [hunk 1]
```diff
@@ -220,6 +220,15 @@ public function showFailure($failure)
                 session_write_close();
 
                 /* Load single signon session */
+                /* Session cookie params */
+                $sessionCookieParams = (array) $GLOBALS['cfg']['Server']['SignonCookieParams'];
+                session_set_cookie_params(
```
Comment (mauriciofauth) [inline libraries/classes/Plugins/Auth/AuthenticationSignon.php]: You could check if PHP > 7.3 to use the PHP 7.3 signature of `session_set_cookie_params`.

File: libraries/classes/Plugins/Auth/AuthenticationSignon.php [hunk 2]
```diff
@@ -220,6 +220,15 @@ public function showFailure($failure)
...
+                    $sessionCookieParams['lifetime'],
```
Comment (mauriciofauth) [inline libraries/classes/Plugins/Auth/AuthenticationSignon.php]: I think it would be interesting to check if the key exists and also add a type cast.

File: libraries/classes/Plugins/Auth/AuthenticationSignon.php (hunk 1 above)
Comment (williamdes) [reply libraries/classes/Plugins/Auth/AuthenticationSignon.php]: I copied the line https://github.com/phpmyadmin/phpmyadmin/blob/9de453fa314863b8f728e80addfe10411e30324d/libraries/classes/Plugins/Auth/AuthenticationSignon.php#L118 

Do I fix the other occurrences (adding a if statement) ?

Comment (mauriciofauth) [reply libraries/classes/Plugins/Auth/AuthenticationSignon.php]: The PHP 7.3 signature adds support for the SameSite cookie attribute. I think it will be good to add that.

Comment (williamdes) [reply libraries/classes/Plugins/Auth/AuthenticationSignon.php]: Okay, will do that tomorrow :)

Comment (mauriciofauth) [reply libraries/classes/Plugins/Auth/AuthenticationSignon.php]: But that change is not related to the issue. Maybe open another PR for this changes?

Comment (williamdes) [reply libraries/classes/Plugins/Auth/AuthenticationSignon.php]: Yes, good idea

File: libraries/classes/Plugins/Auth/AuthenticationSignon.php (hunk 2 above)
Comment (williamdes) [reply libraries/classes/Plugins/Auth/AuthenticationSignon.php]: Yes, in an other PR :)

**Review by MauricioFauth — APPROVED** [review]

**Review by nhatier — APPROVED** [review]
The changes work for me.

**Comment by williamdes** [comment]
@mauriciofauth I made the changes you wanted, can you re-review please ?

File: libraries/classes/Plugins/Auth/AuthenticationSignon.php (hunk 2 above)
Comment (williamdes) [reply libraries/classes/Plugins/Auth/AuthenticationSignon.php]: I move this to a function because checking that the key exists already existed in the code

File: libraries/classes/Plugins/Auth/AuthenticationSignon.php (hunk 1 above)
Comment (williamdes) [reply libraries/classes/Plugins/Auth/AuthenticationSignon.php]: Done !

**Review by MauricioFauth — APPROVED** [review]
Very good!
