### PR TITLE
Fix #19073 - Both replicated and not replicated icon shown

### LINKED ISSUE #19073: Both replicated and not replicated icon shown
### Describe the bug

When connecting to a replica mysql server which has tables that are no longer replicated, two icons are shown.
One with tooltip `Not replicated` and the other with tooltip `Replicated`, which is a bit confusing.

https://github.com/phpmyadmin/phpmyadmin/blob/8e4443b17bfe629d01da14cc3e2a0cace76c9106/resources/templates/database/structure/structure_table_row.twig#L15-L20

### To Reproduce

1. Go to Database Structure page on a replica server that has tables that are no longer replicated.
2. See error

### Expected behavior

I'd say in this case it would make sense to show only the `Not replicated` icon.

### Additional Info

`($nbServReplicaDoDb == 0 && $nbServReplicaIgnoreDb == 0)` is true here

https://github.com/phpmyadmin/phpmyadmin/blob/8e4443b17bfe629d01da14cc3e2a0cace76c9106/src/Controllers/Database/StructureController.php#L596-L608

with this `json_encode($replicaInfo)`:
```json
{
    "Do_DB": [],
    "Do_Table": [],
    "Ignore_DB": [],
    "Ignore_Table": [
         "[some unrelated tables]"
    ],
    "status": true,
    "Wild_Do_Table": [],
    "Wild_Ignore_Table": [
        "phpmyadmin.%"
    ]
}
```

### Screenshots
image

### Server configuration

- Database version: MySQl 5.7.44
- phpMyAdmin version: 5.2.1 / master

### PR DESCRIPTION
**Pull request by ping-yee**
### Description

Please describe your pull request.

Fixes #19073 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Some screenshots would help, but the diff is clean
Thank you for your contributions!

**Comment by M393** [comment]
Looks good to me.
image

File: libraries/classes/Controllers/Database/StructureController.php [hunk 1]
```diff
@@ -605,16 +605,19 @@ protected function getReplicationStatus($replicaInfo, string $table): array
...
-                || $this->hasTable($replicaInfo['Wild_Do_Table'], $table);
-
             $searchDb = array_search($this->db, $replicaInfo['Ignore_DB']);
             $searchTable = array_search($table, $replicaInfo['Ignore_Table']);
             $ignored = (is_string($searchTable) && strlen($searchTable) > 0)
                 || (is_string($searchDb) && strlen($searchDb) > 0)
                 || $this->hasTable($replicaInfo['Wild_Ignore_Table'], $table);
+
+            // Only set do = true if table is not ignored
+            if (!$ignored) {
```
Comment (M393) [inline libraries/classes/Controllers/Database/StructureController.php]:
```suggestion
            if (! $ignored) {
```

**Comment by ping-yee** [comment]
@M393 Thanks for your testing!

**Comment by ping-yee** [comment]
@williamdes Thanks for your review!

File: libraries/classes/Controllers/Database/StructureController.php (hunk 1 above)
Comment (ping-yee) [reply libraries/classes/Controllers/Database/StructureController.php]: Already fixed.

**Review by MauricioFauth — APPROVED** [review]
