### PR TITLE
Fix #19504 - set default value for the innodb.

### LINKED ISSUE #19504: Advisor rules are throwing some errors.
### Describe the bug

If MySQL/MariaDB is started with `skip-innodb`, Advisory rules are throwing some errors.

```
Failed evaluating precondition for rule 'InnoDB log size'. Error when evaluating: Variable "innodb_buffer_pool_size" is not valid around position 1 for expression `innodb_buffer_pool_size > 0 && ! (IS_MARIADB && PMA_MYSQL_INT_VERSION > 100500)`.
Failed evaluating precondition for rule 'InnoDB log size'. Error when evaluating: Variable "innodb_buffer_pool_size" is not valid around position 1 for expression `innodb_buffer_pool_size > 0 && IS_MARIADB && PMA_MYSQL_INT_VERSION > 100500`.
Failed evaluating precondition for rule 'Max InnoDB log size'. Error when evaluating: Variable "innodb_buffer_pool_size" is not valid around position 1 for expression `innodb_buffer_pool_size > 0 && innodb_log_file_size / innodb_buffer_pool_size * 100 < 30`.
Failed calculating value for rule 'InnoDB buffer pool size'. Error when evaluating: Variable "innodb_buffer_pool_size" is not valid around position 1 for expression `innodb_buffer_pool_size / system_memory * 100`.
```

### To Reproduce

1. Start MySQL/MariaDB with `skip-innodb`.
2. Go to Status > Advisor
3. See error

### Expected behavior

If InnoDB is not available, rules should be ignored.

### Screenshots

errors

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### PR DESCRIPTION
**Pull request by ping-yee**
### Description

Please describe your pull request.

Fixes #19504 

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: libraries/classes/Advisor.php [hunk 1]
```diff
@@ -396,7 +396,22 @@ private function replaceVariable(array $matches): string
...
+        }
+
+        if (! isset($variables['innodb_log_file_size'])) {
+            $variables['innodb_log_file_size'] = 0;
+        }
+
+        if (! isset($variables['innodb_log_files_in_group'])) {
+            $variables['innodb_log_files_in_group'] = 0;
+        }
+
```
Comment (liviuconcioiu) [inline libraries/classes/Advisor.php:413]:
```suggestion

```

Comment (liviuconcioiu) [reply libraries/classes/Advisor.php:413]: @ping-yee you have some spaces on line 413. I tested the PR and works, no more errors.

**Review by MauricioFauth — APPROVED** [review]
