### PR TITLE
FIXES #17414 - Adjusting export object in PluginExport to export databases with comp…

### LINKED ISSUE #17414: ZIP file downloads uncompress to an empty file
As I first noticed at https://github.com/phpmyadmin/phpmyadmin/issues/17413#issuecomment-1047905279, zip file exports are properly-formed ZIP files, but the uncompressed file is an empty SQL file.

To reproduce:

1. Go to any database
2. Pick the Export tab
3. Select an SQL file with ZIP compression (other defaults are fine)
4. Uncompress the resulting download

Tested with Chrome and Firefox using a relatively current master. The problem did not occur with RELEASE_5_1_3.

Git bisect says that ba35901594676dfe032dc6869db52845c1f03e85 is the first bad commit.

### PR DESCRIPTION
**Pull request by pokemaobr**
…ress

Signed-off-by: Rodrigo Pokemaobr <contato@pokemaobr.dev>

### Description

The export object was regenerated in ExportPlugin then causes empty content in buffer and compressed files empty.

Fixes #17414  

Before submitting pull request, please review the following checklist:

- [ ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### CODE REVIEW

**Review by MauricioFauth — CHANGES_REQUESTED** [review]
Hi @pokemaobr. Thanks for your contribution.

You should fix the PHPUnit tests before we can merge your pull request.
https://github.com/phpmyadmin/phpmyadmin/runs/6136576578?check_suite_focus=true#step:8:66

You should also fix the errors reported by Psalm.
https://github.com/phpmyadmin/phpmyadmin/runs/6136576294?check_suite_focus=true

File: libraries/classes/Plugins/ExportPlugin.php [hunk 1]
```diff
@@ -39,13 +39,14 @@ abstract class ExportPlugin implements Plugin
     /** @var Transformations */
     protected $transformations;
 
+    /**
+     * @psalm-supress InvalidArrayOffset, MixedAssignment, MixedMethodCall
```
Comment (mauriciofauth) [inline libraries/classes/Plugins/ExportPlugin.php:43]:
```suggestion
     * @psalm-suppress InvalidArrayOffset, MixedAssignment, MixedMethodCall
```

**Review by MauricioFauth — CHANGES_REQUESTED** [review]

**Review by MauricioFauth — APPROVED** [review]

**Comment by mauriciofauth** [comment]
Merged, thanks for your contribution!
