### PR TITLE
Fixes #15854: Designer Fullscreen Issues.

### LINKED ISSUE #15854: Designer full screen issues (Menu item toggling and black borders)
### Describe the bug

When switching to fullscreen on the designer, 

- Black borders appears on the canvas and the canvas resizes when moving tables around.
- Pressing ESC key to exit full screen in the Designer messes up the menu toggle buttons.

### To Reproduce

1. Go to Designer
2. Click on View Fullscreen in the menu
3. You can see the black borders. Move the table into the black screen and the white canvas resizes.
4. Press ESC Key to exit full screen
5. The menu item for toggle fullscreen is not toggled correctly.

### Expected behavior

- Full screen white canvas.
- Proper icon toggling on exiting full screen by pressing ESC Key

### Server configuration

- Operating system: phpMyAdmin demo - MySQL (192.168.30.23 via TCP/IP
- Web server: nginx/1.10.3
- Database version: 8.0.18 - MySQL Community Server - GP
- PHP version: 7.4.0
- phpMyAdmin version: 5.0.1

### Client configuration

- Browser: Google Chrome
- Operating system: macOS Catalina 10.15.2

### PR DESCRIPTION
**Pull request by rabeehrz**
### Description

Fixes #15854

- Removes black border on fullscreen canvas by setting the width and height to 100 viewports.
- Add the functionality to change menu icon on exiting full screen mode by pressing ESC.

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: js/designer/move.js [hunk 1]
```diff
@@ -500,10 +507,11 @@ DesignerMove.clear = function () {
 DesignerMove.rect = function (x1, y1, w, h, color) {
     var ctx = document.getElementById('canvas').getContext('2d');
     ctx.fillStyle = color;
-    ctx.fillRect(x1, y1, w, h);
+    ctx.fillRect(x1, y1, w, h)
```
Comment (williamdes) [inline js/designer/move.js]: can you revert this change ?
and the line added below ?

**Review by williamdes — APPROVED** [review]

**Comment by williamdes** [comment]
Code looks good, can you please squash the commits into one ?

**Comment by rabeehrz** [comment]
@williamdes Commits squashed.

File: js/designer/move.js [hunk 2]
```diff
@@ -24,17 +24,26 @@ AJAX.registerTeardown('designer/move.js', function () {
...
             $span.text($span.data('enter'));
             $img.attr('src', $img.data('enter'))
                 .attr('title', $span.data('enter'));
         }
+        if (!$content.fullScreen()) {
+            $img.attr('src', $img.data('enter'))
+            .attr('title', $span.data('enter'));
+            $span.text($span.data('enter'));
+            valueSent = 'off';
+            DesignerMove.saveValueInConfig('full_screen', valueSent);
```
Comment (williamdes) [inline js/designer/move.js]: why did you add this line :thinking:

Comment (rabeehrz) [reply js/designer/move.js]: When the designer full screen is exited via by hitting the Exit full screen button, the value is saved in config. So when the full screen exists via ESC button, I thought the same thing should be done. Do I need to remove this? 😅

Comment (williamdes) [reply js/designer/move.js]: Oh, no you can leave it, maybe add a comment to explain the issue ?

File: js/designer/move.js [hunk 3]
```diff
@@ -516,6 +528,7 @@ DesignerMove.toggleFullscreen = function () {
         $content
             .addClass('content_fullscreen')
             .css({ 'width': screen.width - 5, 'height': screen.height - 5 });
+        $('#osn_tab').css({ 'width': '100vw', 'height': '100vh' });
```
Comment (williamdes) [inline js/designer/move.js]: https://caniuse.com/#feat=mdn-api_css_vw
https://caniuse.com/#feat=mdn-api_css_vh

Can you find another way to do ?
And squash the commits ?

I would have loved to merge but the support is terrible for those units

**Comment by rabeehrz** [comment]
@williamdes I've switched from viewports to JS screen dimensions. Please review. :)

File: js/designer/move.js [hunk 4]
```diff
@@ -516,12 +531,18 @@ DesignerMove.toggleFullscreen = function () {
         $content
             .addClass('content_fullscreen')
             .css({ 'width': screen.width - 5, 'height': screen.height - 5 });
+        console.log(screen.width);
```
Comment (williamdes) [inline js/designer/move.js]: Needs to be removed ;)

**Review by williamdes — CHANGES_REQUESTED** [review]

**Review by williamdes — APPROVED** [review]
tested it and it works fine.

File: js/designer/move.js [hunk 5]
```diff
@@ -21,17 +21,33 @@ AJAX.registerTeardown('designer/move.js', function () {
...
                 .css({ 'width': 'auto', 'height': 'auto' });
-            var $img = $('#toggleFullscreen').find('img');
-            var $span = $img.siblings('span');
+
             $span.text($span.data('enter'));
             $img.attr('src', $img.data('enter'))
                 .attr('title', $span.data('enter'));
         }
+        if (!$content.fullScreen()) {
+            $content.removeClass('content_fullscreen')
```
Comment (williamdes) [inline js/designer/move.js]: @rabeehrz can hard reset to my commit 3dd8a075e91423e13bd75bd1b8b382c4208a962b and add a OR case so it reduces the code duplication ?

Comment (rabeehrz) [reply js/designer/move.js]: @williamdes Done! :)

**Comment by williamdes** [comment]
Merged, thank your for your contributions !
I added f887621ad999e8239cd8dcc1718317779003ccc2 that I forgot to add to the commit
