### PR TITLE
Fix #14502 - Triggered the on-change event on the input field to uncheck the "ignore" checkbox 

### LINKED ISSUE #14502: "Ignore" check box (in INSERT tab) does not uncheck when all the fields are edited through popup windows
### Steps to reproduce
1.  Create a table with let's say 2 columns with foreign key
2. In the related tables (those referred to by the keys), add many entries, so that it reaches the threshold of PhpMyAdmin where the < select > becomes a popup, for displaying the options.

### Expected behaviour
The "Ignore" checkbox should become unchecked for that entry, since fields are filled.

### Actual behaviour
The js listener does not understand that fields have been filled, and thus, the "Ignore" button is not set to the unchecked state!

### Server configuration
**phpMyAdmin version:** 4.8.3, 5.0.0-dev

### PR DESCRIPTION
**Pull request by anny21**
### Description
The "Ignore" checkbox doesn't uncheck when fields are filled using the pop up modal

Fixes: #14502

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Looks good, thank you !

File: js/src/sql.js [hunk 1]
```diff
@@ -937,6 +937,9 @@ Sql.browseForeignDialog = function ($thisA) {
             }
             // Set selected value as input value
             $input.val($(this).data('key'));
+            // Unchecks the Ignore checkbox for the current row
+            $input.trigger("change");
```
Comment (williamdes) [inline js/src/sql.js:941]: Tips: `yarn run js-lint --fix`

**Comment by williamdes** [comment]
I applied the js-lint fix and added one more commit to handle GIS modal on save un-check action
