### PR TITLE
Fixes #18557 - Drag & drop difference between Firefox & Chromium browsers

### LINKED ISSUE #18557: Drag and drop difference between Firefox and Chromium browsers
### Describe the bug

The drag and drop is activated in Chromium browsers, when an icon from phpMyAdmin is dragged accidentally. This doesn't happen on Firefox.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/
2. Drag the phpMyAdmin logo
3. See difference between Firefox and Chrome (it gets activated while it shouldn't)

### Expected behavior

Drag and drop should work like in Firefox - it doesn't get activated accidentally with icons from phpMyAdmin.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/859b67aa-9e93-4d4a-9e48-01b837ce3fbe

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### Client configuration

- Browser: Chrome

### PR DESCRIPTION
**Pull request by og-khushalpatel**
### Description

Fix the drag-and-drop import overlay being incorrectly activated on Chromium-based browsers (Chrome, Edge, Brave, Opera) when users drag internal page elements such as the phpMyAdmin logo, icons, or links. Firefox is not affected because it does not expose Files in `dataTransfer.types` for in-page drags.

#### Changes (single file: js/src/drag_drop_import.js)
**1. New `internalDomDrag` flag (property)**

Added a boolean property `internalDomDrag` to the `DragDropImport `object.
Tracks whether the current drag operation was initiated from within the page DOM (i.e., user dragged a page element, not an OS file).

**2. New `markInternalDrag(event)` method**

Bound to the dragstart event on document.
Since OS file drags never trigger `dragstart` on the page, this reliably distinguishes internal DOM drags from external file drags.

**3. New `clearInternalDrag()` method**

Resets `internalDomDrag` to `false`.
Bound to `dragend` and `drop` events to ensure the flag is always cleaned up.

**4. Rewritten `hasFiles(event)` method (core fix)**

The original one-liner:
```js
return !(typeof event.originalEvent.dataTransfer.types === 'undefined' ||
    $.inArray('Files', event.originalEvent.dataTransfer.types) < 0 ||
    $.inArray('application/x-moz-nativeimage', event.originalEvent.dataTransfer.types) >= 0);
```
was replaced with a multi-layered detection approach:

- **Internal DOM drag check**: If `internalDomDrag` is `true`, returns `false` immediately
- `**undefined**` **types guard**: Returns `false` when `dataTransfer.types` is undefined.
- **`Files` type presence**: Returns `false` if `Files` is not in the types list.
- **Firefox native image exclusion**: Returns `false` if `application/x-moz-nativeimage` is present (retained from original logic).
- **Chromium internal element heuristic (new)**: Returns `false` if `text/uri-list` or `text/html` are present — these accompany in-page element drags on Chromium but are absent when dragging real OS files.

**5. Updated `drop(event)` handler**

Added an early `hasFiles()` guard at the top of the `drop` handler to reject non-file drops cleanly.
Added `clearInternalDrag()` call at the end of the handler to reset state.

**6. New event listeners**
```js
$(document).on('dragstart', DragDropImport.markInternalDrag);
$(document).on('dragend drop', DragDropImport.clearInternalDrag);
```

Fixes #18557 

Before submitting pull request, please review the following checklist:

- [ X ] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [ X ] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [ X ] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [ X ] Every commit has a descriptive commit message.
- [ ] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [ ] Any new functionality is covered by tests.

### Demo

https://github.com/user-attachments/assets/ea258f1a-fbbc-4add-891c-cce2619e1642

### CODE REVIEW

**Comment by og-khushalpatel** [comment]
Hi @MauricioFauth , I’m following up on this PR in case it got buried. Please let me know if any changes are needed from my side. Thank you!

**Review by williamdes — APPROVED** [review]
This looks good
What do you thing @kamil-tekiela and @liviuconcioiu ?

**Comment by kamil-tekiela** [comment]
I'm not very good with JavaScript so I won't review the code but the change looks positive to me.

**Comment by liviuconcioiu** [comment]
Same here

File: js/src/drag_drop_import.js [hunk 1]
```diff
@@ -171,12 +201,37 @@ var DragDropImport = {
...
+        // Not a file drag at all
+        if ($.inArray('Files', types) < 0) {
+            return false;
+        }
+
+        // Firefox native image drag - exclude it
+        if ($.inArray('application/x-moz-nativeimage', types) >= 0) {
+            return false;
+        }
+
```
Comment (williamdes) [inline js/src/drag_drop_import.js:225]:
```suggestion

        // Firefox native file drag - allow it
        // "Firefox also adds a non-standard text item of type application/x-moz-file
        // containing the full path of the file on the user's file system. Unless within
        // privileged code (such as an extension), its value is the empty string."
        if ($.inArray('application/x-moz-file', types) !== -1) {
            return true;
        }
```
I added this to allow Mozilla Firefox file drag and drop
Documentation from MDN
