### PR TITLE
Fix #17398 - Fixing clicking on `JSON` columns triggers `update` query 

### LINKED ISSUE #17398: Clicking on JSON column types, triggers UPDATE query
### Describe the bug

When clicking on JSON column types, a UPDATE query is triggered. Also, the query generated contains `\n` and spaces.
`{\n    \"a\": [\n        [\n            12345,\n            12345\n        ]\n    ],\n    \"b\": true\n}` instead of `{"a": [[12345, 12345]], "b": true}`

Also, JSON columns that aren't _`NULL`_, have a `null` value when browsing table that is also present when exporting a table
`(1, NULL, 'null', NULL),` - I don't know if this is a bug or not.

### To Reproduce

1. Create a table with JSON column types
2. Insert a few rows
3. Click on a field

### Expected behavior

It should not trigger a UPDATE query.

### Screenshots

https://user-images.githubusercontent.com/25424343/154415730-533fbe62-3340-462d-aec5-6cfd2367c06a.mp4

https://user-images.githubusercontent.com/25424343/154416842-cd6bd0ee-ac55-487f-a071-c103c2c42d3f.mp4

### Server configuration

- phpMyAdmin version: 5.x

### PR DESCRIPTION
**Pull request by iifawzi**
### Description

Hi, This PR is fixing the two issues mentioned at #17398
1- An `update` query is executed when clicking on the `JSON` columns
2- The `JSON` columns values are saved with unneeded spaces and lines when updated

https://user-images.githubusercontent.com/46695441/208328428-ce2656bc-bd32-4536-9604-b9c37fc10482.mov

Fixes #17398

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

File: js/src/makegrid.js [hunk 1]
```diff
@@ -1274,7 +1274,12 @@ var makeGrid = function (t, enableResize, enableReorder, enableVisib, enableGrid
                             fieldsType.push('hex');
                         }
                         fieldsNull.push('');
-                        fields.push($thisField.data('value'));
+
+                        if ($thisField.attr('data-type') !== 'json') {
+                            fields.push($thisField.data('value'));
+                        } else {
+                            fields.push(JSON.stringify(JSON.parse($thisField.data('value'))));
```
Comment (williamdes) [inline js/src/makegrid.js:1281]: what if the user inputs a broken JSON string by mistake, I think it would create a JS error
Can you add some checks before sending an invalid value to `JSON.stringify(` ?

Comment (iifawzi) [reply js/src/makegrid.js:1281]: Yes, you're right, I will make sure to work on fixing this asap

Comment (williamdes) [reply js/src/makegrid.js:1281]: Thanks, if you can rebase that's cool too

File: js/src/functions.js [hunk 2]
```diff
@@ -3980,6 +3980,24 @@ Functions.getCellValue = function (td) {
...
+ *
+ * @param json the json input to be validated and stringified
+ * @param replacer An array of strings and numbers that acts as an approved list for selecting the object properties that will be stringified.
+ * @param space Adds indentation, white space, and line break characters to the return-value JSON text to make it easier to read.
+ * @return {string}
+ */
+Functions.stringifyJSON = function (json, replacer = null, space = 0) {
+    let stringifiedJSON = json;
+    try {
+        stringifiedJSON = JSON.stringify(JSON.parse(json), replacer, space);
```
Comment (williamdes) [inline js/src/functions.js:3994]:
```suggestion
        return JSON.stringify(JSON.parse(json), replacer, space);
```

File: js/src/functions.js [hunk 3]
```diff
@@ -3980,6 +3980,24 @@ Functions.getCellValue = function (td) {
...
+    } catch (e) {
+        // will be returned as it's
```
Comment (williamdes) [inline js/src/functions.js:3996]: catch can also return

By the way you can probably add a JS unit test for this jew function?
There is one example already

File: js/src/functions.js (hunk 2 above)
Comment (iifawzi) [reply js/src/functions.js]: Done

File: js/src/functions.js (hunk 3 above)
Comment (iifawzi) [reply js/src/functions.js]: didn't know that we could test js functions, thanks for pointing to this, done.

**Review by williamdes — APPROVED** [review]
💯
