### PR TITLE
Fix simulate query count

### LINKED ISSUE #18533: Simulate query matched rows wrong count
### Describe the bug

When simulating a UPDATE query, the matched rows count is wrong sometimes. This happens if the column contains NULL values.

The generated query for count is ```SELECT `b` FROM `test` WHERE `a` = '2' AND (`b` <> 'test')``` but it probably should be ```SELECT `b` FROM `test` WHERE `a` = '2' AND (`b` <> 'test' OR `b` IS NULL)```

### To Reproduce

1. Create table
```SQL
CREATE TABLE `test` (
  `id` int(10) UNSIGNED NOT NULL,
  `a` varchar(255) DEFAULT NULL,
  `b` text DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `test` (`id`, `a`, `b`) VALUES
(1, '1', 'test'),
(2, '1', NULL),
(3, '1', NULL),
(4, '1', NULL),
(5, '1', 'test'),
(6, '2', NULL),
(7, '2', NULL),
(8, '2', 'test'),
(9, '2', NULL),
(10, '2', 'test');

ALTER TABLE `test`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `test`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;
```
2. Go to SQL tab and simulate this query
```UPDATE `test` SET `b` = 'test' WHERE `a` = '2'```
3. See the count 0 which is wrong. It should be 3.

### Expected behavior

The count should be accurate.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/8c46380d-1ac3-471e-8e88-64ac4a168532

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### PR DESCRIPTION
**Pull request by MoonE**
Fixes #18533, closes #18536

### CODE REVIEW

**Comment by MauricioFauth** [comment]
@MoonE Could you please rebase the PR it?

**Review by MauricioFauth — APPROVED** [review]

File: libraries/classes/Import/SimulateDml.php [hunk 1]
```diff
@@ -122,33 +115,38 @@ private function getSimulatedDeleteQuery(Parser $parser, DeleteStatement $statem
...
+            ? ''
+            : ' ORDER BY ' . Query::getClause($statement, $parser->list, 'ORDER BY');
+        $limit = $statement->limit === null ? '' : ' LIMIT ' . Query::getClause($statement, $parser->list, 'LIMIT');
+
+        return 'SELECT COUNT(*)' .
+            ' FROM (SELECT ' . implode(',', $newValues) . ') AS `pma_new`' .
+            ' JOIN (' .
+            'SELECT ' . implode(', ', $oldValues) . ' FROM ' . $tableReferences[0] . $where . $order . $limit .
+            ') AS `pma_old`' .
+            ' WHERE NOT (' . implode(', ', $newColumns) . ') <=> (' . implode(', ', $oldColumns) . ')';
```
Comment (kamil-tekiela) [inline libraries/classes/Import/SimulateDml.php:150]: I'd love if there was some comment explaining how this works because I can't comprehend it myself. :)

Comment (MoonE) [reply libraries/classes/Import/SimulateDml.php:150]: `pma_new` selects the `set` values into a single row which is then joined with the current table as `pma_old`. No `ON` condition needed, as `pma_new` is always just a single row.
In the `WHERE` confition a tuple comparison is made that checks if the old data tuple is different to the new data tuple.
The outer select counts all rows that are different.

```sql
UPDATE `table_1` SET `id` = 1, `name` = 'asdf' WHERE `id` = 10
```

```sql
SELECT COUNT(*)
FROM (SELECT 1 AS `n0`, 'asdf' AS `n1`) AS `pma_new`
JOIN (SELECT `id` AS `o0`, `name` AS `o1` FROM `table_1` WHERE `id` = 1) AS `pma_old`
WHERE NOT (`n0`, `n1`) <=> (`o0`, `o1`)
```

Thinking about it ... this should be equivalent to this, placing the values directly in the `WHERE` condition:
```sql
SELECT COUNT(*)
FROM (SELECT `id` AS `o0`, `name` AS `o1` FROM `table_1` WHERE `id` = 1) AS `pma_old`
WHERE NOT (1, 'asdf') <=> (`o0`, `o1`)
```

Comment (liviuconcioiu) [reply libraries/classes/Import/SimulateDml.php:150]: @MoonE I'm not sure about `COUNT(*)`. Previously, when the number was clicked it would have shown the rows that will be updated, but now is only the count number.

Comment (MoonE) [reply libraries/classes/Import/SimulateDml.php:150]: The count is the number of updated/affected rows. The `pma_old` subquery will give the matched rows, and the where condition reduces this to  the affected rows

Comment (liviuconcioiu) [reply libraries/classes/Import/SimulateDml.php:150]: > The count is the number of updated/affected rows. The `pma_old` subquery will give the matched rows, and the where condition reduces this to the affected rows

Yeah, but when the number is clicked, previously the rows where shown, something like:

count

Comment (MoonE) [reply libraries/classes/Import/SimulateDml.php:150]: I did not know about that ...

Though I'm not sure how useful this feature is. Just listing the updated values without a full row context?

Comment (liviuconcioiu) [reply libraries/classes/Import/SimulateDml.php:150]: > I did not know about that ...
> 
> Though I'm not sure how useful this feature is. Just listing the updated values without a full row context?

Well, the feature was there and probably someone might use this.
