### PR TITLE
Fix #18232 - Fix issues when moving a column

### LINKED ISSUE #18232: TypeError: PhpMyAdmin\DatabaseInterface::quoteString(): Argument #1 ($str) must be of type string, bool given
### Describe the bug

`TypeError: PhpMyAdmin\DatabaseInterface::quoteString(): Argument #1 ($str) must be of type string, bool given, called in /home/demo/.pma-demo/master-config/libraries/classes/Table.php on line 627` when moving a column.

UPDATE 1: `TypeError: PhpMyAdmin\Table::generateAlter(): Argument #11 ($comment) must be of type string, bool given, called in /home/demo/.pma-demo/master-config/libraries/classes/Controllers/Table/Structure/MoveColumnsController.php on line 111`

UPDATE 2: `Internal error in .\libraries\classes\Table.php#786
TypeError: PhpMyAdmin\Table::generateAlter(): Argument #9 ($defaultValue) must be of type string, null given, called in \phpmyadmin\libraries\classes\Controllers\Table\Structure\MoveColumnsController.php on line 111
`

### To Reproduce

1. Go to any table structure
2. Move a column
3. See error

### Expected behavior

No error should be given.

### Screenshots

https://user-images.githubusercontent.com/25424343/223585702-5350c9b5-6bc6-4534-a318-f3ad7f597f37.mp4

### Server configuration

- phpMyAdmin version: 6.0.0-dev

### PR DESCRIPTION
**Pull request by liviuconcioiu**
### Description

This PR fixes the bugs that didn't allow a column to be moved. One issue with a column that hasn't a comment, and the other when a column is None.

Fixes #18232

### CODE REVIEW

File: libraries/classes/Controllers/Table/Structure/MoveColumnsController.php [hunk 1]
```diff
@@ -117,10 +117,9 @@ public function __invoke(ServerRequest $request): void
                 $data['Collation'] ?? '',
                 $data['Null'] === 'YES' ? 'YES' : 'NO',
                 $default_type,
-                $current_timestamp ? '' : $data['Default'],
```
Comment (williamdes) [inline libraries/classes/Controllers/Table/Structure/MoveColumnsController.php:120]: Can you search in git history why this `$current_timestamp` was added ?

Comment (liviuconcioiu) [reply libraries/classes/Controllers/Table/Structure/MoveColumnsController.php:120]: If I looked properly, it was added ~8 years ago.

https://github.com/phpmyadmin/phpmyadmin/blob/a599b615341e605fd9b47cd00bac70e171eb7954/libraries/controllers/TableStructureController.class.php

Comment (williamdes) [reply libraries/classes/Controllers/Table/Structure/MoveColumnsController.php:120]: Hmm, it's even older: https://github.com/phpmyadmin/phpmyadmin/pull/11332/files#diff-2169b9129e437365f8609b1da8195eabf6ed4e4e267afe2ee18dccff69ebc912R1052

It was added in #11332

I still do not see the reason, so let's remove it and figure out

**Review by williamdes — APPROVED** [review]

File: libraries/classes/Controllers/Table/Structure/MoveColumnsController.php (hunk 1 above)
Comment (williamdes) [reply libraries/classes/Controllers/Table/Structure/MoveColumnsController.php:120]: I am wrong, deeper it was addded in 95fa48fc8e479f8063876005e8e58093862093c8

And it was finally added by f76f0920a450a0c124fee86977dd29cc4e81640e !!

Comment (williamdes) [reply libraries/classes/Controllers/Table/Structure/MoveColumnsController.php:120]: Since the commit said "Move columns: feed generateAlter with same input as when editing single columns" could you check it does not break something like that ?

Comment (liviuconcioiu) [reply libraries/classes/Controllers/Table/Structure/MoveColumnsController.php:120]: I couldn't find any issues after this change, but I did find two other issues, not related to this change, for which I will open issues.

**Review by MauricioFauth — APPROVED** [review]
