### PR TITLE
Fix #18006 - UUID columns can't be moved

### LINKED ISSUE #18006: Moving columns causes the default uuid() value to get quotes around it
### Describe the bug

When I set a default value for a column that is `UUID` to `uuid()`, and use PHPMyAdmin to move it in the list of columns, and then use `show create table X`, I see that the `uuid()` would become `'uuid()'` and if I move it one more time, it becomes `'''uuid()'''`.

### To Reproduce

- Create a table with at least 3 columns
- Set two columns data types to be UUID
- Set default values for those two columns to `uuid()`
- Then use `Move column` feature to change the order of columns
  - Select the table
  - Go to `Structure` tab
  - Use `Move column` link (if you can't find it, search it inside the page)
- Then use `show create table X`
- You should see quotes around the default value
- If you move columns multiple times, then those quotes will increase in number

### Expected behavior

The default value `uuid()` should remain as is when we move columns (change the order of columns)

### Screenshots

From left hand (default state) we get to the right hand after moving columns around

Screenshot from 2023-01-07 16-19-15

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version: MariaDB
- phpMyAdmin version: latest

### Client configuration

- Browser: Chrome
- Operating system:

### Additional context

Add any other context about the bug here.

### PR DESCRIPTION
**Pull request by liviuconcioiu**
Signed-off-by: Liviu-Mihail Concioiu <liviu.concioiu@gmail.com>

### Description

This PR fixes the issue when uuid columns can't be moved.

Fixes #18006

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

File: libraries/classes/Controllers/Table/Structure/MoveColumnsController.php [hunk 1]
```diff
@@ -81,11 +81,17 @@ public function __invoke(): void
             $timeDefault = $data['Default'] === 'CURRENT_TIMESTAMP' || $data['Default'] === 'current_timestamp()';
             $current_timestamp = $timeType && $timeDefault;
 
+            $uuidType = $data['Type'] === 'uuid';
+            $uuidDefault = $data['Default'] === 'UUID' || $data['Default'] === 'uuid()';
+            $uuid = $uuidType && $uuidDefault;
```
Comment (kamil-tekiela) [inline libraries/classes/Controllers/Table/Structure/MoveColumnsController.php:86]: Could these 3 lines be extracted as a new method?

**Review by williamdes — APPROVED** [review]

File: libraries/classes/Controllers/Table/Structure/MoveColumnsController.php (hunk 1 above)
Comment (williamdes) [reply libraries/classes/Controllers/Table/Structure/MoveColumnsController.php:86]: I am merging this as it is, the above code looks alike
On master branch this could be improved
