### PR TITLE
Fix links to databases for information_schema.SCHEMATA

### LINKED ISSUE #17281: Table links from SCHEMA_NAME have the old link from QA_4_9
### Describe the bug

Table links from SCHEMA_NAME have the old link from QA_4_9. If you click on the table name, it redirects to a wrong link that gives a warning. The warning is shown only on master. On QA_5_1 there is no error, but still is the wrong link, and the table names inside the database aren't shown.

The current link is [https://demo.phpmyadmin.net/master/index.php?route=/sql&db=sakila](https://demo.phpmyadmin.net/master/index.php?route=/sql&db=sakila) instead of [https://demo.phpmyadmin.net/master/index.php?route=/database/structure&db=sakila](https://demo.phpmyadmin.net/master/index.php?route=/database/structure&db=sakila)

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master/index.php?route=/sql&db=information_schema&table=SCHEMATA](https://demo.phpmyadmin.net/master/index.php?route=/sql&db=information_schema&table=SCHEMATA)
2. Click on any table name
3. See error

### Expected behavior

The old route should be replace with the new route.

### Screenshots

route

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

```
Warning in ./libraries/classes/Dbal/DbiMysqli.php#181
 mysqli::query(): Empty query

Backtrace

DbiMysqli.php#181: mysqli->query(
string '',
integer 0,
)
DatabaseInterface.php#218: PhpMyAdmin\Dbal\DbiMysqli->realQuery(
string '',
,
integer 0,
)
Sql.php#622: PhpMyAdmin\DatabaseInterface->tryQuery(string '')
Sql.php#837: PhpMyAdmin\Sql->executeQueryAndMeasureTime(string '')
Sql.php#1730: PhpMyAdmin\Sql->executeTheQuery(
array,
string '',
boolean true,
string 'sakila',
string '',
NULL,
NULL,
NULL,
)
Sql.php#1621: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'sakila',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
string 'index.php?route=/database/structure',
NULL,
NULL,
string '',
NULL,
)
SqlController.php#212: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'sakila',
string '',
NULL,
NULL,
NULL,
NULL,
NULL,
string 'index.php?route=/database/structure',
NULL,
NULL,
string '',
NULL,
)
Routing.php#187: PhpMyAdmin\Controllers\Sql\SqlController->__invoke(
,
array,
)
index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/sql',
,
,
)
```

### PR DESCRIPTION
**Pull request by liviuconcioiu**
Signed-off-by: Liviu-Mihail Concioiu <liviu.concioiu@gmail.com>

### Description

This PR fixes the links to databases when this query is executed:
`SELECT * FROM information_schema.SCHEMATA;`

Fixes #17281

Before submitting pull request, please review the following checklist:

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Wow, thanks for the fix !

File: libraries/classes/Config/SpecialSchemaLinks.php [hunk 1]
```diff
@@ -66,7 +66,7 @@ public static function get(): array
     {
         global $cfg;
 
-        $defaultPage = './' . Util::getScriptNameForOption($cfg['DefaultTabTable'], 'table');
+        $defaultPage = './' . Util::getScriptNameForOption($cfg['DefaultTabTable'], 'database');
```
Comment (williamdes) [inline libraries/classes/Config/SpecialSchemaLinks.php:69]:
```suggestion
        $defaultPage = './' . Util::getScriptNameForOption($cfg['DefaultTabDatabase'], 'database');
```

I concluded this fix is wrong without this change. Any opinions @liviuconcioiu ?
https://github.com/phpmyadmin/phpmyadmin/blob/aeab8a1c4172c46190649a86d404487deac183ee/libraries/classes/Util.php#L1552-L1571

**Review by williamdes — CHANGES_REQUESTED** [review]
I did further testing and it breaks some other pages.
```sql
SELECT * FROM `columns_priv` ORDER BY `columns_priv`.`Host` ASC
```
It's probably better to have two default links, one for DBs and the other one for tables

**Review by williamdes — APPROVED** [review]
Thanks !
The diff looks nice, I will test it
