### PR TITLE
Fix #15863: Designer move menu icon not changing directions

### LINKED ISSUE #15863: Designer move menu icon not changing directions
### Describe the bug

The move menu icon in the designer toolbar doesn't toggle when clicked.

### To Reproduce

1. Go to Designer
2. Click on Move Menu icon at the bottom of the toolbar
3. See the bug

### Expected behavior

The icon should toggle between left and right.

### Server configuration

- Operating system: phpMyAdmin demo - MySQL (192.168.30.23 via TCP/IP
- Web server: nginx/1.10.3
- Database version: 8.0.18 - MySQL Community Server - GP
- PHP version: 7.4.0
- phpMyAdmin version: 5.0.1

### Client configuration

- Browser: Google Chrome
- Operating system: macOS Catalina 10.15.2

### Screenshots

[](https://gifyu.com/image/qlqH)

### PR DESCRIPTION
**Pull request by rabeehrz**
Signed-off-by: Mohammed Rabeeh <mohammadrabeeh@gmail.com>

### Description

Fixes issue #15863 

- [x] Make sure you have read our [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md) document.
- [x] Make sure you are making a pull request against the correct branch. For example, for bug fixes in a released version use the corresponding QA branch and for new features use the _master_ branch. If you have a doubt, you can ask as a comment in the bug report or on the mailing list.
- [x] Every commit has proper `Signed-off-by` line as described in our [DCO](https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO). This ensures that the work you're submitting is your own creation.
- [x] Every commit has a descriptive commit message.
- [x] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them.
- [x] Any new functionality is covered by tests.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
LGTM

File: js/designer/move.js [hunk 1]
```diff
@@ -1710,16 +1710,16 @@ DesignerMove.sideMenuRight = function (idThis) {
     $('#side_menu').toggleClass('right');
     $('#layer_menu').toggleClass('left');
     var icon = $(idThis.childNodes[0]);
+    var iconImg = $(idThis.childNodes[1]);
```
Comment (williamdes) [inline js/designer/move.js]: can you explain me why you use childNodes[1] ?
`temp1.getElementsByTagName('img')[0]` seems a more clear solution

Comment (rabeehrz) [reply js/designer/move.js]: I only used childNodes because that's how the icon was retrieved. I checked the code and saw that the icon and img were sibling elements. Do you want me to change it?

Comment (williamdes) [reply js/designer/move.js]: If you can make the two lines less position sensible it would be cool
I am afraid someone changes the order of the nodes and breaks the functionality

Comment (rabeehrz) [reply js/designer/move.js]: Okay, i'll change both the lines.

Comment (rabeehrz) [reply js/designer/move.js]: @williamdes I've made the changes you've requested. I read the code and tested some stuff out. It looks like the icon variable wasn't doing anything. It was meant to toggle the Move Menu icon originally, but it was written wrong. Please review and tell me if any changes are required. :)

File: js/designer/move.js [hunk 2]
```diff
@@ -1709,17 +1709,11 @@ DesignerMove.showLeftMenu = function (idThis) {
 DesignerMove.sideMenuRight = function (idThis) {
     $('#side_menu').toggleClass('right');
     $('#layer_menu').toggleClass('left');
-    var icon = $(idThis.childNodes[0]);
-    var current = icon.attr('src');
-    icon.attr('src', icon.attr('data-right')).attr('data-right', current);
-
-    icon = $(document.getElementById('layer_menu_sizer').childNodes[0])
-        .toggleClass('floatleft')
```
Comment (williamdes) [inline js/designer/move.js]: I am okay with your fix, but can you explain why the `toggleClass` lines are not more needed ?

Comment (rabeehrz) [reply js/designer/move.js]: @williamdes Hey, it turns on that there was another icon that needed toggling, apart from the Move Menu icon. It was the resizer icon. That toggle wasn't working in the first place becase childNodes[0] was incorrect and it was supposed to be childNodes[1]. I've added the toggleClass back and I've fixed the resizer icon as well. I'm very sorry for removing that. Please review and tell me if any changes are required.

Comment (williamdes) [reply js/designer/move.js]: Thank you, seems right now

**Comment by williamdes** [comment]
@rabeehrz I made more changes for he toggle resize button while reviewing.
I fixed the template, all good for your ?

**Comment by rabeehrz** [comment]
resizeIcon.attr('src', resizeIcon.attr('data-right'));
    resizeIcon.attr('data-right', resizeIcon.attr('src'));

    moveMenuIcon.attr('src', moveMenuIcon.attr('data-right'));
    moveMenuIcon.attr('data-right', moveMenuIcon.attr('src'));

@williamdes I don't think this swaps them. It isn't working. I think you need to use a third variable to swap the attributes.

**Comment by williamdes** [comment]
> @williamdes I don't think this swaps them. It isn't working. I think you need to use a third variable to swap the attributes.

Yes, sorry
I added the code back but renamed the variables

**Comment by rabeehrz** [comment]
@williamdes Yup looks good to me. Thank You for helping me with this! 😄

**Comment by williamdes** [comment]
:rocket:
