### PR TITLE
Fix bug in userDir

### LINKED ISSUE #20000: [Bug]: Import.php  open_basedir + PhpMyAdmin\FileListing->getFileSelectOptions
### Describe the bug

It is good practice to lock PHP down with open_basedir to prevent against file traversal attacks.

Import.php checks the folder '/' which throws an error.

```
Warning in ./libraries/classes/FileListing.php#33
 file_exists(): open_basedir restriction in effect. File(/) is not within the allowed path(s): (/home/devlocal/:/usr/lib/php/:/usr/local/:/usr/share/GeoIP/:/tmp/)
```

Backtrace:

```
FileListing.php#33: file_exists(string '/')
FileListing.php#80: PhpMyAdmin\FileListing->getDirContent(
string '/',
string '@\\.(csv|shp|txt|ods|sql|xml)(\\.(gz|zip))?$@',
)
Import.php#1539: PhpMyAdmin\FileListing->getFileSelectOptions(
string '/',
string '@\\.(csv|shp|txt|ods|sql|xml)(\\.(gz|zip))?$@',
string '',
```

### How to Reproduce

_No response_

### Expected behavior

_No response_

### Screenshots

_No response_

### Operating System

_No response_

### Web Server

_No response_

### Database Server

_No response_

### Database version

_No response_

### PHP version

_No response_

### phpMyAdmin version

5.2.3

### browser

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamil-tekiela**
Fixes #20000

### CODE REVIEW

File: libraries/classes/Util.php [hunk 1]
```diff
@@ -1253,7 +1253,7 @@ public static function getPageFromPosition($pos, $maxCount)
     public static function userDir(string $dir): string
     {
         // add trailing slash
-        if (mb_substr($dir, -1) !== '/') {
+        if ($dir !== '' && mb_substr($dir, -1) !== '/') {
```
Comment (williamdes) [inline libraries/classes/Util.php]: or if ($dir === '') return '';

Comment (williamdes) [reply libraries/classes/Util.php]: this would be easier to understand

**Review by williamdes — APPROVED** [review]
Thanks, ~~I will try to add a test~~
Thank you for the test !

**Review by MauricioFauth — APPROVED** [review]
